--○ 스터디원 신고 등록 테이블 생성
CREATE TABLE TBL_MEM_REPORT_REG
( MEM_REPORT_REG_CODE   VARCHAR2(12)
, PARTI_REPORT_CODE     VARCHAR2(12) NOT NULL
, REPORT_REG_DATE       DATE    DEFAULT SYSDATE NOT NULL
, MEM_REPORT_CTG_CODE   VARCHAR2(3) NOT NULL
, REPORT_REG_REASON     VARCHAR2(300)
, PARTI_REPORTED_CODE   VARCHAR2(12)    NOT NULL
, CONSTRAINT MEM_REP_REG_MRRC_PK PRIMARY KEY(MEM_REPORT_REG_CODE)
, CONSTRAINT MEM_REP_REG_PRC_FK FOREIGN KEY(PARTI_REPORT_CODE)
            REFERENCES TBL_STUDY_PARTICIPANT(PARTI_CODE)
, CONSTRAINT MEM_REP_REG_MRCC_FK FOREIGN KEY(MEM_REPORT_CTG_CODE)
            REFERENCES TBL_MEM_REPORT_CTG(MEM_REPORT_CTG_CODE)
, CONSTRAINT MEM_REP_REG_PRDC_FK FOREIGN KEY(PARTI_REPORTED_CODE)
            REFERENCES TBL_STUDY_PARTICIPANT(PARTI_CODE)
);

--○ 스터디원 신고 카테고리 테이블 생성
CREATE TABLE TBL_MEM_REPORT_CTG
( MEM_REPORT_CTG_CODE   VARCHAR2(3)
, MEM_REPORT_CTG        VARCHAR2(30) NOT NULL
, CONSTRAINT MEM_REP_CTG_MRCC_PK PRIMARY KEY(MEM_REPORT_CTG_CODE)
);

--○ 스터디원 신고 처리 테이블 생성
CREATE TABLE TBL_MEM_REPORT_HANDLE
( MEM_REPORT_HANDLE_CODE    VARCHAR2(12)
, MEM_REPORT_REG_CODE       VARCHAR2(12) NOT NULL
, HANDLE_RESULT             VARCHAR2(3) NOT NULL
, HANDEL_DATE               DATE DEFAULT SYSDATE NOT NULL
, CONSTRAINT MEM_REP_HDL_MRHC_PK PRIMARY KEY(MEM_REPORT_HANDLE_CODE)
, CONSTRAINT MEM_REP_HDL_MRRC_FK FOREIGN KEY(MEM_REPORT_REG_CODE)
            REFERENCES TBL_MEM_REPORT_REG(MEM_REPORT_REG_CODE)
, CONSTRAINT MEM_REP_HDL_HR_FK FOREIGN KEY(HANDLE_RESULT)
            REFERENCES TBL_MEM_REPORT_HANDLE_RESULT(MEM_REPORT_HANDLE_RESULT_CODE)
);

--○ 스터디원 처리 결과 테이블 생성
CREATE TABLE TBL_MEM_REPORT_HANDLE_RESULT
( MEM_REPORT_HANDLE_RESULT_CODE VARCHAR2(3)
, MEM_REPORT_HANDLE_RESULT      VARCHAR2(20) NOT NULL
, CONSTRAINT MEM_REP_HDL_RST_MRHRC_PK PRIMARY KEY(MEM_REPORT_HANDLE_RESULT_CODE)
);

--○ 내보내기 등록 테이블 생성
CREATE TABLE TBL_MEM_KICK_REG
( MEM_KICK_REG_CODE     VARCHAR2(12)
, PARTI_KICKED_CODE     VARCHAR2(12) NOT NULL
, PARTI_KICK_CODE       VARCHAR2(12) NOT NULL
, MEM_KICK_REG_DATE     DATE DEFAULT SYSDATE NOT NULL
, CONSTRAINT MEM_KICK_REG_MKRC_PK PRIMARY KEY(MEM_KICK_REG_CODE)
, CONSTRAINT MEM_KICK_REG_PKDC_FK FOREIGN KEY(PARTI_KICKED_CODE)
            REFERENCES TBL_STUDY_PARTICIPANT(PARTI_CODE)
, CONSTRAINT MEM_KICK_REG_PKC_FK FOREIGN KEY(PARTI_KICK_CODE)
            REFERENCES TBL_STUDY_PARTICIPANT(PARTI_CODE)
);

--○ 내보내기 처리 테이블 생성
CREATE TABLE TBL_MEM_KICK_HANDLE
( MEM_KICK_HANDLE_CODE VARCHAR2(12)
, MEM_KICK_REG_CODE     VARCHAR2(12) NOT NULL
, MEM_KICK_HANDLE_DATE  DATE DEFAULT SYSDATE NOT NULL
, CONSTRAINT MEM_KICK_HDL_MKHC_PK PRIMARY KEY(MEM_KICK_HANDLE_CODE)
, CONSTRAINT MEM_KICK_HDL_MKRC_FK FOREIGN KEY(MEM_KICK_REG_CODE)
            REFERENCES TBL_MEM_KICK_REG(MEM_KICK_REG_CODE)
);






