-- 먼저 C 드라이브에 StitkerData 폴더 만들어 놓기.

-- 테이블스페이스 생성
CREATE TABLESPACE TBS_STITKER
DATAFILE 'C:\StitkerData\TBS_STITKER01.DBF'
SIZE 30M
AUTOEXTEND ON NEXT 10M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

-- 사용자 계정 생성(이름 : stitker, 비번 : java006$, 테이블스페이스 : TBS_STITKER)
CREATE USER stitker IDENTIFIED BY java006$
DEFAULT TABLESPACE TBS_STITKER;

-- 계정 접속 권한 부여
GRANT CREATE SESSION TO STITKER;

-- 테이블 생성 권한 부여
GRANT CREATE TABLE TO STITKER;

-- 테이블스페이스 할당량 부여(용량제한X)
ALTER USER STITKER
QUOTA UNLIMITED ON TBS_STITKER;

-- 시퀀스 생성 권한 부여
GRANT CREATE SEQUENCE TO STITKER;

-- 뷰 생성 권한 부여
GRANT CREATE VIEW TO STITKER;

-- 프로시저 생성 권한 부여
GRANT CREATE PROCEDURE TO STITKER;

-- 트리거 생성 권한 부여
GRANT CREATE TRIGGER TO STITKER;









