
--○ 내 활동내역 뷰
CREATE OR REPLACE VIEW VIEW_ MyPage_Activity
AS
SELECT T.STUDY_NAME STUDY_NAME, T.USER_CODE USER_CODE
        , T.START_DATE START_DATE, T.END_DATE END_DATE
        ,   CASE WHEN T.START_DATE > SYSDATE THEN '대기중'
                    WHEN T.START_DATE <= SYSDATE AND T.END_DATE >= SYSDATE THEN '진행중'
                    WHEN T.END_DATE < SYSDATE THEN '스터디종료'
            END STUDY_STATE
FROM
(
SELECT E.STUDY_NAME STUDY_NAME
        ,  D.USER_CODE USER_CODE
        ,  E.START_DATE START_DATE , E.END_DATE END_DATE
        ,  CASE WHEN SUBSTR(D.POSITION_CODE, 3 , 1) IN ('1') THEN '개설자'
                   WHEN SUBSTR(D.POSITION_CODE, 3, 1) IN ('2') THEN '참가자'
                   ELSE '판별불가'
           END  "직책"
        ,  E.USER_CODE "개설자"
        ,  D.USER_CODE "직접개설"
FROM TBL_STUDY_OPEN E, TBL_STUDY_APPLY D
WHERE E.USER_CODE = D.USER_CODE
)T 
;


delete 
FROM VIEW_MyPage_Activity
commit


-- ○ 내정보, 내정보수정화면
CREATE OR REPLACE VIEW VIEW_MY_INF
AS
SELECT R.ID ID, R.NAME NAME, L.INTEREST_LC INTEREST_LC, M.INTEREST_MC INTEREST_MC, 
B.LOC_LC LOC_LC, A.LOC_MC LOC_MC, D.JOB_LC JOB_LC, C.JOB_MC JOB_MC, R.EMAIL EMAIL
FROM TBL_USER_REGISTER R, TBL_INTEREST_MC M, TBL_INTEREST_LC L
, TBL_LOC_MC A, TBL_LOC_LC B, TBL_JOB_MC C, TBL_JOB_LC D
WHERE R.INTEREST_MC_CODE = M.INTEREST_MC_CODE AND R.LOC_MC_CODE = A.LOC_MC_CODE
AND R.JOB_MC_CODE = C.JOB_MC_CODE AND M.INTEREST_LC_CODE = L.INTEREST_LC_CODE
AND A.LOC_LC_CODE = B.LOC_LC_CODE AND C.JOB_LC_CODE = D.JOB_LC_CODE;

select *
FROM MY_INF_VIEW;

-- ○ 계정탈퇴 뷰
CREATE OR REPLACE VIEW VIEW_MY_WITHDRAWAL
AS
SELECT R.ID ID, R.NAME NAME, M.INTEREST_MC INTEREST_MC
, B.LOC_LC LOC_LC, A.LOC_MC LOC_MC, C.JOB_MC JOB_MC, R.EMAIL EMAIL
, R.REGDATE REGDATE , S.STUDY_TYPE STUDY_TYPE
FROM TBL_USER_REGISTER R, TBL_INTEREST_MC M, TBL_INTEREST_LC L
, TBL_LOC_MC A, TBL_LOC_LC B, TBL_JOB_MC C, TBL_JOB_LC D, TBL_STUDY_TYPE S
WHERE R.INTEREST_MC_CODE = M.INTEREST_MC_CODE AND R.LOC_MC_CODE = A.LOC_MC_CODE
AND R.JOB_MC_CODE = C.JOB_MC_CODE AND M.INTEREST_LC_CODE = L.INTEREST_LC_CODE
AND A.LOC_LC_CODE = B.LOC_LC_CODE AND C.JOB_LC_CODE = D.JOB_LC_CODE
AND R.STUDY_TYPE_CODE = S.STUDY_TYPE_CODE ;

SELECT ID, ACCT_SUS_CODE, ACCT_SUS_DATE, ACCT_SUS_DATE_END FROM  VIEW_ACCOUNT_SUSPEND
WHERE ID = 'khj78';

--○ 계정정지 뷰 
CREATE OR REPLACE VIEW  VIEW_ACCOUNT_SUSPEND
AS
SELECT R.ID ID, S.ACCT_SUS_CODE ACCT_SUS_CODE
        , S.ACCT_SUS_DATE ACCT_SUS_DATE, S.ACCT_SUS_DATE+365 ACCT_SUS_DATE_END
FROM TBL_USER_REGISTER R ,TBL_WARNING W, TBL_ACCOUNT_SUSPEND S
WHERE R.USER_CODE = W.USER_CODE
   AND W.WARNING_CODE = S.WARNING_CODE;


/*
-- ○ 내 활동 내역(게시글)
CREATE OR REPLACE VIEW MyPage_Activity_BOARD_VIEW
AS
SELECT R.ID ID, I.TITLE ITITLE, N.TITLE NTITLE, S.TITLE STITLE, F.TITLE FTITLE, Q.TITLE QTITLE, A.TITLE ATITLE, T.TITLE TTITLE
FROM
 -- ① 내가 쓴 게시글
 TBL_USER_REGISTER R, TBL_BOARD_INFORM I, TBL_BOARD_INTERVIEW N , TBL_BOARD_SEMINAR S
, TBL_BOARD_FREE F, TBL_BOARD_QUESTION Q, TBL_BOARD_ANSWER A , TBL_BOARD_STUDYREVIEW T
WHERE R.USER_CODE = I.USER_CODE AND R.USER_CODE = N.USER_CODE
AND R.USER_CODE = S.USER_CODE AND R.USER_CODE = F.USER_CODE
AND R.USER_CODE = Q.USER_CODE AND R.USER_CODE = A.USER_CODE
AND R.USER_CODE = T.PARTI_CODE;
*/
-- ○ 내 활동 내역(게시글) -- 조인 수정
CREATE OR REPLACE VIEW VIEW_MyPage_Activity_BOARD
AS
SELECT R.ID ID, I.TITLE ITITLE, N.TITLE NTITLE, S.TITLE STITLE, F.TITLE FTITLE, Q.TITLE QTITLE, A.TITLE ATITLE, T.TITLE TTITLE
FROM
 -- ① 내가 쓴 게시글
 TBL_USER_REGISTER R JOIN TBL_BOARD_INFORM I ON R.USER_CODE = I.USER_CODE
LEFT JOIN TBL_BOARD_INTERVIEW N ON R.USER_CODE = N.USER_CODE
LEFT JOIN TBL_BOARD_SEMINAR S ON R.USER_CODE = S.USER_CODE
LEFT JOIN TBL_BOARD_FREE F ON R.USER_CODE = F.USER_CODE
LEFT JOIN TBL_BOARD_QUESTION Q ON R.USER_CODE = Q.USER_CODE
LEFT JOIN TBL_BOARD_ANSWER A ON R.USER_CODE = A.USER_CODE
LEFT JOIN TBL_BOARD_STUDYREVIEW T ON R.USER_CODE = T.PARTI_CODE;



/*
-- ○ 내 활동 내역(댓글) 
CREATE OR REPLACE VIEW MyPage_Activity_COMMENT_VIEW
AS
SELECT R.ID ID
, SUBSTR(I.COMMENTS,2,10) ICOMMENTS , I.WRITE_DATE IWRITE_DATE
, SUBSTR(N.COMMENTS,2,10) NCOMMENTS , N.WRITE_DATE NWRITE_DATE
, SUBSTR(S.COMMENTS,2,10) SCOMMENTS , S.WRITE_DATE SWRITE_DATE
, SUBSTR(F.COMMENTS,2,10) FCOMMENTS , F.WRITE_DATE FWRITE_DATE
, SUBSTR(Q.COMMENTS,2,10) QCOMMENTS , Q.WRITE_DATE QWRITE_DATE
, SUBSTR(A.COMMENTS,2,10) ACOMMENTS , A.WRITE_DATE AWRITE_DATE
, SUBSTR(T.COMMENTS,2,10) TCOMMENTS , T.WRITE_DATE TWRITE_DATE
FROM
 -- ① 내가 쓴 댓글
 TBL_USER_REGISTER R, TBL_COMMENT_INFORM I, TBL_COMMENT_INTERVIEW N , TBL_COMMENT_SEMINAR S
, TBL_COMMENT_FREE F, TBL_COMMENT_QUESTION Q, TBL_COMMENT_ANSWER A , TBL_COMMENT_STUDYREVIEW T
WHERE R.USER_CODE = I.USER_CODE AND R.USER_CODE = N.USER_CODE
AND R.USER_CODE = S.USER_CODE AND R.USER_CODE = F.USER_CODE
AND R.USER_CODE = Q.USER_CODE AND R.USER_CODE = A.USER_CODE
AND R.USER_CODE = T.USER_CODE;
*/

-- ○ 내 활동 내역(댓글) -- 조인 수정
CREATE OR REPLACE VIEW VIEW_MyPage_Activity_COMMENT
AS
SELECT R.ID ID
, SUBSTR(I.COMMENTS,2,10) ICOMMENTS , I.WRITE_DATE IWRITE_DATE
, SUBSTR(N.COMMENTS,2,10) NCOMMENTS , N.WRITE_DATE NWRITE_DATE
, SUBSTR(S.COMMENTS,2,10) SCOMMENTS , S.WRITE_DATE SWRITE_DATE
, SUBSTR(F.COMMENTS,2,10) FCOMMENTS , F.WRITE_DATE FWRITE_DATE
, SUBSTR(Q.COMMENTS,2,10) QCOMMENTS , Q.WRITE_DATE QWRITE_DATE
, SUBSTR(A.COMMENTS,2,10) ACOMMENTS , A.WRITE_DATE AWRITE_DATE
, SUBSTR(T.COMMENTS,2,10) TCOMMENTS , T.WRITE_DATE TWRITE_DATE
FROM
 -- ① 내가 쓴 댓글
TBL_USER_REGISTER R  JOIN TBL_COMMENT_INFORM I ON R.USER_CODE = I.USER_CODE
LEFT JOIN TBL_COMMENT_INTERVIEW N ON R.USER_CODE = N.USER_CODE
LEFT JOIN TBL_COMMENT_SEMINAR S ON R.USER_CODE = S.USER_CODE
LEFT JOIN TBL_COMMENT_FREE F ON R.USER_CODE = F.USER_CODE
LEFT JOIN TBL_COMMENT_QUESTION Q ON R.USER_CODE = Q.USER_CODE
LEFT JOIN  TBL_COMMENT_ANSWER A ON R.USER_CODE = A.USER_CODE
LEFT JOIN  TBL_COMMENT_STUDYREVIEW T ON R.USER_CODE = T.USER_CODE;



