--○ 관심분야 중분류 뷰(말머리 조회에 사용)
CREATE OR REPLACE VIEW VIEW_INTEREST
AS
SELECT M.INTEREST_MC INTEREST_MC
FROM TBL_INTEREST_MC M, TBL_INTEREST_LC L
WHERE M.INTEREST_LC_CODE = L.INTEREST_LC_CODE AND L.INTEREST_LC_CODE ='3241';

--○ 세미나/공모전 말머리 뷰 (말머리 조회에 사용)
CREATE OR REPLACE VIEW VIEW_SEMINAR_CTG
AS
SELECT SEMINAR_CATEGORY
FROM TBL_SEMINAR_CATEGORY
ORDER BY 1;