--○ 관심분야 중분류 뷰(말머리 조회에 사용)
CREATE OR REPLACE VIEW VIEW_INTEREST
AS
SELECT M.INTEREST_MC INTEREST_MC
FROM TBL_INTEREST_MC M, TBL_INTEREST_LC L
WHERE M.INTEREST_LC_CODE = L.INTEREST_LC_CODE AND L.INTEREST_LC_CODE ='3241';

--○ 세미나/공모전 말머리 뷰 (말머리 조회에 사용)ㅎ
CREATE OR REPLACE VIEW VIEW_SEMINAR_CTG
AS
SELECT SEMINAR_CATEGORY
FROM TBL_SEMINAR_CATEGORY
ORDER BY 1;



--○ 기술정보공유 게시판 추천수 탑3
CREATE OR REPLACE VIEW VIEW_INFORM_REC_RANK3
AS
SELECT R.COUNT COUNT, R.POST_CODE POST_CODE
FROM
(
    SELECT COUNT(*) COUNT, POST_CODE
    FROM TBL_REC_INFORM
    WHERE REC_CHECK ='추천'
    GROUP BY POST_CODE
    ORDER BY COUNT
) R, TBL_BOARD_INFORM B
WHERE ROWNUM<=3 AND R.POST_CODE = B.POST_CODE;




