--○ VIEW 생성(IT기술정보공유 게시판 리스트)
--   IT기술정보공유 테이블, IT기술정보공유 추천비추천 테이블, 관심분야 중분류 카테고리 테이블
CREATE OR REPLACE VIEW BOARD_INFORM_VIEW
AS
SELECT T.POST_CODE, T.USER_CODE, T.WRITE_DATE, T.HITCOUNT, T.TITLE, T.REC, T.NOTREC, T.INTEREST_MC
FROM 
(
SELECT BI.POST_CODE "POST_CODE", BI.USER_CODE "USER_CODE", BI.WRITE_DATE "WRITE_DATE"
     , BI.HITCOUNT "HITCOUNT", BI.TITLE "TITLE", ROW_NUMBER() OVER (PARTITION BY BI.POST_CODE ORDER BY BI.POST_CODE) "RNUM"
     , (SELECT COUNT(*)
        FROM TBL_REC_INFORM
        WHERE REC_CHECK = 1 AND POST_CODE = BI.POST_CODE) "REC"
     , (SELECT COUNT(*)
         FROM TBL_REC_INFORM
        WHERE REC_CHECK = 2 AND POST_CODE = BI.POST_CODE) "NOTREC"
     , IM.INTEREST_MC "INTEREST_MC"
FROM TBL_BOARD_INFORM BI FULL OUTER JOIN TBL_REC_INFORM RI
ON BI.POST_CODE = RI.POST_CODE
    JOIN TBL_INTEREST_MC IM
    ON BI.INTEREST_MC_CODE = IM.INTEREST_MC_CODE
) T
WHERE RNUM = 1;

--○ VIEW 생성(면접/코딩테스트 게시판 리스트)
--   면접/코딩테스트 테이블, 면접/코딩테스트 추천비추천 테이블, 관심분야 중분류 카테고리 테이블
CREATE OR REPLACE VIEW BOARD_INTERVIEW_VIEW
AS
SELECT T.POST_CODE, T.USER_CODE, T.WRITE_DATE, T.HITCOUNT, T.TITLE, T.REC, T.NOTREC, T.INTEREST_MC
FROM 
(SELECT BV.POST_CODE "POST_CODE", BV.USER_CODE "USER_CODE", BV.WRITE_DATE "WRITE_DATE"
     , BV.HITCOUNT "HITCOUNT", BV.TITLE "TITLE", ROW_NUMBER() OVER (PARTITION BY BV.POST_CODE ORDER BY BV.POST_CODE) "RNUM"
     , (SELECT COUNT(*)
        FROM TBL_REC_INTERVIEW
        WHERE REC_CHECK = 1 AND POST_CODE = BV.POST_CODE) "REC"
     , (SELECT COUNT(*)
         FROM TBL_REC_INTERVIEW
        WHERE REC_CHECK = 2 AND POST_CODE = BV.POST_CODE) "NOTREC"
     , IM.INTEREST_MC "INTEREST_MC"
FROM TBL_BOARD_INTERVIEW BV FULL OUTER JOIN TBL_REC_INTERVIEW RV
ON BV.POST_CODE = RV.POST_CODE
    JOIN TBL_INTEREST_MC IM
    ON BV.INTEREST_MC_CODE = IM.INTEREST_MC_CODE
) T
WHERE RNUM = 1;

--○ VIEW 생성(세미나 및 공모전 게시판 리스트)
--   세미나 및 공모전 테이블, 세미나 및 공모전 추천비추천 테이블, 세미나 말머리 테이블
CREATE OR REPLACE VIEW BOARD_SEMINAR_VIEW
AS
SELECT T.POST_CODE, T.USER_CODE, T.WRITE_DATE, T.HITCOUNT, T.TITLE, T.REC, T.NOTREC, T.SEMINAR_CTG
FROM 
(SELECT BS.POST_CODE "POST_CODE", BS.USER_CODE "USER_CODE", BS.WRITE_DATE "WRITE_DATE"
     , BS.HITCOUNT "HITCOUNT", BS.TITLE "TITLE", ROW_NUMBER() OVER (PARTITION BY BS.POST_CODE ORDER BY BS.POST_CODE) "RNUM"
     , (SELECT COUNT(*)
        FROM TBL_REC_SEMINAR
        WHERE REC_CHECK = 1 AND POST_CODE = BS.POST_CODE) "REC"
     , (SELECT COUNT(*)
         FROM TBL_REC_SEMINAR
        WHERE REC_CHECK = 2 AND POST_CODE = BS.POST_CODE) "NOTREC"
     ,SC.SEMINAR_CATEGORY "SEMINAR_CTG"
FROM TBL_BOARD_SEMINAR BS FULL OUTER JOIN TBL_REC_SEMINAR RS
ON BS.POST_CODE = RS.POST_CODE
    JOIN TBL_SEMINAR_CATEGORY SC
    ON BS.SEMINAR_CATEGORY_CODE = SC.SEMINAR_CATEGORY_CODE
) T
WHERE RNUM = 1;
    
--○ VIEW 생성(Q&A 게시판 리스트)
--   QUSTION테이블, ANSWER 테이블, QUESTION 추천비추천 테이블, ANSWER 추천비추천 테이블, 관심분야 중분류 카테고리 테이블
CREATE OR REPLACE VIEW BOARD_QUESTION_VIEW
AS
SELECT T.QPOST_CODE, T.QUSER_CODE, T.QWRITE_DATE, T.QHITCOUNT, T.QTITLE, T.QREC, T.QNOTREC, T.INTEREST_MC
     , T.APOST_CODE, T.AUSER_CODE, T.AWRITE_DATE, T.AHITCOUNT, T.ATITLE, T.AREC, T.ANOTREC
FROM 
(SELECT BQ.POST_CODE "QPOST_CODE", BQ.USER_CODE "QUSER_CODE", BQ.WRITE_DATE "QWRITE_DATE"
     , BQ.HITCOUNT "QHITCOUNT", BQ.TITLE "QTITLE", BA.POST_CODE "APOST_CODE"
     , BA.USER_CODE "AUSER_CODE", BA.WRITE_DATE "AWRITE_DATE"
     , BA.HITCOUNT "AHITCOUNT", BA.TITLE "ATITLE"
     , (SELECT COUNT(*)
        FROM TBL_REC_QUESTION
        WHERE REC_CHECK = 1 AND POST_CODE = BQ.POST_CODE) "QREC"
     , (SELECT COUNT(*)
         FROM TBL_REC_QUESTION
        WHERE REC_CHECK = 2 AND POST_CODE = BQ.POST_CODE) "QNOTREC"
     , (SELECT COUNT(*)
        FROM TBL_REC_ANSWER
        WHERE REC_CHECK = 1 AND POST_CODE = BA.POST_CODE) "AREC"
     , (SELECT COUNT(*)
         FROM TBL_REC_ANSWER
        WHERE REC_CHECK = 2 AND POST_CODE = BA.POST_CODE) "ANOTREC"
     , IM.INTEREST_MC "INTEREST_MC", ROW_NUMBER() OVER (PARTITION BY BQ.POST_CODE ORDER BY BQ.POST_CODE) "RNUM"
FROM TBL_BOARD_QUESTION BQ JOIN TBL_BOARD_ANSWER BA
ON BQ.POST_CODE = BA.QPOST_CODE
    JOIN TBL_INTEREST_MC IM
    ON BQ.INTEREST_MC_CODE = IM.INTEREST_MC_CODE
        FULL OUTER JOIN TBL_REC_QUESTION RQ
        ON BQ.POST_CODE = RQ.POST_CODE
            FULL OUTER JOIN TBL_REC_ANSWER RA
            ON BA.POST_CODE = RA.POST_CODE
) T
WHERE RNUM = 1;
        
            
--○ VIEW 생성(스터디리뷰 게시판 리스트)
--   스터디리뷰 테이블, 스터디리뷰 추천비추천 테이블, 관심분야 중분류 카테고리 테이블
CREATE OR REPLACE VIEW BOARD_STUDYREVIEW_VIEW
AS
SELECT T.POST_CODE, T.PARTI_CODE, T.WRITE_DATE, T.HITCOUNT, T.TITLE, T.REC, T.NOTREC, T.INTEREST_MC
FROM
(SELECT BR.POST_CODE "POST_CODE", BR.PARTI_CODE "PARTI_CODE", BR.WRITE_DATE "WRITE_DATE"
     , BR.HITCOUNT "HITCOUNT", BR.TITLE "TITLE"
     , (SELECT COUNT(*)
        FROM TBL_REC_STUDYREVIEW
        WHERE REC_CHECK = 1 AND POST_CODE = BR.POST_CODE) "REC"
     , (SELECT COUNT(*)
         FROM TBL_REC_STUDYREVIEW
        WHERE REC_CHECK = 2 AND POST_CODE = BR.POST_CODE) "NOTREC"
     , ROW_NUMBER() OVER (PARTITION BY BR.POST_CODE ORDER BY BR.POST_CODE) "RNUM"
     , IM.INTEREST_MC "INTEREST_MC"
FROM TBL_BOARD_STUDYREVIEW BR FULL OUTER JOIN TBL_REC_STUDYREVIEW RR
ON BR.POST_CODE = RR.POST_CODE
    JOIN TBL_INTEREST_MC IM
    ON BR.INTEREST_MC_CODE = IM.INTEREST_MC_CODE
) T
WHERE RNUM = 1;
  
--○ VIEW 생성(자유게시판 리스트)
--   자유게시판 테이블, 자유게시판 추천비추천 테이블
CREATE OR REPLACE VIEW BOARD_FREE_VIEW
AS
SELECT T.POST_CODE, T.USER_CODE, T.WRITE_DATE, T.HITCOUNT, T.TITLE, T.REC, T.NOTREC
FROM
(SELECT BF.POST_CODE "POST_CODE", BF.USER_CODE "USER_CODE", BF.WRITE_DATE "WRITE_DATE"
     , BF.HITCOUNT "HITCOUNT", BF.TITLE "TITLE"
     , (SELECT COUNT(*)
        FROM TBL_REC_FREE
        WHERE REC_CHECK = 1 AND POST_CODE = BF.POST_CODE) "REC"
     , (SELECT COUNT(*)
         FROM TBL_REC_FREE
        WHERE REC_CHECK = 2 AND POST_CODE = BF.POST_CODE) "NOTREC"
     , ROW_NUMBER() OVER (PARTITION BY BF.POST_CODE ORDER BY BF.POST_CODE) "RNUM"
FROM TBL_BOARD_FREE BF FULL OUTER JOIN TBL_REC_FREE RF
ON BF.POST_CODE = RF.POST_CODE
) T
WHERE RNUM = 1;



--○ VIEW 생성(자유게시판 상세페이지)
--   자유게시판 테이블, 자유게시판 추천비추천 테이블
CREATE OR REPLACE VIEW DETAILPG_FREE_VIEW
AS
SELECT T.POST_CODE, T.USER_CODE, T.WRITE_DATE, T.HITCOUNT, T.TITLE, T.CONTENT, T.REC, T.NOTREC
FROM
(SELECT BF.POST_CODE "POST_CODE", BF.USER_CODE "USER_CODE", BF.WRITE_DATE "WRITE_DATE"
     , BF.HITCOUNT "HITCOUNT", BF.TITLE "TITLE", BF.CONTENT "CONTENT"
     , (SELECT COUNT(*)
        FROM TBL_REC_FREE
        WHERE REC_CHECK = 1 AND POST_CODE = BF.POST_CODE) "REC"
     , (SELECT COUNT(*)
         FROM TBL_REC_FREE
        WHERE REC_CHECK = 2 AND POST_CODE = BF.POST_CODE) "NOTREC"
     , ROW_NUMBER() OVER (PARTITION BY BF.POST_CODE ORDER BY BF.POST_CODE) "RNUM"
FROM TBL_BOARD_FREE BF FULL OUTER JOIN TBL_REC_FREE RF
ON BF.POST_CODE = RF.POST_CODE
) T
WHERE T.POST_CODE = 'BF1' AND RNUM = 1;

--○ VIEW 생성(IT정보공유게시판 상세페이지)
--   IT정보공유게시판 테이블, IT정보공유게시판 추천비추천 테이블
CREATE OR REPLACE VIEW DETAILPG_INFORM_VIEW
AS
SELECT T.POST_CODE, T.USER_CODE, T.WRITE_DATE, T.HITCOUNT, T.TITLE, T.CONTENT, T.REC, T.NOTREC, T.INTEREST_MC
FROM 
(
SELECT BI.POST_CODE "POST_CODE", BI.USER_CODE "USER_CODE", BI.WRITE_DATE "WRITE_DATE"
     , BI.HITCOUNT "HITCOUNT", BI.TITLE "TITLE", ROW_NUMBER() OVER (PARTITION BY BI.POST_CODE ORDER BY BI.POST_CODE) "RNUM"
     , (SELECT COUNT(*)
        FROM TBL_REC_INFORM
        WHERE REC_CHECK = 1 AND POST_CODE = BI.POST_CODE) "REC"
     , (SELECT COUNT(*)
         FROM TBL_REC_INFORM
        WHERE REC_CHECK = 2 AND POST_CODE = BI.POST_CODE) "NOTREC"
     , IM.INTEREST_MC "INTEREST_MC", BI.CONTENT "CONTENT"
FROM TBL_BOARD_INFORM BI FULL OUTER JOIN TBL_REC_INFORM RI
ON BI.POST_CODE = RI.POST_CODE
    JOIN TBL_INTEREST_MC IM
    ON BI.INTEREST_MC_CODE = IM.INTEREST_MC_CODE
) T
WHERE T.POST_CODE = 'BI1' AND RNUM = 1;


--○ VIEW 생성(면접/코딩테스트 후기 상세페이지)
--   면접/코딩테스트 후기 테이블, 면접/코딩테스트 후기 추천비추천 테이블
CREATE OR REPLACE VIEW DETAILPG_INTERVIEW_VIEW
AS
SELECT T.POST_CODE, T.USER_CODE, T.WRITE_DATE, T.HITCOUNT, T.TITLE, T.CONTENT, T.REC, T.NOTREC 
     , T.INTEREST_MC
FROM 
(SELECT BV.POST_CODE "POST_CODE", BV.USER_CODE "USER_CODE", BV.WRITE_DATE "WRITE_DATE"
     , BV.HITCOUNT "HITCOUNT", BV.TITLE "TITLE", ROW_NUMBER() OVER (PARTITION BY BV.POST_CODE ORDER BY BV.POST_CODE) "RNUM"
     , (SELECT COUNT(*)
        FROM TBL_REC_INTERVIEW
        WHERE REC_CHECK = 1 AND POST_CODE = BV.POST_CODE) "REC"
     , (SELECT COUNT(*)
         FROM TBL_REC_INTERVIEW
        WHERE REC_CHECK = 2 AND POST_CODE = BV.POST_CODE) "NOTREC"
     , IM.INTEREST_MC "INTEREST_MC", BV.CONTENT "CONTENT"
FROM TBL_BOARD_INTERVIEW BV FULL OUTER JOIN TBL_REC_INTERVIEW RV
ON BV.POST_CODE = RV.POST_CODE
    JOIN TBL_INTEREST_MC IM
    ON BV.INTEREST_MC_CODE = IM.INTEREST_MC_CODE
) T
WHERE RNUM = 1 AND T.POST_CODE = 'BV1';



--○ VIEW 생성(Q&A 질문 상세페이지)
--   Q&A 질문 테이블, Q&A 질문 추천비추천 테이블
CREATE OR REPLACE VIEW DETAILPG_QUESTION_VIEW
AS
SELECT T.QPOST_CODE, T.QUSER_CODE, T.QWRITE_DATE, T.QHITCOUNT, T.QTITLE, T.QCONTENT, T.QREC
     , T.QNOTREC, T.INTEREST_MC
FROM 
(SELECT BQ.POST_CODE "QPOST_CODE", BQ.USER_CODE "QUSER_CODE", BQ.WRITE_DATE "QWRITE_DATE"
     , BQ.HITCOUNT "QHITCOUNT", BQ.TITLE "QTITLE", BQ.CONTENT "QCONTENT"
     , (SELECT COUNT(*)
        FROM TBL_REC_QUESTION
        WHERE REC_CHECK = 1 AND POST_CODE = BQ.POST_CODE) "QREC"
     , (SELECT COUNT(*)
         FROM TBL_REC_QUESTION
        WHERE REC_CHECK = 2 AND POST_CODE = BQ.POST_CODE) "QNOTREC"
     , IM.INTEREST_MC "INTEREST_MC", ROW_NUMBER() OVER (PARTITION BY BQ.POST_CODE ORDER BY BQ.POST_CODE) "RNUM"
FROM TBL_BOARD_QUESTION BQ 
FULL OUTER JOIN TBL_REC_QUESTION RQ
ON BQ.POST_CODE = RQ.POST_CODE
    JOIN TBL_INTEREST_MC IM
    ON BQ.INTEREST_MC_CODE = IM.INTEREST_MC_CODE
) T
WHERE RNUM = 1 AND T.QPOST_CODE = 'BQ7';


--○ VIEW 생성(Q&A 답변 상세페이지)
--   Q&A 답변 테이블, Q&A 답변 추천비추천 테이블
CREATE OR REPLACE VIEW DETAILPG_ANSWER_VIEW
AS
SELECT T.APOST_CODE, T.AUSER_CODE, T.AWRITE_DATE, T.AHITCOUNT, T.ATITLE, T.ACONTENT, T.AREC
     , T.ANOTREC, T.INTEREST_MC
FROM 
(SELECT BA.POST_CODE "APOST_CODE", BA.USER_CODE "AUSER_CODE", BA.WRITE_DATE "AWRITE_DATE"
     , BA.HITCOUNT "AHITCOUNT", BA.TITLE "ATITLE", BA.CONTENT "ACONTENT"
     , (SELECT COUNT(*)
        FROM TBL_REC_ANSWER
        WHERE REC_CHECK = 1 AND POST_CODE = BA.POST_CODE) "AREC"
     , (SELECT COUNT(*)
         FROM TBL_REC_ANSWER
        WHERE REC_CHECK = 2 AND POST_CODE = BA.POST_CODE) "ANOTREC"
     , IM.INTEREST_MC "INTEREST_MC", ROW_NUMBER() OVER (PARTITION BY BQ.POST_CODE ORDER BY BQ.POST_CODE) "RNUM"
FROM TBL_BOARD_ANSWER BA 
FULL OUTER JOIN TBL_REC_ANSWER RA
ON BA.POST_CODE = RA.POST_CODE
    JOIN TBL_BOARD_QUESTION BQ
    ON BA.QPOST_CODE = BQ.POST_CODE
        JOIN TBL_INTEREST_MC IM
        ON BQ.INTEREST_MC_CODE = IM.INTEREST_MC_CODE
) T
WHERE RNUM = 1 AND T.APOST_CODE = 'BA1';
           

--○ VIEW 생성(스터디리뷰 게시판 상세페이지)
--   스터디리뷰 테이블, 스터디리뷰 추천비추천 테이블, 관심분야 중분류 카테고리 테이블
CREATE OR REPLACE VIEW DETAILPG_STUDYREVIEW_VIEW
AS
SELECT T.POST_CODE, T.PARTI_CODE, T.WRITE_DATE, T.HITCOUNT, T.TITLE, T.CONTENT, T.REC, T.NOTREC, T.INTEREST_MC
FROM
(SELECT BR.POST_CODE "POST_CODE", BR.PARTI_CODE "PARTI_CODE", BR.WRITE_DATE "WRITE_DATE"
     , BR.HITCOUNT "HITCOUNT", BR.TITLE "TITLE"
     , (SELECT COUNT(*)
        FROM TBL_REC_STUDYREVIEW
        WHERE REC_CHECK = 1 AND POST_CODE = BR.POST_CODE) "REC"
     , (SELECT COUNT(*)
         FROM TBL_REC_STUDYREVIEW
        WHERE REC_CHECK = 2 AND POST_CODE = BR.POST_CODE) "NOTREC"
     , ROW_NUMBER() OVER (PARTITION BY BR.POST_CODE ORDER BY BR.POST_CODE) "RNUM"
     , IM.INTEREST_MC "INTEREST_MC",  BR.CONTENT "CONTENT"
FROM TBL_BOARD_STUDYREVIEW BR FULL OUTER JOIN TBL_REC_STUDYREVIEW RR
ON BR.POST_CODE = RR.POST_CODE
    JOIN TBL_INTEREST_MC IM
    ON BR.INTEREST_MC_CODE = IM.INTEREST_MC_CODE
) T
WHERE RNUM = 1 AND T.POST_CODE = 'BR5';


--○ VIEW 생성(세미나 및 공모전 게시판 상세페이지)
--   스터디리뷰 테이블, 스터디리뷰 추천비추천 테이블, 관심분야 중분류 카테고리 테이블
CREATE OR REPLACE VIEW DETAILPG_STUDYREVIEW_VIEW
AS
SELECT T.POST_CODE, T.USER_CODE, T.WRITE_DATE, T.HITCOUNT, T.TITLE, T.CONTENT, T.REC, T.NOTREC, T.SEMINAR_CTG
FROM 
(SELECT BS.POST_CODE "POST_CODE", BS.USER_CODE "USER_CODE", BS.WRITE_DATE "WRITE_DATE"
     , BS.HITCOUNT "HITCOUNT", BS.TITLE "TITLE", ROW_NUMBER() OVER (PARTITION BY BS.POST_CODE ORDER BY BS.POST_CODE) "RNUM"
     , (SELECT COUNT(*)
        FROM TBL_REC_SEMINAR
        WHERE REC_CHECK = 1 AND POST_CODE = BS.POST_CODE) "REC"
     , (SELECT COUNT(*)
         FROM TBL_REC_SEMINAR
        WHERE REC_CHECK = 2 AND POST_CODE = BS.POST_CODE) "NOTREC"
     ,SC.SEMINAR_CATEGORY "SEMINAR_CTG", BS.CONTENT "CONTENT"
FROM TBL_BOARD_SEMINAR BS FULL OUTER JOIN TBL_REC_SEMINAR RS
ON BS.POST_CODE = RS.POST_CODE
    JOIN TBL_SEMINAR_CATEGORY SC
    ON BS.SEMINAR_CATEGORY_CODE = SC.SEMINAR_CATEGORY_CODE
) T
WHERE RNUM = 1 AND T.POST_CODE = 'BS1';
                        