--■■■ 뷰(VIEW) 생성 ■■■--
--※SELECT로 먼저 조회한 후 CREATE VIEW 하기

SELECT *
FROM TBL_REPORT_HANDLE_INFORM
UNION ALL
SELECT *
FROM TBL_REPORT_HANDLE_SEMINAR
UNION ALL
SELECT *
FROM TBL_REPORT_HANDLE_INTERVIEW
UNION ALL
SELECT *
FROM TBL_REPORT_HANDLE_FREE
UNION ALL
SELECT *
FROM TBL_REPORT_HANDLE_QUESTION
UNION ALL
SELECT *
FROM TBL_REPORT_HANDLE_ANSWER
UNION ALL
SELECT *
FROM TBL_REPORT_HANDLE_STUDYREVIEW;

-- ○ Board_report_list.jsp(각종 게시판 신고처리를 위한 리스트 뷰 - 작성자, 글제목, 내용, 신고처리결과, 신고처리날짜)
-- ○ 뷰 이름 : RH_BOARD_VIEW
CREATE OR REPLACE VIEW RH_BOARDLIST_VIEW 
AS
SELECT B.USER_CODE, B.POST_CODE, B.TITLE, HR.HANDLE_RESULT, H.HANDLE_DATE
FROM TBL_REPORT_HANDLE_INFORM H JOIN TBL_REPORT_REG_INFORM R
  ON R.POST_REPORT_CODE = H.POST_REPORT_CODE
    JOIN TBL_BOARD_INFORM B
    ON B.POST_CODE = R.POST_CODE
      LEFT JOIN TBL_HANDLE_RESULT HR
      ON HR.HANDLE_RESULT_CODE = H.HANDLE_RESULT_CODE
UNION ALL
SELECT B.USER_CODE, B.POST_CODE, B.TITLE, HR.HANDLE_RESULT, H.HANDLE_DATE
FROM TBL_REPORT_HANDLE_INTERVIEW H JOIN TBL_REPORT_REG_INTERVIEW R
  ON R.POST_REPORT_CODE = H.POST_REPORT_CODE
    JOIN TBL_BOARD_INTERVIEW B
    ON B.POST_CODE = R.POST_CODE
      LEFT JOIN TBL_HANDLE_RESULT HR
      ON HR.HANDLE_RESULT_CODE = H.HANDLE_RESULT_CODE
UNION ALL
SELECT B.USER_CODE, B.POST_CODE, B.TITLE, HR.HANDLE_RESULT, H.HANDLE_DATE
FROM TBL_REPORT_HANDLE_SEMINAR H JOIN TBL_REPORT_REG_SEMINAR R
  ON R.POST_REPORT_CODE = H.POST_REPORT_CODE
    JOIN TBL_BOARD_SEMINAR B
    ON B.POST_CODE = R.POST_CODE
      LEFT JOIN TBL_HANDLE_RESULT HR
      ON HR.HANDLE_RESULT_CODE = H.HANDLE_RESULT_CODE
UNION ALL      
SELECT B.USER_CODE, B.POST_CODE, B.TITLE, HR.HANDLE_RESULT, H.HANDLE_DATE
FROM TBL_REPORT_HANDLE_FREE H JOIN TBL_REPORT_REG_FREE R
  ON R.POST_REPORT_CODE = H.POST_REPORT_CODE
    JOIN TBL_BOARD_FREE B
    ON B.POST_CODE = R.POST_CODE
      LEFT JOIN TBL_HANDLE_RESULT HR
      ON HR.HANDLE_RESULT_CODE = H.HANDLE_RESULT_CODE
UNION ALL      
SELECT B.USER_CODE, B.POST_CODE, B.TITLE, HR.HANDLE_RESULT, H.HANDLE_DATE
FROM TBL_REPORT_HANDLE_QUESTION H JOIN TBL_REPORT_REG_QUESTION R
  ON R.POST_REPORT_CODE = H.POST_REPORT_CODE
    JOIN TBL_BOARD_QUESTION B
    ON B.POST_CODE = R.POST_CODE
      LEFT JOIN TBL_HANDLE_RESULT HR
      ON HR.HANDLE_RESULT_CODE = H.HANDLE_RESULT_CODE
UNION ALL      
SELECT B.USER_CODE, B.POST_CODE, B.TITLE, HR.HANDLE_RESULT, H.HANDLE_DATE
FROM TBL_REPORT_HANDLE_ANSWER H JOIN TBL_REPORT_REG_ANSWER R
  ON R.POST_REPORT_CODE = H.POST_REPORT_CODE
    JOIN TBL_BOARD_ANSWER B
    ON B.POST_CODE = R.POST_CODE
      LEFT JOIN TBL_HANDLE_RESULT HR
      ON HR.HANDLE_RESULT_CODE = H.HANDLE_RESULT_CODE
UNION ALL
SELECT A.USER_CODE, B.POST_CODE, B.TITLE, HR.HANDLE_RESULT, H.HANDLE_DATE
FROM TBL_REPORT_HANDLE_STUDYREVIEW H JOIN TBL_REPORT_REG_STUDYREVIEW R
  ON R.POST_REPORT_CODE = H.POST_REPORT_CODE
    JOIN TBL_BOARD_STUDYREVIEW B
    ON B.POST_CODE = R.POST_CODE
      LEFT JOIN TBL_HANDLE_RESULT HR
      ON HR.HANDLE_RESULT_CODE = H.HANDLE_RESULT_CODE
        JOIN TBL_STUDY_PARTICIPANT P
        ON P.PARTI_CODE = B.PARTI_CODE
            JOIN TBL_STUDY_APPLY A
            ON A.APPLY_CODE = P.APPLY_CODE
UNION ALL
SELECT B.USER_CODE, B.STUDY_CODE, B.STUDY_NAME, HR.HANDLE_RESULT, H.ACCUSE_HANDLE_DATE
FROM TBL_STUDY_OPEN B JOIN TBL_STUDY_ACCUSE R
  ON B.STUDY_CODE = R.STUDY_CODE
    JOIN TBL_STUDY_ACCUSE_HANDLE H
    ON R.ACCUSE_CODE = H.ACCUSE_CODE
        LEFT JOIN TBL_HANDLE_RESULT HR
        ON HR.HANDLE_RESULT_CODE = H.HANDLE_RESULT_CODE;

select *
from RH_BOARDLIST_VIEW;

-- ○ Report_detailpage.jsp(각종 게시판 신고처리 상세페이지를 위한 뷰 - 게시물코드, 피신고자, 신고자, 신고일, 카테고리, 기타내용)
-- ○ 뷰 이름 : RH_REPORTLIST_VIEW
CREATE OR REPLACE VIEW RH_REPORTLIST_VIEW
AS
SELECT B.POST_CODE, B.USER_CODE REPORTED_USER_CODE, R.USER_CODE REPORT_USER_CODE, R.REPORT_DATE, C.POST_REPORT_CTG, R.REPORT_REASON
FROM TBL_REPORT_REG_INFORM R JOIN TBL_BOARD_INFORM B
        ON B.POST_CODE = R.POST_CODE
            JOIN TBL_POST_REPORT_CTG C
            ON C.POST_REPORT_CTG_CODE = R.POST_REPORT_CTG_CODE
UNION ALL
SELECT B.POST_CODE, B.USER_CODE REPORTED_USER_CODE, R.USER_CODE REPORT_USER_CODE, R.REPORT_DATE, C.POST_REPORT_CTG, R.REPORT_REASON
FROM TBL_REPORT_REG_INTERVIEW R JOIN TBL_BOARD_INTERVIEW B
        ON B.POST_CODE = R.POST_CODE
            JOIN TBL_POST_REPORT_CTG C
            ON C.POST_REPORT_CTG_CODE = R.POST_REPORT_CTG_CODE
UNION ALL
SELECT B.POST_CODE, B.USER_CODE REPORTED_USER_CODE, R.USER_CODE REPORT_USER_CODE, R.REPORT_DATE, C.POST_REPORT_CTG, R.REPORT_REASON
FROM TBL_REPORT_REG_SEMINAR R JOIN TBL_BOARD_SEMINAR B
        ON B.POST_CODE = R.POST_CODE
            JOIN TBL_POST_REPORT_CTG C
            ON C.POST_REPORT_CTG_CODE = R.POST_REPORT_CTG_CODE
UNION ALL
SELECT B.POST_CODE, B.USER_CODE REPORTED_USER_CODE, R.USER_CODE REPORT_USER_CODE, R.REPORT_DATE, C.POST_REPORT_CTG, R.REPORT_REASON
FROM TBL_REPORT_REG_FREE R JOIN TBL_BOARD_FREE B
        ON B.POST_CODE = R.POST_CODE
            JOIN TBL_POST_REPORT_CTG C
            ON C.POST_REPORT_CTG_CODE = R.POST_REPORT_CTG_CODE
UNION ALL
SELECT B.POST_CODE, B.USER_CODE REPORTED_USER_CODE, R.USER_CODE REPORT_USER_CODE, R.REPORT_DATE, C.POST_REPORT_CTG, R.REPORT_REASON
FROM TBL_REPORT_REG_QUESTION R JOIN TBL_BOARD_QUESTION B
        ON B.POST_CODE = R.POST_CODE
            JOIN TBL_POST_REPORT_CTG C
            ON C.POST_REPORT_CTG_CODE = R.POST_REPORT_CTG_CODE
UNION ALL
SELECT B.POST_CODE, B.USER_CODE REPORTED_USER_CODE, R.USER_CODE REPORT_USER_CODE, R.REPORT_DATE, C.POST_REPORT_CTG, R.REPORT_REASON
FROM TBL_REPORT_REG_ANSWER R JOIN TBL_BOARD_ANSWER B
        ON B.POST_CODE = R.POST_CODE
            JOIN TBL_POST_REPORT_CTG C
            ON C.POST_REPORT_CTG_CODE = R.POST_REPORT_CTG_CODE
UNION ALL
SELECT B.POST_CODE, A.USER_CODE REPORTED_USER_CODE, R.USER_CODE REPORT_USER_CODE, R.REPORT_DATE, C.POST_REPORT_CTG, R.REPORT_REASON
FROM TBL_REPORT_REG_STUDYREVIEW R JOIN TBL_BOARD_STUDYREVIEW B
        ON B.POST_CODE = R.POST_CODE
            JOIN TBL_POST_REPORT_CTG C
            ON C.POST_REPORT_CTG_CODE = R.POST_REPORT_CTG_CODE            
                JOIN TBL_STUDY_PARTICIPANT P
                ON P.PARTI_CODE = B.PARTI_CODE
                    JOIN TBL_STUDY_APPLY A
                    ON A.APPLY_CODE = P.APPLY_CODE;


-- ○ 뷰 이름 : RH_STUDYMEM_VIEW
CREATE OR REPLACE VIEW RH_STUDYMEM_VIEW
AS
SELECT O.STUDY_NAME, A.USER_CODE REPORT_USER_CODE, A2.USER_CODE REPORTED_USER_CODE, O.START_DATE 
FROM TBL_MEM_REPORT_HANDLE H JOIN TBL_MEM_REPORT_REG R
  ON H.MEM_REPORT_REG_CODE = R.MEM_REPORT_REG_CODE
    JOIN TBL_STUDY_PARTICIPANT P
    ON P.PARTI_CODE = R.PARTI_REPORT_CODE
        JOIN TBL_STUDY_PARTICIPANT P2
        ON P2.PARTI_CODE = R.PARTI_REPORTED_CODE
            JOIN TBL_STUDY_APPLY A
            ON A.APPLY_CODE = P.APPLY_CODE
                JOIN TBL_STUDY_APPLY A2
                ON P2.APPLY_CODE = A2.APPLY_CODE
                    JOIN TBL_STUDY_OPEN O
                    ON O.STUDY_CODE = A.STUDY_CODE;
        
      

-- ○ Study_report_list.jsp(스터디 신고처리를 위한 뷰 - 개설자, 스터디이름, 내용, 신고처리결과, 신고처리날짜)
-- ○ 뷰 이름 : RH_STUDY_VIEW
CREATE OR REPLACE VIEW RH_STUDY_VIEW
AS
SELECT O.USER_CODE USER_CODE, O.WRITE_DATE, O.STUDY_NAME, O.STUDY_DESC, HR.HANDLE_RESULT, H.ACCUSE_HANDLE_DATE
    , A.ACCUSE_REASON, C.POST_REPORT_CTG
FROM TBL_STUDY_ACCUSE_HANDLE H JOIN TBL_STUDY_ACCUSE A
  ON H.ACCUSE_CODE = H.ACCUSE_CODE
    JOIN TBL_STUDY_OPEN O
    ON A.STUDY_CODE = O.STUDY_CODE
        JOIN TBL_HANDLE_RESULT HR
        ON HR.HANDLE_RESULT_CODE = H.HANDLE_RESULT_CODE
            JOIN TBL_POST_REPORT_CTG C
            ON C.POST_REPORT_CTG_CODE = A.POST_REPORT_CTG_CODE;

          
-- ○ 계정정지 등록 프로시저를 위한 뷰
-- ○ 뷰 이름 : INSERT_SUSPEND_VIEW
CREATE OR REPLACE VIEW INSERT_SUSPEND_VIEW
AS
SELECT A.USER_CODE, A.APPLY_CODE, C.CANCEL_CODE, O.END_DATE
FROM TBL_STUDY_APPLY A LEFT JOIN TBL_STUDY_CANCEL C
  ON A.APPLY_CODE = C.APPLY_CODE    
    JOIN TBL_STUDY_OPEN O
    ON A.STUDY_CODE = O.STUDY_CODE
WHERE END_DATE > SYSDATE;
--==>> View INSERT_SUSPEND_VIEW이(가) 생성되었습니다.


-- ○ 스터디 취소 등록 프로시저에서 사용하는 뷰
-- ○ 뷰 이름 : STUDY_CANCEL_VIEW
CREATE OR REPLACE VIEW STUDY_CANCEL_VIEW
AS
SELECT O.STUDY_CODE 스터디코드, A.APPLY_CODE 참가코드, A.USER_CODE 참여자, C.CANCEL_CODE 취소코드, C.CANCEL_DATE 취소날짜, C.AUTO_CANCEL 자동취소여부, P.POSITION_CODE 직책, O.USER_CODE AS 개설자 
     , O.START_DATE 시작일, O.END_DATE 종료일, M.MEMNUM AS 최소인원, O.WRITE_DATE 작성일
FROM TBL_STUDY_APPLY A JOIN TBL_STUDY_OPEN O
    ON A.STUDY_CODE = O.STUDY_CODE
        JOIN TBL_MEMNUM M
        ON M.MEMNUM_CODE = O.MIN_MEM_CODE
            LEFT JOIN TBL_STUDY_CANCEL C
            ON C.APPLY_CODE = A.APPLY_CODE
                JOIN TBL_MEMNUM M2
                ON M2.MEMNUM_CODE = O.MAX_MEM_CODE
                    JOIN TBL_STUDY_POSITION P
                    ON A.POSITION_CODE = P.POSITION_CODE;
--==>> View STUDY_CANCEL_VIEW이(가) 생성되었습니다.
