/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2020-12-27 08:55:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class FreeBoard_005fwrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	request.setCharacterEncoding("UTF-8");
String cp = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>FreeBoard_write.jsp</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(cp);
      out.write("/js/util.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\tfunction sendIt()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//alert(\"호출\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tf = document.myForm;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 제목 입력 확인 -------------------------------------\r\n");
      out.write("\t\tstr = f.subject.value;\r\n");
      out.write("\t\tstr = str.trim();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// ※ javascript 에는 trim() 이 존재하지 않음.\r\n");
      out.write("\t\t//    외부에서 참조한 util.js 에 만들어두었음.\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 테스트\r\n");
      out.write("\t\t//alert(\"|\" + str + \"|\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!str)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"\\n제목을 입력하세요~!!!\");\r\n");
      out.write("\t\t\tf.subject.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// ------------------------------------- 제목 입력 확인\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 패스워드 입력 확인 -------------------------------------\r\n");
      out.write("\t\tstr = f.pwd.value;\r\n");
      out.write("\t\tstr = str.trim();\r\n");
      out.write("\t\tif(!str)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"\\n패스워드를 입력하세요~!!!\");\r\n");
      out.write("\t\t\tf.pwd.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t// ------------------------------------- 패스워드 입력 확인 \r\n");
      out.write("\t\r\n");
      out.write("\t\tf.action = \"");
      out.print(cp);
      out.write("/Create_ok.jsp\";\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(cp);
      out.write("/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(cp);
      out.write("/css/create.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#BoardType {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tpadding-left: 20px;\r\n");
      out.write("\tpadding-top: 100px;\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("\tmargin: 30px auto;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#BoardType a {\r\n");
      out.write("\tfont-size: 10pt;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#BoardType li {\r\n");
      out.write("\tfont-size: 10pt;\r\n");
      out.write("\tborder-bottom: 1px solid;\r\n");
      out.write("\tpadding-top: 10px;\r\n");
      out.write("\tpadding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("#BoardBottom{\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("}\r\n");
      out.write("a {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tcolor: #000000;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tfont-size: 9pt;\r\n");
      out.write("\tline-height: 150%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover, a:active {\r\n");
      out.write("\tfont-size: 9pt;\r\n");
      out.write("\tcolor: #8000ff;\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul {\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("}\r\n");
      out.write("#bbs_title\r\n");
      out.write("{\r\n");
      out.write("\twidth: 574px;\r\n");
      out.write("\tpadding-left: 20px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tborder: 3px solid black;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tline-height: 40px;\r\n");
      out.write("\tfont-size: 10pt;\r\n");
      out.write("\tmargin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<table id=\"bbs\" style=\"width: 100%; height: 100%\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div id=\"BoardType\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a>세미나 및 공모전</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a>IT기술정보공유</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a>Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a>자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a>면접/코딩테스트 후기</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a>스터디 후기</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- #BoardType -->\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t<div id=\"BoardMenu\">\r\n");
      out.write("\t\t\t\t\t<a>홈</a> > <a>정보공유게시판</a> > <a>자유게시판</a> > <a>글 작성페이지</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"bbs_title\">자 유 게 시 판</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"\" method=\"post\" name=\"myForm\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"bbsCreated\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bbsCreated_bottomLine\">\r\n");
      out.write("\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t<dt>제&nbsp;&nbsp;&nbsp;&nbsp;목</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"subject\" size=\"74\" maxlength=\"100\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"boxTF\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- bbsCreated_bottomLine -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div id=\"bbsCreated_content\">\r\n");
      out.write("\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t<dt>내&nbsp;&nbsp;&nbsp;&nbsp;용</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea rows=\"12\" cols=\"63\" name=\"content\" class=\"boxTA\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- #bbsCreated_content -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div id=\"bbsCreated_footer\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"게시물등록\" class=\"btn2\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"sendIt()\"> <input type=\"reset\" value=\"전체삭제\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn2\" onclick=\"document.myForm.subject.focus()\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"작성취소\" class=\"btn2\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"javascript:location.href='");
      out.print(cp);
      out.write("/List.jsp'\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- #bbsCreated_footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- #bbsCreated -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t<td id=\"BoardBottom\">\r\n");
      out.write("\t\t\t\t개인정보이용약관 | 고객센터전화번호:070-8435-6825 | 오시는길 : 서울시 마포구 가마산로 18길\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<!-- #bbs -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
