
--○ 직책테이블, UK 추가
ALTER TABLE TBL_STUDY_POSITION
ADD CONSTRAINT STUDY_POSITION_P_UK UNIQUE (POSITION);

--○ 스터디평가테이블, CK 추가
ALTER TABLE TBL_STUDY_ASSESS
ADD CONSTRAINT STUDY_ASSESS_S_CK CHECK (SCORE>=0 AND SCORE <=5);

--○ 출석부 테이블, CK 추가
ALTER TABLE TBL_STUDY_ATTEND
ADD CONSTRAINT STUDY_ATTEND_CO_CK CHECK (CLOCK_OUT > CLOCK_IN);

--○ 외출등록 테이블, CK 추가
ALTER TABLE TBL_STUDY_STEPOUT
ADD CONSTRAINT STUDY_STOT_CO_CK CHECK (CLOCK_OUT > CLOCK_IN);

--○ 평가점수 테이블, UK 및 CK 추가
ALTER TABLE TBL_STUDY_ASSESS_RESP
ADD (CONSTRAINT STUDY_ASSRP_R_UK UNIQUE (RESP)
, CONSTRAINT STUDY_ASSRP_S_UK UNIQUE (SCORE)
, CONSTRAINT STUDY_ASSRP_S_CK CHECK (SCORE >= 0 AND SCORE <= 100)
);

--○ 평가항목 테이블, UK 추가
ALTER TABLE TBL_STUDY_ASSESS_ITEM
ADD CONSTRAINT STUDY_ASSITM_I_UK UNIQUE (ITEM);





