--○ 테이블명, CK/UK 추가
--예시)
ALTER TABLE TBL_어쩌구
ADD( CONSTRAINT 어쩌구_컬럼_CK CHECK (컬럼명 > 100 AND 컬럼명 < 200)
   , CONSTRAINT 어쩌구_컬럼_UK UNIQUE (컬럼명)
);

--○ 회원 등록 테이블 CK,UK추가
ALTER TABLE TBL_USER_REGISTER
ADD( CONSTRAINT USER_REG_ID_UK UNIQUE(ID)
    ,CONSTRAINT USER_REG_SSN_CK CHECK(LENGTH(SSN)=13)
    ,CONSTRAINT USER_REG_SSN_UK UNIQUE(SSN)
    ,CONSTRAINT USER_REG_EMAIL_UK UNIQUE(EMAIL)
    ,CONSTRAINT USER_REG_NAME_CK CHECK(LENGTH(NAME)>=2)
);


--○ 비밀번호 찾기 질문 데이블 UK추가
ALTER TABLE TBL_PW_SEARCH_QUE
ADD( CONSTRAINT PW_SRCH_QUE_PWQ_UK UNIQUE(PW_SRCH_QUE)
);


--○ 현재 직업 대분류 테이블 UK추가
ALTER TABLE TBL_JOB_LC
ADD(CONSTRAINT JOB_LC_JL_UK UNIQUE(JOB_LC)
);


--○ 현재 직업 중분류 테이블 UK추가
ALTER TABLE TBL_JOB_MC
ADD(CONSTRAINT JOB_MC_JM_UK UNIQUE(JOB_MC)
);


--○ 탈퇴 기록 및 개인정보 보관 테이블 CK,UK추가
ALTER TABLE TBL_WITHDRAWAL_INFO
ADD(CONSTRAINT WDL_INFO_SSN_CK CHECK(LENGTH(SSN)=13)
    ,CONSTRAINT WDL_INFO_SSN_UK UNIQUE(SSN) 
);

--○ 탈퇴 카테고리 테이블
ALTER TABLE TBL_WITHDRAWAL_CATEGORY
ADD(CONSTRAINT WDL_CTG_WDL_CTG_UK UNIQUE(WDL_CTG)
);


--○ 제약조건 추가한 사항
--   숫자만 입력했는지 확인

-- 회원 등록 테이블
ALTER TABLE TBL_USER_REGISTER
ADD(CONSTRAINT USER_REG_SSN_CK2 CHECK(REGEXP_INSTR(SSN,'[^0-9]') = 0));

-- 탈퇴 기록 및 개인정보 보관 테이블
ALTER TABLE TBL_WITHDRAWAL_INFO
ADD(CONSTRAINT WDL_INFO_SSN_CK2 CHECK(REGEXP_INSTR(SSN,'[^0-9]') = 0));
