
--○ 직책테이블, UK 추가
ALTER TABLE TBL_STUDY_POSITION
ADD CONSTRAINT STUDY_POSITION_P_UK UNIQUE (POSITION);

--○ 스터디평가테이블, CK 추가
ALTER TABLE TBL_STUDY_ASSESS
ADD CONSTRAINT STUDY_ASSESS_S_CK CHECK (SCORE>=0 AND SCORE <=5);

--○ 출석부 테이블, CK 추가
ALTER TABLE TBL_STUDY_ATTEND
ADD CONSTRAINT STUDY_ATTEND_CO_CK CHECK (CLOCK_OUT > CLOCK_IN);

--○ 외출등록 테이블, CK 추가
ALTER TABLE TBL_STUDY_STEPOUT
ADD CONSTRAINT STUDY_STOT_CO_CK CHECK (CLOCK_OUT > CLOCK_IN);

--○ 평가점수 테이블, UK 및 CK 추가
ALTER TABLE TBL_STUDY_ASSESS_RESP
ADD (CONSTRAINT STUDY_ASSRP_R_UK UNIQUE (RESP)
, CONSTRAINT STUDY_ASSRP_S_UK UNIQUE (SCORE)
, CONSTRAINT STUDY_ASSRP_S_CK CHECK (SCORE >= 0 AND SCORE <= 100)
);

--○ 평가항목 테이블, UK 추가
ALTER TABLE TBL_STUDY_ASSESS_ITEM
ADD CONSTRAINT STUDY_ASSITM_I_UK UNIQUE (ITEM);

--○ 테이블명, CK/UK 추가
--예시)
ALTER TABLE TBL_어쩌구
ADD( CONSTRAINT 어쩌구_컬럼_CK CHECK (컬럼명 > 100 AND 컬럼명 < 200)
   , CONSTRAINT 어쩌구_컬럼_UK UNIQUE (컬럼명)
);

--○ 회원 등록 테이블 CK,UK추가
ALTER TABLE TBL_USER_REGISTER
ADD( CONSTRAINT USER_REG_ID_UK UNIQUE(ID)
    ,CONSTRAINT USER_REG_SSN_CK CHECK(LENGTH(SSN)=13)
    ,CONSTRAINT USER_REG_SSN_UK UNIQUE(SSN)
    ,CONSTRAINT USER_REG_EMAIL_UK UNIQUE(EMAIL)
    ,CONSTRAINT USER_REG_NAME_CK CHECK(LENGTH(NAME)>=2)
);

--○ 비밀번호 찾기 질문 데이블 UK추가
ALTER TABLE TBL_PW_SEARCH_QUE
ADD( CONSTRAINT PW_SRCH_QUE_PWQ_UK UNIQUE(PW_SRCH_QUE)
);


--○ 현재 직업 대분류 테이블 UK추가
ALTER TABLE TBL_JOB_LC
ADD(CONSTRAINT JOB_LC_JL_UK UNIQUE(JOB_LC)
);


--○ 현재 직업 중분류 테이블 UK추가
ALTER TABLE TBL_JOB_MC
ADD(CONSTRAINT JOB_MC_JM_UK UNIQUE(JOB_MC)
);


--○ 탈퇴 기록 및 개인정보 보관 테이블 CK,UK추가
ALTER TABLE TBL_WITHDRAWAL_INFO
ADD(CONSTRAINT WDL_INFO_SSN_CK CHECK(LENGTH(SSN)=13)
    ,CONSTRAINT WDL_INFO_SSN_UK UNIQUE(SSN) 
);

--○ 탈퇴 카테고리 테이블
ALTER TABLE TBL_WITHDRAWAL_CATEGORY
ADD(CONSTRAINT WDL_CTG_WDL_CTG_UK UNIQUE(WDL_CTG)
);



-- 모임 요일 테이블 CK 제약 조건
ALTER TABLE TBL_STUDY_MEETDAY
ADD ( CONSTRAINT STD_MEETDAY_ST_CK CHECK(START_TIME BETWEEN 0 AND 24)
    , CONSTRAINT STD_MEETDAY_ET_CK CHECK(END_TIME BETWEEN 0 AND 24 AND END_TIME BETWEEN START_TIME+1 AND START_TIME+12));

-- 요일 테이블 UK 제약 조건
ALTER TABLE TBL_WEEKDAY
ADD ( CONSTRAINT WEEKDAY_WD_UK UNIQUE(WEEKDAY));

-- 인원수 테이블 CK, UK 제약 조건
ALTER TABLE TBL_MEMNUM
ADD ( CONSTRAINT MEMNUM_MN_CK CHECK(MEMNUM >=3 AND MEMNUM <=8 ));

ALTER TABLE TBL_MEMNUM
ADD ( CONSTRAINT MEMNUM_MN_UK UNIQUE(MEMNUM));


-- 등급 테이블 CK, UK 제약 조건
ALTER TABLE TBL_USER_RANK
ADD ( CONSTRAINT USER_RANK_RK_CK CHECK(RANK >=6 AND RANK<=1)
    , CONSTRAINT USER_RANK_MNS_CK CHECK(MIN_SCORE >= -4200)
    , CONSTRAINT USER_RANK_MXS_CK CHECK(MAX_SCORE <= 21600 AND MAX_SCORE > MIN_SCORE));

ALTER TABLE TBL_USER_RANK
ADD ( CONSTRAINT USER_RANK_RK_UK UNIQUE(RANK)
    , CONSTRAINT USER_RANK_MNS_UK UNIQUE(MIN_SCORE)
    , CONSTRAINT USER_RANK_MXS_UK UNIQUE(MAX_SCORE));

-- 스터디 유형 테이블 UK 제약 조건
ALTER TABLE TBL_STUDY_TYPE
ADD (CONSTRAINT STD_TYPE_ST_UK UNIQUE(STUDY_TYPE));

-- 관심분야 대분류 테이블 UK 제약 조건
ALTER TABLE TBL_INTEREST_LC
ADD (CONSTRAINT INTER_LC_IL_UK UNIQUE(INTEREST_LC));

-- 관심분야 중분류 테이블 UK 제약 조건
ALTER TABLE TBL_INTEREST_MC
ADD (CONSTRAINT INTER_MC_IM_UK UNIQUE(INTEREST_MC));

-- 지역 대분류 테이블 UK 제약 조건
ALTER TABLE TBL_LOC_LC
ADD ( CONSTRAINT LOC_LC_UK UNIQUE(LOC_LC));

-- 지역 중분류 테이블 UK 제약 조건
ALTER TABLE TBL_LOC_MC
ADD ( CONSTRAINT LOC_MC_UK UNIQUE(LOC_MC));

-- 스터디 개설 테이블 체크 제약조건 
ALTER TABLE TBL_STUDY_OPEN
ADD (CONSTRAINT STD_OPEN_SD_CK CHECK (START_DATE >= WRITE_DATE+10 AND START_DATE <= WRITE_DATE+15));

ALTER TABLE TBL_STUDY_OPEN
ADD ( CONSTRAINT STD_OPEN_ED_CK CHECK (END_DATE <= START_DATE+365));

--○ 욕설 테이블 UK 추가
ALTER TABLE TBL_CURSE
ADD CONSTRAINT CURSE_CK_UK UNIQUE (CURSE_KIND);
--==>> 실행 된 상태



