--스터디 신청 테이블
CREATE TABLE TBL_STUDY_APPLY
( APPLY_CODE    VARCHAR2(15)
, STUDY_CODE    VARCHAR2(15)                 NOT NULL
, USER_CODE     VARCHAR2(10)                 NOT NULL
, APPLY_DATE    DATE         DEFAULT SYSDATE NOT NULL
, CONSTRAINT STUDY_APPLY_AC_PK PRIMARY KEY (APPLY_CODE)
, CONSTRAINT STUDY_APPLY_SC_FK FOREIGN KEY (STUDY_CODE)
  REFERENCES TBL_STUDY_OPEN (STUDY_CODE)
, CONSTRAINT STUDY_APPLY_UC_FK FOREIGN KEY (USER_CODE)
  REFERENCES TBL_USER_CODE_CREATE (USER_CODE)
);

-- 스터디 취소 처리 테이블
CREATE TABLE TBL_STUDY_CANCEL
( CANCEL_CODE   VARCHAR2(15)
, APPLY_CODE    VARCHAR2(15)                 NOT NULL
, CANCEL_DATE   DATE         DEFAULT SYSDATE NOT NULL
, CONSTRAINT STUDY_CANCEL_CC_PK PRIMARY KEY (CANCEL_CODE)
, CONSTRAINT STUDY_CANCEL_AC_FK FOREIGN KEY (APPLY_CODE)
  REFERENCES TBL_STUDY_APPLY (APPLY_CODE)
);

-- 스터디 참가 테이블
CREATE TABLE TBL_STUDY_PARTICIPANT
( PARTI_CODE    VARCHAR2(15)
, APPLY_CODE    VARCHAR2(15)    NOT NULL
, POSITION_CODE VARCHAR2(5)     NOT NULL
, CONSTRAINT STUDY_PARTI_PC_PK PRIMARY KEY (PARTI_CODE)
, CONSTRAINT STUDY_PARTI_AC_FK FOREIGN KEY (APPLY_CODE)
  REFERENCES TBL_STUDY_APPLY (APPLY_CODE)
, CONSTRAINT STUDY_PARTI_PC_FK FOREIGN KEY (POSITION_CODE)
  REFERENCES TBL_STUDY_POSITION (POSITION_CODE)
);

-- 직책 테이블
CREATE TABLE TBL_STUDY_POSITION
( POSITION_CODE VARCHAR2(5)
, POSITION      VARCHAR2(20) NOT NULL
, CONSTRAINT STUDY_POSITION_PC_PK PRIMARY KEY (POSITION_CODE)
);

-- 스터디 컨텐츠 테이블
CREATE TABLE TBL_STUDY_CONTENT
( CONTENT_CODE  VARCHAR2(15)
, PARTI_CODE    VARCHAR2(15)                 NOT NULL
, WRITE_DATE    DATE         DEFAULT SYSDATE NOT NULL
, HITCOUNT      NUMBER       DEFAULT 0       NOT NULL
, TITLE         VARCHAR2(100)                NOT NULL
, CONTENT       VARCHAR2(4000)               NOT NULL
, CONSTRAINT STUDY_CONTENT_CC_PK PRIMARY KEY (CONTENT_CODE)
, CONSTRAINT STUDY_CONTENT_PC_FK FOREIGN KEY (PARTI_CODE)
  REFERENCES TBL_STUDY_PARTICIPANT (PARTI_CODE)
);

-- 스터디 평가 테이블
CREATE TABLE TBL_STUDY_ASSESS
( ASSESS_CODE   VARCHAR2(15)                 NOT NULL
, PARTI_CODE    VARCHAR2(15)                 NOT NULL
, SCORE         NUMBER                       NOT NULL
, ASSESS_DATE   DATE         DEFAULT SYSDATE NOT NULL
, CONSTRAINT STUDY_ASSESS_AC_PK PRIMARY KEY (ASSESS_CODE)
, CONSTRAINT STUDY_ASSESS_PC_FK FOREIGN KEY (PARTI_CODE)
  REFERENCES TBL_STUDY_PARTICIPANT (PARTI_CODE)
);

-- 출석부 테이블
CREATE TABLE TBL_STUDY_ATTEND
( ATTEND_CODE   VARCHAR2(15)
, PARTI_CODE    VARCHAR2(15)                 NOT NULL
, ATTEND_DATE   DATE         DEFAULT SYSDATE NOT NULL
, CLOCK_IN      TIMESTAMP    DEFAULT SYSDATE NOT NULL
, CLOCK_OUT     TIMESTAMP 
, CONSTRAINT STUDY_ATTEND_AC_PK PRIMARY KEY (ATTEND_CODE)
, CONSTRAINT STUDY_ASSESS_PC_FK FOREIGN KEY (PARTI_CODE)
  REFERENCES TBL_STUDY_PARTICIPANT (PARTI_CODE)
);

-- 일정관리 테이블
CREATE TABLE TBL_STUDY_SCHEDULE
( ATTEND_CODE   VARCHAR2(15)
, SCHEDULE      VARCHAR2(1200)
, CONSTRAINT SCHEDULE_AC_PK PRIMARY KEY (ATTEND_CODE)
, CONSTRAINT SCHEDULE_AC_FK FOREIGN KEY (ATTEND_CODE)
  REFERENCES TBL_STUDY_ATTEND (ATTEND_CODE)
);

-- 외출 등록 테이블
CREATE TABLE TBL_STUDY_STEPOUT
( ATTEND_CODE   VARCHAR2(15)
, CLOCK_IN      TIMESTAMP   DEFAULT SYSDATE NOT NULL
, CLOCK_OUT     TIMESTAMP 
, CONSTRAINT STUDY_STEPOUT_AC_PK PRIMARY KEY (ATTEND_CODE)
, CONSTRAINT STUDY_STEPOUT_AC_FK FOREIGN KEY (ATTEND_CODE)
  REFERENCES TBL_STUDY_ATTEND (ATTEND_CODE)
);

-- 스터디원 평가 등록 테이블
CREATE TABLE TBL_STUDY_INTERASSESS
( INTERASSESS_CODE  VARCHAR2(15)                
, PARTI_CODE        VARCHAR2(15)                 NOT NULL
, RESP_CODE         VARCHAR2(5)                  NOT NULL
, ITEM_CODE         VARCHAR2(5)                  NOT NULL
, PARTI_CODE        VARCHAR2(15)                 NOT NULL
, INTERASSESS_DATE  DATE         DEFAULT SYSDATE NOT NULL
, CONSTRAINT STUDY_ITASS_PK PRIMARY KEY (INTERASSESS_CODE)
, CONSTRAINT STUDY_ITASS_FK FOREIGN KEY (PARTI_CODE)
  REFERENCES TBL_STUDY_PARTICIPANT (PARTI_CODE)
, CONSTRAINT STUDY_ITASS_FK FOREIGN KEY (RESP_CODE)
  REFERENCES TBL_STUDY_ASSESS_RESP (RESP_CODE)
, CONSTRAINT STUDY_ITASS_FK FOREIGN KEY (ITEM_CODE)
  REFERENCES TBL_STUDY_ASSESS_ITEM (ITEM_CODE)
, CONSTRAINT STUDY_ITASS_FK FOREIGN KEY (PARTI_CODE)
  REFERENCES TBL_STUDY_PARTICIPANT (PARTI_CODE)
);

-- 평가 점수 테이블
CREATE TABLE TBL_STUDY_ASSESS_RESP
( RESP_CODE VARCHAR2(5)
, RESP      VARCHAR2(40)    NOT NULL
, SCORE     NUMBER(3)       NOT NULL
, CONSTRAINT STUDY_ASS_RESP_RC_PK PRIMARY KEY (RESP_CODE)
);

-- 평가 항목 테이블
CREATE TABLE TBL_STUDY_ASSESS_ITEM
( ITEM_CODE VARCHAR2(5) 
, ITEM      VARCHAR2(100)   NOT NULL
, CONSTRAINT STUDY_ASS_ITEM_IC_PK PRIMARY KEY (ITEM_CODE)
);

-- 점수 기록 테이블
CREATE TABLE TBL_SCORE
( SCORE_CODE    VARCHAR2(15)
, USER_CODE     VARCHAR2(10)                NOT NULL
, SCORE         NUMBER                      NOT NULL
, SCORE_DATE    DATE        DEFAULT SYSDATE NOT NULL
, CONSTRAINT SCORE_SC_PK PRIMARY KEY (SCORE_CODE)
, CONSTRAINT SCORE_UC_FK FOREIGN KEY (USER_CODE)
  REFERENCES TBL_USER_CODE_CREATE (USER_CODE)
);

-- 경고 등록 테이블
CREATE TABLE TBL_WARNING
( WARNING_CODE  VARCHAR2(15)
, WARNING_DATE  VARCHAR2(1200)  NOT NULL
, USER_CODE     VARCHAR2(10)    NOT NULL
, CONSTRAINT WARN_WC_PK PRIMARY KEY (WARNING_CODE)
, CONSTRAINT WARN_UC_FK FOREIGN KEY (USER_CODE)
  REFERENCES TBL_USER_CODE_CREATE (USER_CODE)
);

 