--■■■ 변경사항 ■■■--

-- 테이블 이름으로 제약조건 조회
SELECT *
FROM ALL_CONSTRAINTS
WHERE OWNER = 'STITKER' AND TABLE_NAME = 'TBL_STUDY_APPLY'
ORDER BY TABLE_NAME;

-- 휴지통 비우기
PURGE RECYCLEBIN;


-- 외출 테이블 삭제(기능 삭제함.)
DROP TABLE TBL_STUDY_STEPOUT;

-- 스터디 출석 시간 NOT NULL 제약조건 삭제.
-- 스터디 출석테이블에 종료날짜까지의 모든 회차 일단 다 인서트하기로 함.
ALTER TABLE TBL_STUDY_ATTEND DROP CONSTRAINT SYS_C008005;

-- 스터디 신청 날짜.
-- 스터디 확인 버튼 눌렸는지 안눌렸는지 확인하기 위함.
ALTER TABLE TBL_STUDY_APPLY DROP CONSTRAINT SYS_C007764;


-- 스터디 진행에서 직책 컬럼 삭제
ALTER TABLE TBL_STUDY_PARTICIPANT DROP COLUMN POSITION_CODE;

-- 스터디 참가에서 직책 컬럼 추가
ALTER TABLE TBL_STUDY_APPLY ADD (
    POSITION_CODE VARCHAR(5) NOT NULL
  , CONSTRAINT STUDY_APPLY_PC_FK FOREIGN KEY (POSITION_CODE)
            REFERENCES TBL_STUDY_POSITION (POSITION_CODE)
);

-- 등급 테이블 체크 제약조건 수정
ALTER TABLE TBL_USER_RANK
ADD ( CONSTRAINT USER_RANK_RK_CK CHECK(RANK BETWEEN 1 AND 6));

-- 탈퇴 카테고리 항목 컬럼길이 수정(50 -> 150)
ALTER TABLE TBL_WITHDRAWAL_CATEGORY MODIFY(WDL_CTG VARCHAR2(150));

-- 등급 테이블 체크 제약조건 수정
ALTER TABLE TBL_USER_RANK
ADD ( CONSTRAINT USER_RANK_RK_CK CHECK(RANK BETWEEN 1 AND 6)
    , CONSTRAINT USER_RANK_MNS_CK CHECK(MIN_SCORE >= 0)
    , CONSTRAINT USER_RANK_MXS_CK CHECK(MAX_SCORE <= 18600 AND MAX_SCORE > MIN_SCORE));

-- 인원수 테이블 체크 제약조건 수정 
ALTER TABLE TBL_MEMNUM
ADD ( CONSTRAINT MEMNUM_CK CHECK(MEMNUM BETWEEN 3 AND 8));

-- 스터디원 신고카테고리 테이블의 카테고리 칼럼 데이터타입 변경(늘림)
ALTER TABLE TBL_MEM_REPORT_CTG MODIFY MEM_REPORT_CTG VARCHAR2(50);

-- 스터디원 신고카테고리 테이블의 기본키 칼럼 데이터타입 변경(늘림)
ALTER TABLE TBL_MEM_REPORT_CTG MODIFY MEM_REPORT_CTG_CODE VARCHAR2(5);

-- 스터디원 처리결과 테이블 기본키 칼럼 데이터타입 변경(늘림)
ALTER TABLE TBL_MEM_REPORT_HANDLE_RESULT MODIFY MEM_REPORT_HANDLE_RESULT_CODE VARCHAR2(5);

-- 세미나 및 공모전 테이블 모집시작일, 모집마감일 컬럼 추가
ALTER TABLE TBL_BOARD_SEMINAR ADD START_DATE DATE NOT NULL;
ALTER TABLE TBL_BOARD_SEMINAR ADD END_DATE DATE NOT NULL;

--스터디원 신고처리 테이블 칼럼 데이터타입 변경(늘림
ALTER TABLE TBL_MEM_REPORT_HANDLE MODIFY HANDLE_RESULT VARCHAR2(5);

-- Q&A 답변 게시판 Q&A질문게시물코드 추가
ALTER TABLE TBL_BOARD_ANSWER ADD (
    QPOST_CODE VARCHAR(15) 
  , CONSTRAINT BRD_AWR_QPC_FK FOREIGN KEY(QPOST_CODE)
            REFERENCES TBL_BOARD_QUESTION(POST_CODE)
);

--Q&A 답변 게시판 관심분야 중분류 코드 삭제
ALTER TABLE TBL_BOARD_ANSWER DROP COLUMN INTEREST_MC_CODE;

<<<<<<< HEAD
-- 스터디 취소 테이블 APPLY_CODE에 UK 제약조건 추가
ALTER TABLE TBL_STUDY_CANCEL
ADD ( CONSTRAINT STD_CANCEL_AC_UK UNIQUE(APPLY_CODE));

-- 스터디 신청 테이블 STUDY_CODE, USER_CODE에 복합 UK 제약조건 추가
ALTER TABLE TBL_STUDY_APPLY
ADD ( CONSTRAINT STUDY_APPLY_SC_UC_UK UNIQUE(STUDY_CODE, USER_CODE));
=======

<<<<<<< HEAD
-- 주민번호 컬럼 길이 변경 
ALTER TABLE TBL_USER_REGISTER MODIFY(SSN VARCHAR2(20));
--==>>Table TBL_USER_REGISTER이(가) 변경되었습니다.

ALTER TABLE TBL_WITHDRAWAL_INFO MODIFY(SSN VARCHAR2(20));
--==>>Table TBL_WITHDRAWAL_INFO이(가) 변경되었습니다.

COMMIT;
=======
-- 게시물 추천/비추천 테이블 : post_code, user_code 묶어서 uk 설정하기
ALTER TABLE TBL_REC_INFORM ADD UNIQUE(POST_CODE, USER_CODE);
ALTER TABLE TBL_REC_FREE ADD UNIQUE(POST_CODE, USER_CODE);
ALTER TABLE TBL_REC_INTERVIEW ADD UNIQUE(POST_CODE, USER_CODE);
ALTER TABLE TBL_REC_SEMINAR ADD UNIQUE(POST_CODE, USER_CODE);
ALTER TABLE TBL_REC_QUESTION ADD UNIQUE(POST_CODE, USER_CODE);
ALTER TABLE TBL_REC_ANSWER ADD UNIQUE(POST_CODE, USER_CODE);
ALTER TABLE TBL_REC_STUDYREVIEW ADD UNIQUE(POST_CODE, USER_CODE);
>>>>>>> b1308b342e4318300c1c1ef9d8f9df04373dde58


-- 신고, 내보내기 등록 제약조건 추가
ALTER TABLE TBL_STUDY_ACCUSE
ADD CONSTRAINT STUDY_ACCUSE_SCUC_UK UNIQUE (STUDY_CODE, USER_CODE);

ALTER TABLE TBL_MEM_REPORT_REG
ADD CONSTRAINT MEM_REP_REG_TCDC_UK UNIQUE (PARTI_REPORT_CODE, PARTI_REPORTED_CODE);

ALTER TABLE TBL_MEM_KICK_REG
ADD CONSTRAINT MEM_KICK_REG_KCDC_UK UNIQUE(PARTI_KICKED_CODE, PARTI_KICK_CODE);

ALTER TABLE TBL_REPORT_REG_INFORM
ADD CONSTRAINT RPT_REG_INFO_PCUC_UK UNIQUE(POST_CODE, USER_CODE);

ALTER TABLE TBL_REPORT_REG_INTERVIEW
ADD CONSTRAINT RPT_REG_INTER_PCUC_UK UNIQUE(POST_CODE, USER_CODE);

ALTER TABLE TBL_REPORT_REG_SEMINAR
ADD CONSTRAINT RPT_REG_SEMI_PCUC_UK UNIQUE(POST_CODE, USER_CODE);

ALTER TABLE TBL_REPORT_REG_FREE
ADD CONSTRAINT RPT_REG_FREE_PCUC_UK UNIQUE(POST_CODE, USER_CODE);

ALTER TABLE TBL_REPORT_REG_QUESTION
ADD CONSTRAINT RPT_REG_QUE_PCUC_UK UNIQUE(POST_CODE, USER_CODE);

ALTER TABLE TBL_REPORT_REG_ANSWER
ADD CONSTRAINT RPT_REG_AWR_PCUC_UK UNIQUE(POST_CODE, USER_CODE);

ALTER TABLE TBL_REPORT_REG_STUDYREVIEW
ADD CONSTRAINT RPT_REG_STRV_PCUC_UK UNIQUE(POST_CODE, USER_CODE);
>>>>>>> 59a6d0ea93311c56aa8fb872ac68d61b76a9fbcc




-- 게시판 리스트 출력 뷰 → 신고 5개 받은 게시물은 안보이게 변경----------------------------------------------------------------------
-- VIEW_BOARD_FREE 에서 USER_ID 컬럼도 나오게 수정

CREATE OR REPLACE VIEW VIEW_BOARD_FREE
AS
SELECT T.POST_NUM, T.POST_CODE, T.USER_CODE, T.WRITE_DATE, T.HITCOUNT, T.TITLE, T.CONTENT
     , T.REC, T.NOTREC, T.USER_NAME, T.USER_ID
FROM
(SELECT SUBSTR(BF.POST_CODE, 3) AS POST_NUM, BF.POST_CODE AS POST_CODE, BF.USER_CODE AS USER_CODE, TO_CHAR(BF.WRITE_DATE,'YYYY-MM-DD') AS WRITE_DATE
     , BF.HITCOUNT AS HITCOUNT, BF.TITLE AS TITLE, BF.CONTENT AS CONTENT
     , (SELECT NAME
        FROM TBL_USER_REGISTER
        WHERE USER_CODE = BF.USER_CODE) AS USER_NAME
     , (SELECT ID
        FROM TBL_USER_REGISTER
        WHERE USER_CODE = BF.USER_CODE) AS USER_ID
     , (SELECT COUNT(*)
        FROM TBL_REC_FREE
        WHERE REC_CHECK = 1 AND POST_CODE = BF.POST_CODE) AS REC
     , (SELECT COUNT(*)
         FROM TBL_REC_FREE
        WHERE REC_CHECK = 2 AND POST_CODE = BF.POST_CODE) AS NOTREC
     , (SELECT COUNT(*) REG_COUNT
        FROM TBL_REPORT_REG_INTERVIEW
        WHERE POST_CODE = BF.POST_CODE) AS REG_COUNT     
FROM TBL_BOARD_FREE BF
) T
WHERE T.REG_COUNT < 5;

--○ VIEW 생성(IT기술정보공유 게시판 리스트, 상세페이지 조회)
--   IT기술정보공유 테이블, 관심분야 중분류 카테고리 테이블
CREATE OR REPLACE VIEW VIEW_BOARD_INFORM
AS
SELECT T.POST_NUM, T.POST_CODE, T.USER_CODE, T.WRITE_DATE, T.HITCOUNT, T.TITLE, T.CONTENT
     , T.REC, T.NOTREC, T.INTEREST_MC, T.USER_NAME
FROM 
(SELECT (SUBSTR(BI.POST_CODE, 3)) AS POST_NUM, BI.POST_CODE AS POST_CODE, BI.USER_CODE AS USER_CODE
     , TO_CHAR(BI.WRITE_DATE,'YYYY-MM-DD') AS WRITE_DATE
     , BI.HITCOUNT AS HITCOUNT, BI.TITLE AS TITLE
     , (SELECT NAME
        FROM TBL_USER_REGISTER
        WHERE USER_CODE = BI.USER_CODE) AS USER_NAME
     , (SELECT COUNT(*)
        FROM TBL_REC_INFORM
        WHERE REC_CHECK = 1 AND POST_CODE = BI.POST_CODE) AS REC
     , (SELECT COUNT(*)
         FROM TBL_REC_INFORM
        WHERE REC_CHECK = 2 AND POST_CODE = BI.POST_CODE) AS NOTREC
     , BI.INTEREST_MC_CODE AS INTEREST_MC_CODE
     , (SELECT INTEREST_MC
        FROM TBL_INTEREST_MC
        WHERE INTEREST_MC_CODE = BI.INTEREST_MC_CODE) AS INTEREST_MC
     , BI.CONTENT "CONTENT"
     , (SELECT COUNT(*) REG_COUNT
        FROM TBL_REPORT_REG_INFORM
        WHERE POST_CODE = BI.POST_CODE) AS REG_COUNT
FROM TBL_BOARD_INFORM BI
) T
WHERE T.REG_COUNT < 5;

--○ VIEW 생성(면접/코딩테스트 게시판 리스트, 상사페이지 조회)
--   면접/코딩테스트 테이블, 관심분야 중분류 카테고리 테이블
CREATE OR REPLACE VIEW VIEW_BOARD_INTERVIEW
AS
SELECT T.POST_NUM, T.POST_CODE, T.USER_CODE, T.WRITE_DATE, T.HITCOUNT, T.TITLE, T.CONTENT
    , T.REC, T.NOTREC, T.INTEREST_MC, T.USER_NAME
FROM 
(SELECT SUBSTR(BV.POST_CODE, 3) AS POST_NUM, BV.POST_CODE AS POST_CODE, BV.USER_CODE AS USER_CODE
     , TO_CHAR(BV.WRITE_DATE,'YYYY-MM-DD') AS WRITE_DATE, BV.HITCOUNT AS HITCOUNT, BV.TITLE AS TITLE, BV.CONTENT AS CONTENT
     , (SELECT NAME
        FROM TBL_USER_REGISTER
        WHERE USER_CODE = BV.USER_CODE) AS USER_NAME
     , (SELECT COUNT(*)
        FROM TBL_REC_INTERVIEW
        WHERE REC_CHECK = 1 AND POST_CODE = BV.POST_CODE) AS REC
     , (SELECT COUNT(*)
         FROM TBL_REC_INTERVIEW
        WHERE REC_CHECK = 2 AND POST_CODE = BV.POST_CODE) AS NOTREC
     , BV.INTEREST_MC_CODE AS INTEREST_MC_CODE
     , (SELECT INTEREST_MC
        FROM TBL_INTEREST_MC
        WHERE INTEREST_MC_CODE = BV.INTEREST_MC_CODE) AS INTEREST_MC
     , (SELECT COUNT(*) REG_COUNT
        FROM TBL_REPORT_REG_INTERVIEW
        WHERE POST_CODE = BV.POST_CODE) AS REG_COUNT
FROM TBL_BOARD_INTERVIEW BV 
) T
WHERE T.REG_COUNT < 5;        

--○ VIEW 생성(세미나 및 공모전 게시판 리스트)
--   세미나 및 공모전 테이블, 세미나 말머리 테이블
CREATE OR REPLACE VIEW VIEW_BOARD_SEMINAR
AS
SELECT T.POST_NUM, T.POST_CODE, T.USER_CODE, T.WRITE_DATE, T.START_DATE, T.END_DATE, T.HITCOUNT, T.TITLE, T.CONTENT
     , T.REC, T.NOTREC, T.SEMINAR_CTG, T.USER_NAME, T.SEMINAR_CTG_CODE
FROM 
(SELECT SUBSTR(BS.POST_CODE, 3) AS POST_NUM, BS.POST_CODE AS POST_CODE, BS.USER_CODE AS USER_CODE
     , TO_CHAR(BS.WRITE_DATE,'YYYY-MM-DD') AS WRITE_DATE, TO_CHAR(BS.START_DATE,'YYYY-MM-DD') AS START_DATE
     , TO_CHAR(BS.END_DATE,'YYYY-MM-DD') AS END_DATE
     , BS.HITCOUNT AS HITCOUNT, BS.TITLE AS TITLE, BS.CONTENT AS CONTENT
     , (SELECT NAME
        FROM TBL_USER_REGISTER
        WHERE USER_CODE = BS.USER_CODE) AS USER_NAME
     , (SELECT COUNT(*)
        FROM TBL_REC_SEMINAR
        WHERE REC_CHECK = 1 AND POST_CODE = BS.POST_CODE) AS REC
     , (SELECT COUNT(*)
         FROM TBL_REC_SEMINAR
        WHERE REC_CHECK = 2 AND POST_CODE = BS.POST_CODE) AS NOTREC
     , BS.SEMINAR_CATEGORY_CODE AS SEMINAR_CTG_CODE
     , (SELECT SEMINAR_CATEGORY
        FROM TBL_SEMINAR_CATEGORY
        WHERE SEMINAR_CATEGORY_CODE = BS.SEMINAR_CATEGORY_CODE) AS SEMINAR_CTG
     , (SELECT COUNT(*) REG_COUNT
        FROM TBL_REPORT_REG_SEMINAR
        WHERE POST_CODE = BS.POST_CODE) AS REG_COUNT
FROM TBL_BOARD_SEMINAR BS 
) T
WHERE T.REG_COUNT < 5;   
    
--○ VIEW 생성(Q&A 게시판 리스트, 상세페이지 조회)
--   QUSTION테이블, ANSWER 테이블, 관심분야 중분류 카테고리 테이블
CREATE OR REPLACE VIEW VIEW_BOARD_QUESTION
AS
SELECT T.QPOST_NUM, T.QPOST_CODE, T.QUSER_CODE, T.QWRITE_DATE, T.QHITCOUNT, T.QTITLE, T.QCONTENT
     , T.QREC, T.QNOTREC, T.QUSER_NAME, T.INTEREST_MC, T.APOST_NUM, T.APOST_CODE, T.AUSER_CODE, T.AWRITE_DATE
     , T.AHITCOUNT, T.ATITLE, T.ACONTENT, T.AREC, T.ANOTREC, T.AUSER_NAME
FROM 
(SELECT SUBSTR(BQ.POST_CODE, 3) AS QPOST_NUM, BQ.POST_CODE AS QPOST_CODE, BQ.USER_CODE AS QUSER_CODE
     , TO_CHAR(BQ.WRITE_DATE,'YYYY-MM-DD') AS QWRITE_DATE
     , BQ.HITCOUNT AS QHITCOUNT, BQ.TITLE AS QTITLE, BQ.CONTENT AS QCONTENT
     , SUBSTR(BA.POST_CODE, 3) AS APOST_NUM, BA.POST_CODE AS APOST_CODE, BA.USER_CODE AS AUSER_CODE
     , TO_CHAR(BA.WRITE_DATE,'YYYY-MM-DD') AS AWRITE_DATE
     , BA.HITCOUNT AS AHITCOUNT, BA.TITLE AS ATITLE, BA.CONTENT AS ACONTENT
     , (SELECT NAME
        FROM TBL_USER_REGISTER
        WHERE USER_CODE = BQ.USER_CODE) AS QUSER_NAME
     , (SELECT NAME
        FROM TBL_USER_REGISTER
        WHERE USER_CODE = BA.USER_CODE) AS AUSER_NAME
     , (SELECT COUNT(*)
        FROM TBL_REC_QUESTION
        WHERE REC_CHECK = 1 AND POST_CODE = BQ.POST_CODE) AS QREC
     , (SELECT COUNT(*)
         FROM TBL_REC_QUESTION
        WHERE REC_CHECK = 2 AND POST_CODE = BQ.POST_CODE) AS QNOTREC
     , (SELECT COUNT(*)
        FROM TBL_REC_ANSWER
        WHERE REC_CHECK = 1 AND POST_CODE = BA.POST_CODE) AS AREC
     , (SELECT COUNT(*)
         FROM TBL_REC_ANSWER
        WHERE REC_CHECK = 2 AND POST_CODE = BA.POST_CODE) AS ANOTREC
     , BQ.INTEREST_MC_CODE "INTEREST_MC_CODE" 
     , (SELECT INTEREST_MC
        FROM TBL_INTEREST_MC
        WHERE INTEREST_MC_CODE = BQ.INTEREST_MC_CODE) AS INTEREST_MC
     , (SELECT COUNT(*)
        FROM TBL_REPORT_REG_QUESTION
        WHERE POST_CODE = BQ.POST_CODE) AS Q_REG_COUNT
     , (SELECT COUNT(*) 
        FROM TBL_REPORT_REG_ANSWER
        WHERE POST_CODE = BA.POST_CODE) AS A_REG_COUNT        
FROM TBL_BOARD_QUESTION BQ FULL OUTER JOIN TBL_BOARD_ANSWER BA
ON BQ.POST_CODE = BA.QPOST_CODE
) T
WHERE T.Q_REG_COUNT < 5 AND T.A_REG_COUNT < 5;
        
            
--○ VIEW 생성(스터디리뷰 게시판 리스트, 상세페이지 조회)
--   스터디리뷰 테이블, 관심분야 중분류 카테고리 테이블
CREATE OR REPLACE VIEW VIEW_BOARD_STUDYREVIEW
AS
SELECT T.POST_NUM, T.POST_CODE, T.PARTI_CODE, T.WRITE_DATE, T.HITCOUNT, T.TITLE, T.CONTENT
     , T.REC, T.NOTREC, T.INTEREST_MC, T.USER_NAME
FROM
(SELECT SUBSTR(BR.POST_CODE, 3) AS POST_NUM, BR.POST_CODE AS POST_CODE, BR.PARTI_CODE AS PARTI_CODE
     , TO_CHAR(BR.WRITE_DATE,'YYYY-MM-DD') AS WRITE_DATE
     , BR.HITCOUNT AS HITCOUNT, BR.TITLE AS TITLE, BR.CONTENT AS CONTENT
     , (SELECT R.NAME
        FROM TBL_STUDY_APPLY A JOIN TBL_STUDY_PARTICIPANT P
        ON A.APPLY_CODE = P.APPLY_CODE
            JOIN TBL_USER_REGISTER R
            ON A.USER_CODE = R.USER_CODE
        WHERE P.PARTI_CODE = BR.PARTI_CODE) AS USER_NAME
     , (SELECT COUNT(*)
        FROM TBL_REC_STUDYREVIEW
        WHERE REC_CHECK = 1 AND POST_CODE = BR.POST_CODE) AS REC
     , (SELECT COUNT(*)
         FROM TBL_REC_STUDYREVIEW
        WHERE REC_CHECK = 2 AND POST_CODE = BR.POST_CODE) AS NOTREC
     , BR.INTEREST_MC_CODE AS INTEREST_MC_CODE
     , (SELECT M.INTEREST_MC
        FROM TBL_INTEREST_MC M
        WHERE M.INTEREST_MC_CODE = BR.INTEREST_MC_CODE) AS INTEREST_MC
     , (SELECT COUNT(*)
        FROM TBL_REPORT_REG_STUDYREVIEW
        WHERE POST_CODE = BR.POST_CODE) AS REG_COUNT
FROM TBL_BOARD_STUDYREVIEW BR
) T
WHERE T.REG_COUNT < 5;
------------------------------------------------------------------------게시판 리스트 출력 뷰 → 신고 5개 받은 게시물은 안보이게 변경