-- 테이블 생성_진주.sql

-- FOREIGN KEY 제약조건은 
-- 테이블 생성 먼저하고 
-- 제약조건 추가하는 방법으로 했습니다.

/*

 ① 모임 요일 테이블
    - FK 제약조건
 ② 요일 테이블
 ③ 인원수 테이블
 ④ 등급 테이블
 ⑤ 스터디 유형 테이블
 ⑥ 관심분야 대분류 테이블
 ⑦ 관심분야 중분류 테이블
    - FK 제약조건
 ⑧ 지역 대분류 테이블
 ⑨ 지역 중분류 테이블
    - FK 제약조건
 ⑩ 스터디 개설 테이블
    - FK 제약조건
     
*/


--① 모임 요일 테이블 생성
CREATE TABLE TBL_STUDY_MEETDAY
( MEETDAY_CODE  VARCHAR2(5)
, WEEKDAY_CODE  VARCHAR2(5)
, STUDY_CODE    VARCHAR2(15)
, START_TIME    NUMBER(2) NOT NULL
, END_TIME      NUMBER(2) NOT NULL
, CONSTRAINT STD_MEETDAY_MDC_PK PRIMARY KEY(MEETDAY_CODE)
);
-- 모임 요일 테이블 제약 외래키 조건
ALTER TABLE TBL_STUDY_MEETDAY
ADD ( CONSTRAINT STD_MEETDAY_WDC_FK FOREIGN KEY(WEEKDAY_CODE)
                 REFERENCES TBL_WEEKDAY(WEEKDAY_CODE));
    
    
    
--② 요일 테이블 생성
CREATE TABLE TBL_WEEKDAY
( WEEKDAY_CODE  VARCHAR2(5)
, WEEKDAY       VARCHAR2(10) NOT NULL
, CONSTRAINT WEEKDAY_WDC_PK PRIMARY KEY(WEEKDAY_CODE)
);



--③ 인원수 테이블 생성
CREATE TABLE TBL_MEMNUM
( MEMNUM_CODE   VARCHAR2(5)
, MEMNUM        NUMBER(1) NOT NULL
, CONSTRAINT MEMNUM_MNC_PK PRIMARY KEY(MEMNUM_CODE)
);



--④ 등급 테이블 생성
CREATE TABLE TBL_USER_RANK
( RANK_CODE VARCHAR2(5) 
, RANK      NUMBER(1) NOT NULL
, MIN_SCORE NUMBER(5) NOT NULL
, MAX_SCORE NUMBER(5) NOT NULL
, CONSTRAINT USER_RANK_RC_PK PRIMARY KEY(RANK_CODE)
);



--⑤ 스터디 유형 테이블 생성
CREATE TABLE TBL_STUDY_TYPE
( STUDY_TYPE_CODE   VARCHAR2(5)
, STUDY_TYPE        VARCHAR2(80)
, CONSTRAINT STD_TYPE_STC_PK PRIMARY KEY(STUDY_TYPE_CODE)
);



--⑥ 관심분야 대분류 테이블 생성
CREATE TABLE TBL_INTEREST_LC
( INTEREST_LC_CODE  VARCHAR2(5)
, INTEREST_LC       VARCHAR2(80) NOT NULL
, CONSTRAINT INTER_LC_IC_PK PRIMARY KEY(INTEREST_LC_CODE)
);



--⑦ 관심분야 중분류 테이블 생성
CREATE TABLE TBL_INTEREST_MC
( INTEREST_MC_CODE  VARCHAR2(5)
, INTEREST_MC       VARCHAR2(80) NOT NULL
, INTEREST_LC_CODE  VARCHAR2(5)
, CONSTRAINT INTER_MC_IC_PK PRIMARY KEY(INTEREST_MC_CODE)
);

--○ 관심분야 중분류 테이블 외래키 제약조건
ALTER TABLE TBL_INTEREST_MC
ADD ( CONSTRAINT INTER_MC_FK FOREIGN KEY(INTEREST_LC_CODE)
                 REFERENCES TBL_INTEREST_LC(INTEREST_LC_CODE));



--⑧ 지역 대분류 테이블 생성
CREATE TABLE TBL_LOC_LC
( LOC_LC_CODE VARCHAR2(5)
, LOC_LC      VARCHAR2(80) NOT NULL
, CONSTRAINT LOC_LC_PK PRIMARY KEY(LOC_LC_CODE)
);



--⑨ 지역 중분류 테이블 생성
CREATE TABLE TBL_LOC_MC
( LOC_MC_CODE   VARCHAR2(5)
, LOC_MC        VARCHAR2(80) NOT NULL
, LOC_LC_CODE   VARCHAR2(5)
, CONSTRAINT LOC_MC_PK PRIMARY KEY(LOC_MC_CODE)
);

--○ 지역 중분류 테이블 외래키 제약조건
ALTER TABLE TBL_LOC_MC
ADD ( CONSTRAINT LOC_MC_FK FOREIGN KEY(LOC_LC_CODE)
                 REFERENCES TBL_LOC_LC(LOC_LC_CODE));



--⑩ 스터디 개설 테이블 생성
CREATE TABLE TBL_STUDY_OPEN
( STUDY_CODE        VARCHAR2(15)
, USER_CODE         VARCHAR2(15)
, WRITE_CODE        DATE DEFAULT SYSDATE NOT NULL
, HITCOUNT          NUMBER DEFAULT 0 NOT NULL
, STUDY_TYPE_CODE   VARCHAR2(5) 
, INTEREST_MC_CODE  VARCHAR2(5)
, START_DATE        DATE NOT NULL
, END_DATE          DATE NOT NULL
, MIN_MEM_CODE       VARCHAR2(5) 
, MAX_MEM_CODE       VARCHAR2(5)
, STUDY_NAME        VARCHAR2(200) NOT NULL
, MIN_RANK          VARCHAR2(5)
, CLOSE_DATE        DATE NOT NULL
, STUDY_DESC        VARCHAR2(1200) NOT NULL
, LOC_MC_CODE       VARCHAR2(5)
, CONSTRAINT STD_OPEN_SC_PK PRIMARY KEY(STUDY_CODE)
);

-- 스터디 개설 테이블 외래키 제약 조건
ALTER TABLE TBL_STUDY_OPEN
ADD ( CONSTRAINT STD_OPEN_UC_FK FOREIGN KEY(USER_CODE)
                 REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
    , CONSTRAINT STD_OPEN_STC_FK FOREIGN KEY(STUDY_TYPE_CODE)
                 REFERENCES TBL_STUDY_TYPE(STUDY_TYPE_CODE)
    , CONSTRAINT STD_OPEN_IMC_FK FOREIGN KEY(INTEREST_MC_CODE)
                 REFERENCES TBL_INTEREST_MC(INTEREST_MC_CODE)
    , CONSTRAINT STD_OPEN_MN_FK FOREIGN KEY(MIN_MEM_CODE)
                 REFERENCES TBL_MEMNUM(MEMNUM_CODE)
    , CONSTRAINT STD_OPEN_MX_FK FOREIGN KEY(MAX_MEM_CODE)
                 REFERENCES TBL_MEMNUM(MEMNUM_CODE)
    , CONSTRAINT STD_OPEN_RK_FK FOREIGN KEY(MIN_RANK)
                 REFERENCES TBL_USER_RANK(RANK_CODE)
    , CONSTRAINT STD_OPEN_LMC_FK FOREIGN KEY(LOC_MC_CODE)
                 REFERENCES TBL_LOC_MC(LOC_MC_CODE)
);









