--○ 회원 코드 생성 테이블 생성
CREATE TABLE TBL_USER_CODE_CREATE
(USER_CODE   VARCHAR2(10)                   -- 회원코드(PK)
,CONSTRAINT USER_CODE_CREATE_UC_PK PRIMARY KEY(USER_CODE)
);
  
            
--○ 비밀번호 찾기 질문 테이블 생성
CREATE TABLE TBL_PW_SEARCH_QUE
(PW_SRCH_QUE_CODE  VARCHAR2(5)              -- 비밀번호 찾기 질문 코드(PK)
,PW_SRCH_QUE       VARCHAR2(200) NOT NULL   -- 비밀번호 찾기 질문
,CONSTRAINT PW_SRCH_QUE_PSQC_PK PRIMARY KEY(PW_SRCH_QUE_CODE)
);


--○ 현재 직업 대분류 테이블 생성
CREATE TABLE TBL_JOB_LC
(JOB_LC_CODE   VARCHAR2(10)                 -- 직업 대분류 코드(PK)
,JOB_LC        VARCHAR2(100) NOT NULL       -- 직종
,CONSTRAINT JOB_LC_JLC_PK PRIMARY KEY(JOB_LC_CODE)
);


--○ 현재 직업 중분류 테이블 생성
CREATE TABLE TBL_JOB_MC
(JOB_MC_CODE  VARCHAR2(10)                   -- 직업 중분류 코드(PK)
,JOB_MC       VARCHAR2(100) NOT NULL         -- 직종
,JOB_LC_CODE  VARCHAR2(10)  NOT NULL         -- 직업 대분류 코드(FK)
,CONSTRAINT JOB_MC_JMC_PK PRIMARY KEY(JOB_MC_CODE)
,CONSTRAINT JOB_MC_JLC_FK FOREIGN KEY(JOB_LC_CODE)
            REFERENCES TBL_JOB_LC(JOB_LC_CODE)
);


--○ 계정 정지 등록 테이블 생성
CREATE TABLE TBL_ACCOUNT_SUSPEND
(ACCT_SUS_CODE   VARCHAR2(10)                       -- 계정 정지 코드(PK)
,ACCT_SUS_DATE   DATE  DEFAULT SYSDATE NOT NULL     -- 계정 정지 일자
,WARNING_CODE    VARCHAR2(15) NOT NULL              -- 경고 등록 코드(FK)
,CONSTRAINT ACCT_SUS_ASC_PK PRIMARY KEY(ACCT_SUS_CODE)
,CONSTRAINT ACCT_SUS_WC_FK FOREIGN KEY(WARNING_CODE)
            REFERENCES TBL_WARNING(WARNING_CODE)
);


--○ 탈퇴 카테고리 테이블 생성
CREATE TABLE TBL_WITHDRAWAL_CATEGORY
(WDL_CTG_CODE   VARCHAR2(5)                 -- 탈퇴 카테고리 코드(PK)
,WDL_CTG        VARCHAR2(50) NOT NULL       -- 탈퇴 카테고리 항목
,CONSTRAINT WDL_CTG_WCC_PK PRIMARY KEY(WDL_CTG_CODE)
);


--○ 탈퇴 기록 및 개인정보 보관 테이블 생성
CREATE TABLE TBL_WITHDRAWAL_INFO
(WDL_CODE       VARCHAR2(10)                        -- 탈퇴 코드(PK)
,WDL_DATE       DATE  DEFAULT SYSDATE NOT NULL      -- 탈퇴 일자
,WDL_CTG_CODE   VARCHAR2(5)   NOT NULL              -- 탈퇴 카테고리 코드(FK)
,SSN            VARCHAR2(13)  NOT NULL              -- 탈퇴자 주민번호
,USER_CODE      VARCHAR2(10)  NOT NULL              -- 사용자 코드
,WDL_REASON     VARCHAR2(200) NOT NULL              -- 탈퇴 사유
,CONSTRAINT WDL_INFO_WC_PK PRIMARY KEY(WDL_CODE)
,CONSTRAINT WDL_INFO_WCC_FK FOREIGN KEY(WDL_CTG_CODE)
            REFERENCES TBL_WITHDRAWAL_CATEGORY(WDL_CTG_CODE)
);


--○ 회원 등록 테이블 생성          
CREATE TABLE TBL_USER_REGISTER
(USER_CODE         VARCHAR2(10)                     -- 사용자 코드(PK)
, ID               VARCHAR2(30)          NOT NULL   -- 아이디
, PW               VARCHAR2(20)          NOT NULL   -- 비밀번호
, SSN              VARCHAR2(20)          NOT NULL   -- 주민번호
, PW_SRCH_QUE_CODE VARCHAR2(5)           NOT NULL   -- 비밀번호 찾기 질문 코드(FK)
, PW_SRCH_QUE_ANS  VARCHAR2(50)          NOT NULL   -- 비밀번호 찾기 답변
, INTEREST_MC_CODE VARCHAR2(5)           NOT NULL   -- 관심 분야 중분류 코드(FK)
, LOC_MC_CODE      VARCHAR2(5)           NOT NULL   -- 지역 중분류 코드(FK)
, JOB_MC_CODE      VARCHAR2(10)          NOT NULL   -- 현재 직업 중분류 코드(FK)
, EMAIL            VARCHAR2(30)          NOT NULL   -- 이메일
, NAME             VARCHAR2(30)          NOT NULL   -- 이름
, REGDATE          DATE  DEFAULT SYSDATE NOT NULL   -- 가입일자
, STUDY_TYPE_CODE  VARCHAR2(5)           NOT NULL   -- 스터디 유형 코드(FK)
,CONSTRAINT USER_REG_UC_PK PRIMARY KEY(USER_CODE)
,CONSTRAINT USER_REG_UC_FK FOREIGN KEY(USER_CODE)
            REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
,CONSTRAINT USER_REG_PSQC_FK FOREIGN KEY(PW_SRCH_QUE_CODE)
            REFERENCES TBL_PW_SEARCH_QUE(PW_SRCH_QUE_CODE)
,CONSTRAINT USER_REG_IMC_FK FOREIGN KEY(INTEREST_MC_CODE)
            REFERENCES TBL_INTEREST_MC(INTEREST_MC_CODE)
,CONSTRAINT USER_REG_JMC_FK FOREIGN KEY(JOB_MC_CODE)
            REFERENCES TBL_JOB_MC(JOB_MC_CODE)
,CONSTRAINT USER_REG_STC_FK FOREIGN KEY(STUDY_TYPE_CODE)
            REFERENCES TBL_STUDY_TYPE(STUDY_TYPE_CODE)            
);