--■ 테이블 INSERT 구문 ■--

DESC TBL_BOARD_FREE;


--○ IT기술정보공유 테이블
INSERT INTO TBL_BOARD_INFORM(POST_CODE, USER_CODE, WRITE_CODE, HITCOUNT, TITLE, CONTENT, INTEREST_MC_CODE) 
VALUES (||BI||BOARD_INFORM_SEQ.NEXTVAL, 'UC1', DEFAULT, 3, '안녕하세요', '파이널 프로젝트 4조 본문입니다.', 'IM1');  


--○ 면접/코딩테스트 후기 테이블
INSERT INTO TBL_BOARD_INTERVIEW(POST_CODE, USER_CODE, WRITE_CODE, HITCOUNT, TITLE, CONTENT, INTEREST_MC_CODE) 
VALUES (||BC||BOARD_INTERVIEW_SEQ.NEXTVAL, 'UC1', DEFAULT, 3, '안녕하세요', '파이널 프로젝트 4조 본문입니다.', 'IM1');  


--○ 세미나 및 공모전 테이블
INSERT INTO TBL_BOARD_SEMINAR(POST_CODE, USER_CODE, WRITE_CODE, HITCOUNT, TITLE, CONTENT, SEMINAR_CATEGORY_CODE) 
VALUES (||BS||BOARD_SEMINAR_SEQ.NEXTVAL, 'UC1', DEFAULT, 3, '안녕하세요', '파이널 프로젝트 4조 본문입니다.', 'IM1');  


--○ 자유게시판 테이블
INSERT INTO TBL_BOARD_FREE(POST_CODE, USER_CODE, WRITE_CODE, HITCOUNT, TITLE, CONTENT) 
VALUES (||BF||BOARD_FREE_SEQ.NEXTVAL, 'UC1', DEFAULT, 3, '안녕하세요', '파이널 프로젝트 4조 본문입니다.');  


--○ Q&A 질문 테이블
INSERT INTO TBL_BOARD_QUESTION(POST_CODE, USER_CODE, WRITE_CODE, HITCOUNT, TITLE, CONTENT, INTEREST_MC_CODE) 
VALUES (||BQ||BOARD_QUESTION_SEQ.NEXTVAL, 'UC1', DEFAULT, 3, '안녕하세요', '파이널 프로젝트 4조 본문입니다.', 'IM1');  


--○ Q&A 답변 테이블
INSERT INTO TBL_BOARD_ANSWER(POST_CODE, USER_CODE, WRITE_CODE, HITCOUNT, TITLE, CONTENT, INTEREST_MC_CODE) 
VALUES (||BA||BOARD_ANSWER_SEQ.NEXTVAL, 'UC1', DEFAULT, 3, '안녕하세요', '파이널 프로젝트 4조 본문입니다.', 'IM1');  


--○ 스터디 후기 테이블
INSERT INTO TBL_BOARD_STUDYREVIEW(POST_CODE, PARTI_CODE, WRITE_CODE, HITCOUNT, TITLE, CONTENT, INTEREST_MC_CODE) 
VALUES (||BR||BOARD_STUDYREVIEW_SEQ.NEXTVAL, 'PT1', DEFAULT, 3, '안녕하세요', '파이널 프로젝트 4조 본문입니다.', 'IM1');  




--○ IT기술정보공유 댓글 테이블
CREATE SEQUENCE COMMENT_INFORM_SEQ
NOCACHE;
INSERT INTO TBL_COMMENT_INFORM(POST_CODE, PARTI_CODE, WRITE_CODE, HITCOUNT, TITLE, CONTENT, INTEREST_MC_CODE) 
VALUES (||CI||COMMENT_INFORM_SEQ.NEXTVAL, 'PT1', DEFAULT, 3, '안녕하세요', '파이널 프로젝트 4조 본문입니다.', 'IM1');  


--○ 면접 및 코딩테스트 후기 댓글 테이블
CREATE SEQUENCE COMMENT_INTERVIEW_SEQ
NOCACHE;

--○ 세미나 및 공모전 댓글 테이블
CREATE SEQUENCE COMMENT_SEMINAR_SEQ
NOCACHE;

--○ 자유게시판 댓글 테이블
CREATE SEQUENCE COMMENT_FREE_SEQ
NOCACHE;

--○ Q&A 질문 댓글 테이블
CREATE SEQUENCE COMMENT_QUESTION_SEQ
NOCACHE;

--○ Q&A 답변 댓글 테이블
CREATE SEQUENCE COMMENT_AMSWER_SEQ
NOCACHE;

--○ 스터디 후기 댓글 테이블
CREATE SEQUENCE COMMENT_STUDYREVIEW_SEQ
NOCACHE;





--○ IT기술정보공유 추천/비추천 테이블
CREATE SEQUENCE REC_INFORM_SEQ
NOCACHE;

--○ 세미나 및 공모전 추천/비추천 테이블
CREATE SEQUENCE REC_SEMINAR_SEQ
NOCACHE;

--○ 면접/코딩테스트 후기 추천비추천 테이블
CREATE SEQUENCE REC_INTERVIEW_SEQ
NOCACHE;

--○ 자유게시판 추천비추천 테이블
CREATE SEQUENCE REC_FREE_SEQ
NOCACHE;

--○ Q&A 질문 추천비추천 테이블
CREATE SEQUENCE REC_QUESTION_SEQ
NOCACHE;


--○ Q&A 답변 추천비추천 테이블
CREATE SEQUENCE REC_INFORM_SEQ
NOCACHE;

--○ 스터디 후기 추천/ 비추천 테이블
CREATE SEQUENCE REC_STUDYREVIEW_SEQ
NOCACHE;

--○ IT기술정보공유 신고등록 테이블
CREATE SEQUENCE RPT_RG_INFORM_SEQ
NOCACHE;

<<<<<<< HEAD
--○ 면접/코딩테스트 후기  신고등록 테이블
CREATE SEQUENCE RPT_RG_INTERVIEW_SEQ
NOCACHE;


--○ 세미나 및 공모전  신고등록 테이블
CREATE SEQUENCE RPT_RG_SEMINAR_SEQ
NOCACHE;

--○ 자유게시판 신고등록 테이블
CREATE SEQUENCE RPT_RG_FREE_SEQ
NOCACHE;


--○ Q&A 질문 신고등록 테이블
CREATE SEQUENCE RPT_RG_QUESTION_SEQ
NOCACHE;

--○ Q&A 답변 신고등록 테이블
CREATE SEQUENCE RPT_RG_ANSWER_SEQ
NOCACHE;

--○ 스터디 후기 신고 등록
CREATE SEQUENCE RPT_RG_STUDYREVIEW_SEQ
NOCACHE;

--○ IT기술정보공유 신고처리 테이블
CREATE SEQUENCE RPT_HD_INFORM_SEQ
NOCACHE;

--○ 면접/코딩테스트 후기 신고처리 테이블
CREATE SEQUENCE RPT_HD_INTERVIEW_SEQ
NOCACHE;

--○ 세미나 및 공모전 신고처리 테이블
CREATE SEQUENCE RPT_HD_SEMINAR_SEQ
NOCACHE;


--○ 자유게시판 신고처리 테이블
CREATE SEQUENCE RPT_HD_FREE_SEQ
NOCACHE;

--○ Q&A 질문 신고처리 테이블
CREATE SEQUENCE RPT_HD_QUESTION_SEQ
NOCACHE;

--○ Q&A 답변 신고처리 테이블
CREATE SEQUENCE RPT_HD_ANSWER_SEQ
NOCACHE;

--○ 스터디 후기 신고 처리  
CREATE SEQUENCE RPT_HD_STUDYREVIEW_SEQ
NOCACHE;  

--○ 실습 테이블 생성(신고 처리 테이블)
CREATE SEQUENCE HD_RESULT_SEQ
NOCACHE;

--○ 실습 테이블 생성(세미나 카테고리 테이블)
CREATE SEQUENCE SEMI_CTG_SEQ
NOCACHE;

--○ 실습 테이블 생성(게시글 신고 카테고리 테이블)
CREATE SEQUENCE POST_RPT_CTG_SEQ
NOCACHE;













