--■■■ 시퀀스(SEQUENCE) 생성 ■■■--


-- ○ 모임 요일 테이블 시퀀스 생성
CREATE SEQUENCE STD_MEETDAY_SEQ
NOCACHE;

-- ○ 요일 테이블 시퀀스 생성
CREATE SEQUENCE WEEKDAY_SEQ
NOCACHE;

-- ○ 인원수 테이블 시퀀스 생성
CREATE SEQUENCE MEMNUM_SEQ
NOCACHE;

-- ○ 등급 테이블 시퀀스 생성
CREATE SEQUENCE USER_RANK_SEQ
NOCACHE;

-- ○ 스터디 유형 테이블 시퀀스 생성
CREATE SEQUENCE STD_TYPE_SEQ
NOCACHE;

-- ○ 관심분야 대분류 테이블 시퀀스 생성
CREATE SEQUENCE INTER_LC_SEQ
NOCACHE;

-- ○ 관심분야 중분류 테이블 시퀀스 생성
CREATE SEQUENCE INTER_MC_SEQ
NOCACHE;

-- ○ 지역 대분류 테이블 시퀀스 생성
CREATE SEQUENCE LOC_LC_SEQ
NOCACHE;

-- ○ 지역 중분류 테이블 시퀀스 생성
CREATE SEQUENCE LOC_MC_SEQ
NOCACHE;

-- ○ 스터디 개설 테이블 시퀀스 생성
CREATE SEQUENCE STD_OPEN_SEQ
NOCACHE;

--○ 스터디원 신고 등록 시퀀스
CREATE SEQUENCE MEM_RR_SEQ
NOCACHE;

--○ 스터디원 신고 카테고리 시퀀스
CREATE SEQUENCE MEM_RC_SEQ
NOCACHE;

--○ 스터디원 신고 처리 시퀀스
CREATE SEQUENCE MEM_RH_SEQ
NOCACHE;

--○ 스터디원 신고 처리 결과 시퀀스
CREATE SEQUENCE MEM_RHR_SEQ
NOCACHE;

--○ 내보내기 등록 시퀀스
CREATE SEQUENCE MEM_KR_SEQ
NOCACHE;

--○ 내보내기 처리 시퀀스
CREATE SEQUENCE MEM_KH_SEQ
NOCACHE;

--○ IT기술정보공유 테이블
CREATE SEQUENCE BOARD_INFORM_SEQ
NOCACHE;

--○ 면접/코딩테스트 후기 테이블
CREATE SEQUENCE BOARD_INTERVIEW_SEQ
NOCACHE;

--○ 세미나 및 공모전 테이블
CREATE SEQUENCE BOARD_SEMINAR_SEQ
NOCACHE;

--○ 자유게시판 테이블
CREATE SEQUENCE BOARD_FREE_SEQ
NOCACHE;

--○ Q&A 질문 테이블
CREATE SEQUENCE BOARD_QUESTION_SEQ
NOCACHE;

--○ Q&A 답변 테이블
CREATE SEQUENCE BOARD_ANSWER_SEQ
NOCACHE;

--○ 스터디 후기 테이블
CREATE SEQUENCE BOARD_STUDYREVIEW_SEQ
NOCACHE;

--○ IT기술정보공유 댓글 테이블
CREATE SEQUENCE COMMENT_INFORM_SEQ
NOCACHE;

--○ 면접 및 코딩테스트 후기 댓글 테이블
CREATE SEQUENCE COMMENT_INTERVIEW_SEQ
NOCACHE;

--○ 세미나 및 공모전 댓글 테이블
CREATE SEQUENCE COMMENT_SEMINAR_SEQ
NOCACHE;

--○ 자유게시판 댓글 테이블
CREATE SEQUENCE COMMENT_FREE_SEQ
NOCACHE;

--○ Q&A 질문 댓글 테이블
CREATE SEQUENCE COMMENT_QUESTION_SEQ
NOCACHE;

--○ Q&A 답변 댓글 테이블
CREATE SEQUENCE COMMENT_ANSWER_SEQ
NOCACHE;

--○ 스터디 후기 댓글 테이블
CREATE SEQUENCE COMMENT_STUDYREVIEW_SEQ
NOCACHE;

--○ IT기술정보공유 추천/비추천 테이블
CREATE SEQUENCE REC_INFORM_SEQ
NOCACHE;

--○ 세미나 및 공모전 추천/비추천 테이블
CREATE SEQUENCE REC_SEMINAR_SEQ
NOCACHE;

--○ 면접/코딩테스트 후기 추천비추천 테이블
CREATE SEQUENCE REC_INTERVIEW_SEQ
NOCACHE;

--○ 자유게시판 추천비추천 테이블
CREATE SEQUENCE REC_FREE_SEQ
NOCACHE;

--○ Q&A 질문 추천비추천 테이블
CREATE SEQUENCE REC_QUESTION_SEQ
NOCACHE;

--○ Q&A 답변 추천비추천 테이블
CREATE SEQUENCE REC_INFORM_SEQ
NOCACHE;

--○ 스터디 후기 추천/ 비추천 테이블
CREATE SEQUENCE REC_STUDYREVIEW_SEQ
NOCACHE;

--○ IT기술정보공유 신고등록 테이블
CREATE SEQUENCE RPT_RG_INFORM_SEQ
NOCACHE;

--○ 면접/코딩테스트 후기  신고등록 테이블
CREATE SEQUENCE RPT_RG_INTERVIEW_SEQ
NOCACHE;

--○ 세미나 및 공모전  신고등록 테이블
CREATE SEQUENCE RPT_RG_SEMINAR_SEQ
NOCACHE;

--○ 자유게시판 신고등록 테이블
CREATE SEQUENCE RPT_RG_FREE_SEQ
NOCACHE;

--○ Q&A 질문 신고등록 테이블
CREATE SEQUENCE RPT_RG_QUESTION_SEQ
NOCACHE;

--○ Q&A 답변 신고등록 테이블
CREATE SEQUENCE RPT_RG_ANSWER_SEQ
NOCACHE;

--○ 스터디 후기 신고 등록
CREATE SEQUENCE RPT_RG_STUDYREVIEW_SEQ
NOCACHE;

--○ IT기술정보공유 신고처리 테이블
CREATE SEQUENCE RPT_HD_INFORM_SEQ
NOCACHE;

--○ 면접/코딩테스트 후기 신고처리 테이블
CREATE SEQUENCE RPT_HD_INTERVIEW_SEQ
NOCACHE;

--○ 세미나 및 공모전 신고처리 테이블
CREATE SEQUENCE RPT_HD_SEMINAR_SEQ
NOCACHE;

--○ 자유게시판 신고처리 테이블
CREATE SEQUENCE RPT_HD_FREE_SEQ
NOCACHE;

--○ Q&A 질문 신고처리 테이블
CREATE SEQUENCE RPT_HD_QUESTION_SEQ
NOCACHE;

--○ Q&A 답변 신고처리 테이블
CREATE SEQUENCE RPT_HD_ANSWER_SEQ
NOCACHE;

--○ 스터디 후기 신고 처리  
CREATE SEQUENCE RPT_HD_STUDYREVIEW_SEQ
NOCACHE;  

--○ 실습 테이블 생성(신고 처리 테이블)
CREATE SEQUENCE HD_RESULT_SEQ
NOCACHE;

--○ 실습 테이블 생성(세미나 카테고리 테이블)
CREATE SEQUENCE SEMI_CTG_SEQ
NOCACHE;

--○ 실습 테이블 생성(게시글 신고 카테고리 테이블)
CREATE SEQUENCE POST_RPT_CTG_SEQ
NOCACHE;

--○ 회원 코드 생성 테이블
CREATE SEQUENCE USER_CODE_CRE_SEQ
NOCACHE;

--○ 회원 등록 테이블 
CREATE SEQUENCE USER_REG_SEQ
NOCACHE;

--○ 비밀번호 찾기 질문 테이블
CREATE SEQUENCE PW_SRCH_QUE_SEQ
NOCACHE;

--○ 현재 직업 대분류 테이블
CREATE SEQUENCE JOB_LC_SEQ
NOCACHE;

--○ 현재 직업 중분류 테이블
CREATE SEQUENCE JOB_LC_SEQ
NOCACHE;

--○ 계정 정지 등록 테이블
CREATE SEQUENCE ACCT_SUS_SEQ
NOCACHE;

--○ 탈퇴 기록 및 개인정보 보관 테이블
CREATE SEQUENCE WDL_INFO_SEQ
NOCACHE;

--○ 탈퇴 카테고리 테이블
CREATE SEQUENCE WDL_CTG_SEQ
NOCACHE;

-- ○ 직책 테이블
CREATE SEQUENCE STUDY_POS_SEQ
NOCACHE;

--○ 스터디 신청 테이블
CREATE SEQUENCE STUDY_APL_SEQ
NOCACHE;

--○ 스터디 취소 처리 테이블
CREATE SEQUENCE STUDY_CANC_SEQ
NOCACHE;

--○ 스터디 참가 테이블
CREATE SEQUENCE STUDY_PARTI_SEQ
NOCACHE;

--○ 스터디 컨텐츠 테이블
CREATE SEQUENCE STUDY_CON_SEQ
NOCACHE;

--○ 스터디 평가 테이블
CREATE SEQUENCE STUDY_ASSE_SEQ
NOCACHE;

--○ 출석부 테이블
CREATE SEQUENCE STUDY_ATT_SEQ
NOCACHE;

--○ 일정관리 테이블
CREATE SEQUENCE STUDY_SCHE_SEQ
NOCACHE;

--○ 외출등록 테이블
CREATE SEQUENCE STUDY_STO_SEQ
NOCACHE;

--○ 스터디원 평가 등록
CREATE SEQUENCE STUDY_IASSE_SEQ
NOCACHE;

--○ 평가점수 테이블
CREATE SEQUENCE STUDY_ASSE_RESP_SEQ
NOCACHE;

--○ 평가항목 테이블
CREATE SEQUENCE STUDY_ASSE_ITM_SEQ
NOCACHE;

--○ 점수 기록 테이블
CREATE SEQUENCE STUDY_SCOR_SEQ
NOCACHE;

--○ 경고 등록 테이블
CREATE SEQUENCE STUDY_WARN_SEQ
NOCACHE;

--○ 스터디 댓글 테이블
CREATE SEQUENCE COMM_STD_SEQ
NOCACHE;

-- ○ 스터디 신고 등록 테이블
CREATE SEQUENCE STUDY_ACC_SEQ
NOCACHE;

-- ○ 스터디 신고 처리 테이블
CREATE SEQUENCE STUDY_ACC_HAN_SEQ
NOCACHE;

-- ○ 스터디 경고 등록 테이블
CREATE SEQUENCE STUDY_WAR_SEQ
NOCACHE;

-- ○ 욕설 테이블
CREATE SEQUENCE CURSE_SEQ
NOCACHE;

-- ○ 고객센터(1:1문의) 테이블
CREATE SEQUENCE ASK_SEQ
NOCACHE;

-- ○ 고객센터(공지사항) 테이블
CREATE SEQUENCE NOTICE_SEQ
NOCACHE;

-- ○ 관리자 테이블
CREATE SEQUENCE ADMIN_SEQ
NOCACHE;

-- 추가
CREATE SEQUENCE JOB_MC_SEQ NOCACHE;
CREATE SEQUENCE REC_ANSWER_SEQ NOCACHE;
CREATE SEQUENCE STD_MEETDAY_SEQ NOCACHE;
CREATE SEQUENCE STUDY_SCORE_SEQ NOCACHE;
CREATE SEQUENCE STUDY_ASSE_RESP_SEQ NOCACHE;
CREATE SEQUENCE STUDY_ACC_SEQ NOCACHE;
