--1. FK가 없는 테이블
  -- 회원코드생성
CREATE TABLE TBL_USER_CODE_CREATE
(USER_CODE   VARCHAR2(10)                   -- 회원코드(PK)
,CONSTRAINT USER_CODE_CREATE_UC_PK PRIMARY KEY(USER_CODE)
);  
  -- 스터디 유형
CREATE TABLE TBL_STUDY_TYPE
( STUDY_TYPE_CODE   VARCHAR2(5)
, STUDY_TYPE        VARCHAR2(80)
, CONSTRAINT STD_TYPE_STC_PK PRIMARY KEY(STUDY_TYPE_CODE)
);  
  -- 관심분야 대분류
CREATE TABLE TBL_INTEREST_LC
( INTEREST_LC_CODE  VARCHAR2(5)
, INTEREST_LC       VARCHAR2(80) NOT NULL
, CONSTRAINT INTER_LC_IC_PK PRIMARY KEY(INTEREST_LC_CODE)
);  
  -- 지역대분류
CREATE TABLE TBL_LOC_LC
( LOC_LC_CODE VARCHAR2(5)
, LOC_LC      VARCHAR2(80) NOT NULL
, CONSTRAINT LOC_LC_PK PRIMARY KEY(LOC_LC_CODE)
);  
  -- 현재직업 대분류
CREATE TABLE TBL_JOB_LC
(JOB_LC_CODE   VARCHAR2(10)                 -- 직업 대분류 코드(PK)
,JOB_LC        VARCHAR2(100) NOT NULL       -- 직종
,CONSTRAINT JOB_LC_JLC_PK PRIMARY KEY(JOB_LC_CODE)
);  
  -- 요일
CREATE TABLE TBL_WEEKDAY
( WEEKDAY_CODE  VARCHAR2(5)
, WEEKDAY       VARCHAR2(10) NOT NULL
, CONSTRAINT WEEKDAY_WDC_PK PRIMARY KEY(WEEKDAY_CODE)
);  
  -- 인원수
CREATE TABLE TBL_MEMNUM
( MEMNUM_CODE   VARCHAR2(5)
, MEMNUM        NUMBER(1) NOT NULL
, CONSTRAINT MEMNUM_MNC_PK PRIMARY KEY(MEMNUM_CODE)
);
  
  -- 등급
CREATE TABLE TBL_USER_RANK
( RANK_CODE VARCHAR2(5) 
, RANK      NUMBER(1) NOT NULL
, MIN_SCORE NUMBER(5) NOT NULL
, MAX_SCORE NUMBER(5) NOT NULL
, CONSTRAINT USER_RANK_RC_PK PRIMARY KEY(RANK_CODE)
);  
  -- 직책
CREATE TABLE TBL_STUDY_POSITION
( POSITION_CODE VARCHAR2(5)
, POSITION      VARCHAR2(20) NOT NULL
, CONSTRAINT STUDY_POSITION_PC_PK PRIMARY KEY (POSITION_CODE)
);  
  -- 스터디원신고카테고리
CREATE TABLE TBL_MEM_REPORT_CTG
( MEM_REPORT_CTG_CODE   VARCHAR2(3)
, MEM_REPORT_CTG        VARCHAR2(30) NOT NULL
, CONSTRAINT MEM_REP_CTG_MRCC_PK PRIMARY KEY(MEM_REPORT_CTG_CODE)
);  
  -- 스터디원신고처리결과
CREATE TABLE TBL_MEM_REPORT_HANDLE_RESULT
( MEM_REPORT_HANDLE_RESULT_CODE VARCHAR2(3)
, MEM_REPORT_HANDLE_RESULT      VARCHAR2(20) NOT NULL
, CONSTRAINT MEM_REP_HDL_RST_MRHRC_PK PRIMARY KEY(MEM_REPORT_HANDLE_RESULT_CODE)
);  
  -- 탈퇴 카테고리
CREATE TABLE TBL_WITHDRAWAL_CATEGORY
(WDL_CTG_CODE   VARCHAR2(5)                 -- 탈퇴 카테고리 코드(PK)
,WDL_CTG        VARCHAR2(50) NOT NULL       -- 탈퇴 카테고리 항목
,CONSTRAINT WDL_CTG_WCC_PK PRIMARY KEY(WDL_CTG_CODE)
);  
  -- 욕설 등록
CREATE TABLE TBL_CURSE
( CURSE_CODE                  VARCHAR(20)     NOT NULL
, CURSE_KIND                   VARCHAR(300)     NOT NULL
, CONSTRAINT CURSE_CC_PK PRIMARY KEY(CURSE_CODE)
);  
  -- 말머리(세미나,공모전)
CREATE TABLE TBL_SEMINAR_CATEGORY
( SEMINAR_CATEGORY_CODE    VARCHAR2(20)    NOT NULL --PK
, SEMINAR_CATEGORY         VARCHAR2(300)   NOT NULL 
, CONSTRAINT SEMI_CTG_PK PRIMARY KEY(SEMINAR_CATEGORY_CODE)        
);  
  -- 게시물신고카테고리
CREATE TABLE TBL_POST_REPORT_CTG
( POST_REPORT_CTG_CODE     VARCHAR2(10)    NOT NULL --PK
, POST_REPORT_CTG          VARCHAR2(100)   NOT NULL 
, CONSTRAINT POST_RPT_CTG_PRCC_PK PRIMARY KEY(POST_REPORT_CTG_CODE)       
);  
  -- 게시물 신고 처리결과
CREATE TABLE TBL_HANDLE_RESULT
( HANDLE_RESULT_CODE    VARCHAR2(5)    NOT NULL --PK
, HANDLE_RESULT         VARCHAR2(20)   NOT NULL 
, CONSTRAINT HLE_RES_HRC_PK PRIMARY KEY(HANDLE_RESULT_CODE)        
);  
  -- 관리자
CREATE TABLE TBL_ADMIN
( ADMIN_CODE                    VARCHAR(20)     NOT NULL 
, ADMIN_ID                         VARCHAR(20)     NOT NULL 
, ADMIN_PW                       VARCHAR(20)     NOT NULL 
, CONSTRAINT ADMIN_AC_PK PRIMARY KEY(ADMIN_CODE)
);  
  -- 평가점수
CREATE TABLE TBL_STUDY_ASSESS_RESP
( RESP_CODE VARCHAR2(5)
, RESP      VARCHAR2(40)    NOT NULL
, SCORE     NUMBER(3)       NOT NULL
, CONSTRAINT STUDY_ASS_RESP_RC_PK PRIMARY KEY (RESP_CODE)
);  
  -- 평가항목
CREATE TABLE TBL_STUDY_ASSESS_ITEM
( ITEM_CODE VARCHAR2(5) 
, ITEM      VARCHAR2(100)   NOT NULL
, CONSTRAINT STUDY_ASS_ITEM_IC_PK PRIMARY KEY (ITEM_CODE)
);  
  -- 비밀번호 찾기 질문
CREATE TABLE TBL_PW_SEARCH_QUE
(PW_SRCH_QUE_CODE  VARCHAR2(5)              -- 비밀번호 찾기 질문 코드(PK)
,PW_SRCH_QUE       VARCHAR2(200) NOT NULL   -- 비밀번호 찾기 질문
,CONSTRAINT PW_SRCH_QUE_PSQC_PK PRIMARY KEY(PW_SRCH_QUE_CODE)
);  


--2. 위 테이블의 pk를 fk로 갖고있는 테이블
  -- 관심분야 중분류 
CREATE TABLE TBL_INTEREST_MC
( INTEREST_MC_CODE  VARCHAR2(5)
, INTEREST_MC       VARCHAR2(80) NOT NULL
, INTEREST_LC_CODE  VARCHAR2(5)
, CONSTRAINT INTER_MC_IC_PK PRIMARY KEY(INTEREST_MC_CODE)
);  
--○ 관심분야 중분류 테이블 외래키 제약조건
ALTER TABLE TBL_INTEREST_MC
ADD ( CONSTRAINT INTER_MC_FK FOREIGN KEY(INTEREST_LC_CODE)
                 REFERENCES TBL_INTEREST_LC(INTEREST_LC_CODE));

  -- 지역 중분류
CREATE TABLE TBL_LOC_MC
( LOC_MC_CODE   VARCHAR2(5)
, LOC_MC        VARCHAR2(80) NOT NULL
, LOC_LC_CODE   VARCHAR2(5)
, CONSTRAINT LOC_MC_PK PRIMARY KEY(LOC_MC_CODE)
);
--○ 지역 중분류 테이블 외래키 제약조건
ALTER TABLE TBL_LOC_MC
ADD ( CONSTRAINT LOC_MC_FK FOREIGN KEY(LOC_LC_CODE)
                 REFERENCES TBL_LOC_LC(LOC_LC_CODE));

  -- 현재직업 중분류
CREATE TABLE TBL_JOB_MC
(JOB_MC_CODE  VARCHAR2(10)                   -- 직업 중분류 코드(PK)
,JOB_MC       VARCHAR2(100) NOT NULL         -- 직종
,JOB_LC_CODE  VARCHAR2(10)  NOT NULL         -- 직업 대분류 코드(FK)
,CONSTRAINT JOB_MC_JMC_PK PRIMARY KEY(JOB_MC_CODE)
,CONSTRAINT JOB_MC_JLC_FK FOREIGN KEY(JOB_LC_CODE)
            REFERENCES TBL_JOB_LC(JOB_LC_CODE)
);  
  -- 고객센터(공지사항)
CREATE TABLE TBL_NOTICE
( NOTICE_CODE                    VARCHAR(20)     NOT NULL 
, NOTICE_DATE                     DATE      DEFAULT SYSDATE  NOT NULL
, NOTICE_TITLE                     VARCHAR(300)     NOT NULL  
, NOTICE_CONTENT               VARCHAR(4000)     NOT NULL 
, ADMIN_CODE                    VARCHAR(20)     NOT NULL 
, HITCOUNT                        NUMBER DEFAULT 0
, CONSTRAINT NOTICE_NC_PK PRIMARY KEY(NOTICE_CODE)
, CONSTRAINT NOTICE_AC_FK FOREIGN KEY(ADMIN_CODE)
                     REFERENCES TBL_ADMIN(ADMIN_CODE)
);  


--3. 위 테이블들의 pk를 fk로 갖고있는 테이블
  -- 회원등록(사용자코드)
CREATE TABLE TBL_USER_REGISTER
(USER_CODE         VARCHAR2(10)                     -- 사용자 코드(PK)
, ID               VARCHAR2(30)          NOT NULL   -- 아이디
, PW               VARCHAR2(20)          NOT NULL   -- 비밀번호
, SSN              VARCHAR2(13)          NOT NULL   -- 주민번호
, PW_SRCH_QUE_CODE VARCHAR2(5)           NOT NULL   -- 비밀번호 찾기 질문 코드(FK)
, PW_SRCH_QUE_ANS  VARCHAR2(50)          NOT NULL   -- 비밀번호 찾기 답변
, INTEREST_MC_CODE VARCHAR2(5)           NOT NULL   -- 관심 분야 중분류 코드(FK)
, LOC_MC_CODE      VARCHAR2(5)           NOT NULL   -- 지역 중분류 코드(FK)
, JOB_MC_CODE      VARCHAR2(10)          NOT NULL   -- 현재 직업 중분류 코드(FK)
, EMAIL            VARCHAR2(30)          NOT NULL   -- 이메일
, NAME             VARCHAR2(30)          NOT NULL   -- 이름
, REGDATE          DATE  DEFAULT SYSDATE NOT NULL   -- 가입일자
, STUDY_TYPE_CODE  VARCHAR2(5)           NOT NULL   -- 스터디 유형 코드(FK)
,CONSTRAINT USER_REG_UC_PK PRIMARY KEY(USER_CODE)
,CONSTRAINT USER_REG_UC_FK FOREIGN KEY(USER_CODE)
            REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
,CONSTRAINT USER_REG_PSQC_FK FOREIGN KEY(PW_SRCH_QUE_CODE)
            REFERENCES TBL_PW_SEARCH_QUE(PW_SRCH_QUE_CODE)
,CONSTRAINT USER_REG_IMC_FK FOREIGN KEY(INTEREST_MC_CODE)
            REFERENCES TBL_INTEREST_MC(INTEREST_MC_CODE)
,CONSTRAINT USER_REG_JMC_FK FOREIGN KEY(JOB_MC_CODE)
            REFERENCES TBL_JOB_MC(JOB_MC_CODE)
,CONSTRAINT USER_REG_STC_FK FOREIGN KEY(STUDY_TYPE_CODE)
            REFERENCES TBL_STUDY_TYPE(STUDY_TYPE_CODE)            
);  


--4. 그 다음 순서
  -- 고객센터(1:1 문의)
CREATE TABLE TBL_ASK
( ASK_CODE                    VARCHAR(20)     NOT NULL 
, USER_CODE                   VARCHAR(10)     NOT NULL 
, ASK_TITLE                     VARCHAR(300)     NOT NULL  
, ASK_CONTENT               VARCHAR(4000)     NOT NULL 
, ASK_DATE                   DATE      DEFAULT SYSDATE  NOT NULL
, ASK_ANSWER                VARCHAR(4000)
, ASK_ANSWER_DATE       DATE
, ADMIN_CODE               VARCHAR(20)
, CONSTRAINT ASK_AC_PK PRIMARY KEY(ASK_CODE)
, CONSTRAINT ASK_UC_FK FOREIGN KEY(USER_CODE)
                     REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
, CONSTRAINT ASK_HRC_FK FOREIGN KEY(ADMIN_CODE)
                     REFERENCES TBL_ADMIN(ADMIN_CODE)
);  
  -- 탈퇴 기록 및 개인정보 보관
CREATE TABLE TBL_WITHDRAWAL_INFO
(WDL_CODE       VARCHAR2(10)                        -- 탈퇴 코드(PK)
,WDL_DATE       DATE  DEFAULT SYSDATE NOT NULL      -- 탈퇴 일자
,WDL_CTG_CODE   VARCHAR2(5)   NOT NULL              -- 탈퇴 카테고리 코드(FK)
,SSN            VARCHAR2(13)  NOT NULL              -- 탈퇴자 주민번호
,USER_CODE      VARCHAR2(10)  NOT NULL              -- 사용자 코드
,WDL_REASON     VARCHAR2(200) NOT NULL              -- 탈퇴 사유
,CONSTRAINT WDL_INFO_WC_PK PRIMARY KEY(WDL_CODE)
,CONSTRAINT WDL_INFO_WCC_FK FOREIGN KEY(WDL_CTG_CODE)
            REFERENCES TBL_WITHDRAWAL_CATEGORY(WDL_CTG_CODE)
);  
  -- 경고등록
CREATE TABLE TBL_WARNING
( WARNING_CODE  VARCHAR2(15)
, WARNING_DATE  VARCHAR2(1200)  NOT NULL
, USER_CODE     VARCHAR2(10)    NOT NULL
, CONSTRAINT WARN_WC_PK PRIMARY KEY (WARNING_CODE)
, CONSTRAINT WARN_UC_FK FOREIGN KEY (USER_CODE)
  REFERENCES TBL_USER_CODE_CREATE (USER_CODE)
);  
  -- 점수 기록
CREATE TABLE TBL_SCORE
( SCORE_CODE    VARCHAR2(15)
, USER_CODE     VARCHAR2(10)                NOT NULL
, SCORE         NUMBER                      NOT NULL
, SCORE_DATE    DATE        DEFAULT SYSDATE NOT NULL
, CONSTRAINT SCORE_SC_PK PRIMARY KEY (SCORE_CODE)
, CONSTRAINT SCORE_UC_FK FOREIGN KEY (USER_CODE)
  REFERENCES TBL_USER_CODE_CREATE (USER_CODE)
);  
  -- 스터디 개설
CREATE TABLE TBL_STUDY_OPEN
( STUDY_CODE        VARCHAR2(15)
, USER_CODE         VARCHAR2(15)
, WRITE_CODE        DATE DEFAULT SYSDATE NOT NULL
, HITCOUNT          NUMBER DEFAULT 0 NOT NULL
, STUDY_TYPE_CODE   VARCHAR2(5) 
, INTEREST_MC_CODE  VARCHAR2(5)
, START_DATE        DATE NOT NULL
, END_DATE          DATE NOT NULL
, MIN_MEM_CODE       VARCHAR2(5) 
, MAX_MEM_CODE       VARCHAR2(5)
, STUDY_NAME        VARCHAR2(200) NOT NULL
, MIN_RANK          VARCHAR2(5)
, CLOSE_DATE        DATE NOT NULL
, STUDY_DESC        VARCHAR2(1200) NOT NULL
, LOC_MC_CODE       VARCHAR2(5)
, CONSTRAINT STD_OPEN_SC_PK PRIMARY KEY(STUDY_CODE)
);
-- 스터디 개설 테이블 외래키 제약 조건
ALTER TABLE TBL_STUDY_OPEN
ADD ( CONSTRAINT STD_OPEN_UC_FK FOREIGN KEY(USER_CODE)
                 REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
    , CONSTRAINT STD_OPEN_STC_FK FOREIGN KEY(STUDY_TYPE_CODE)
                 REFERENCES TBL_STUDY_TYPE(STUDY_TYPE_CODE)
    , CONSTRAINT STD_OPEN_IMC_FK FOREIGN KEY(INTEREST_MC_CODE)
                 REFERENCES TBL_INTEREST_MC(INTEREST_MC_CODE)
    , CONSTRAINT STD_OPEN_MN_FK FOREIGN KEY(MIN_MEM_CODE)
                 REFERENCES TBL_MEMNUM(MEMNUM_CODE)
    , CONSTRAINT STD_OPEN_MX_FK FOREIGN KEY(MAX_MEM_CODE)
                 REFERENCES TBL_MEMNUM(MEMNUM_CODE)
    , CONSTRAINT STD_OPEN_RK_FK FOREIGN KEY(MIN_RANK)
                 REFERENCES TBL_USER_RANK(RANK_CODE)
    , CONSTRAINT STD_OPEN_LMC_FK FOREIGN KEY(LOC_MC_CODE)
                 REFERENCES TBL_LOC_MC(LOC_MC_CODE)
);

  -- it, 기술정보공유
CREATE TABLE TBL_BOARD_INFORM
( POST_CODE         VARCHAR2(15)     --PK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, HITCOUNT          NUMBER          DEFAULT 0 NOT NULL
, TITLE             VARCHAR2(300)   NOT NULL
, CONTENT           VARCHAR2(4000)  NOT NULL
, INTEREST_MC_CODE  VARCHAR2(20)    NOT NULL --FK
, CONSTRAINT BRD_INFO_PC_PK PRIMARY KEY(POST_CODE)
, CONSTRAINT BRD_INFO_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
, CONSTRAINT BRD_INFO_IRMCC_FK FOREIGN KEY(INTEREST_MC_CODE)
             REFERENCES TBL_INTEREST_MC(INTEREST_MC_CODE)
);  
  -- 면접,코딩테스트 후기
CREATE TABLE TBL_BOARD_INTERVIEW
( POST_CODE         VARCHAR2(15)     --PK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, HITCOUNT          NUMBER          DEFAULT 0 NOT NULL
, TITLE             VARCHAR2(300)   NOT NULL
, CONTENT           VARCHAR2(4000)  NOT NULL
, INTEREST_MC_CODE  VARCHAR2(20)    NOT NULL --FK
, CONSTRAINT BRD_INTER_PC_PK PRIMARY KEY(POST_CODE)
, CONSTRAINT BRD_INTER_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
, CONSTRAINT BRD_INTER_IRMCC_FK FOREIGN KEY(INTEREST_MC_CODE)
             REFERENCES TBL_INTEREST_MC(INTEREST_MC_CODE)
); 
  -- 세미나,공모전
CREATE TABLE TBL_BOARD_SEMINAR
( POST_CODE         VARCHAR2(15)         --PK
, USER_CODE         VARCHAR2(10)        NOT NULL --FK
, WRITE_DATE        DATE                DEFAULT SYSDATE NOT NULL
, HITCOUNT          NUMBER              DEFAULT 0 NOT NULL
, TITLE             VARCHAR2(300)       NOT NULL
, CONTENT           VARCHAR2(4000)      NOT NULL
, SEMINAR_CATEGORY_CODE  VARCHAR2(20)   NOT NULL --FK
, CONSTRAINT BRD_SEMI_PC_PK PRIMARY KEY(POST_CODE)
, CONSTRAINT BRD_SEMI_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
, CONSTRAINT BRD_SEMI_SMCTC_FK FOREIGN KEY(SEMINAR_CATEGORY_CODE)
             REFERENCES TBL_SEMINAR_CATEGORY(SEMINAR_CATEGORY_CODE)
);
  -- 자유게시판
CREATE TABLE TBL_BOARD_FREE
( POST_CODE         VARCHAR2(15)     --PK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, HITCOUNT          NUMBER          DEFAULT 0 NOT NULL
, TITLE             VARCHAR2(300)   NOT NULL
, CONTENT           VARCHAR2(4000)  NOT NULL
, CONSTRAINT BRD_FREE_PC_PK PRIMARY KEY(POST_CODE)
, CONSTRAINT BRD_FREE_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
);  
  -- Q&A질문
CREATE TABLE TBL_BOARD_QUESTION
( POST_CODE         VARCHAR2(15)     --PK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, HITCOUNT          NUMBER          DEFAULT 0 NOT NULL
, TITLE             VARCHAR2(300)   NOT NULL
, CONTENT           VARCHAR2(4000)  NOT NULL
, INTEREST_MC_CODE  VARCHAR2(20)    NOT NULL --FK
, CONSTRAINT BRD_QUE_PC_PK PRIMARY KEY(POST_CODE)
, CONSTRAINT BRD_QUE_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
, CONSTRAINT BRD_QUE_IRMCC_FK FOREIGN KEY(INTEREST_MC_CODE)
             REFERENCES TBL_INTEREST_MC(INTEREST_MC_CODE)
);
 

--5. 그 다음 순서
  -- 계정 정지 등록
CREATE TABLE TBL_ACCOUNT_SUSPEND
(ACCT_SUS_CODE   VARCHAR2(10)                       -- 계정 정지 코드(PK)
,ACCT_SUS_DATE   DATE  DEFAULT SYSDATE NOT NULL     -- 계정 정지 일자
,WARNING_CODE    VARCHAR2(15) NOT NULL              -- 경고 등록 코드(FK)
,CONSTRAINT ACCT_SUS_ASC_PK PRIMARY KEY(ACCT_SUS_CODE)
,CONSTRAINT ACCT_SUS_WC_FK FOREIGN KEY(WARNING_CODE)
            REFERENCES TBL_WARNING(WARNING_CODE)
);  
  -- 진행 요일
CREATE TABLE TBL_STUDY_MEETDAY
( MEETDAY_CODE  VARCHAR2(5)
, WEEKDAY_CODE  VARCHAR2(5)
, STUDY_CODE    VARCHAR2(15)
, START_TIME    NUMBER(2) NOT NULL
, END_TIME      NUMBER(2) NOT NULL
, CONSTRAINT STD_MEETDAY_MDC_PK PRIMARY KEY(MEETDAY_CODE)
);
-- 모임 요일 테이블 제약 외래키 조건
ALTER TABLE TBL_STUDY_MEETDAY
ADD ( CONSTRAINT STD_MEETDAY_WDC_FK FOREIGN KEY(WEEKDAY_CODE)
                 REFERENCES TBL_WEEKDAY(WEEKDAY_CODE));
   
  -- 스터디 신고 등록
CREATE TABLE TBL_STUDY_ACCUSE
( ACCUSE_CODE        VARCHAR(20)     NOT NULL
, STUDY_CODE          VARCHAR(10)     NOT NULL
, USER_CODE            VARCHAR(10)     NOT NULL
, ACCUSE_DATE         DATE      DEFAULT SYSDATE  NOT NULL
, ACCUSE_REASON     VARCHAR(300)     NOT NULL
, MEM_REPORT_CTG_CODE   VARCHAR(10)     NOT NULL
, CONSTRAINT STUDY_ACCUSE_AC_PK PRIMARY KEY(ACCUSE_CODE)
, CONSTRAINT STUDY_ACCUSE_SC_FK FOREIGN KEY(STUDY_CODE)
                     REFERENCES TBL_STUDY_OPEN(STUDY_CODE)
, CONSTRAINT STUDY_ACCUSE_UC_FK FOREIGN KEY(USER_CODE)
                     REFERENCES TBL_USER_CODE_CREATE(USER_CODE)            
, CONSTRAINT STUDY_ACCUSE_MRCC_FK FOREIGN KEY(MEM_REPORT_CTG_CODE)
                     REFERENCES TBL_MEM_REPORT_CTG(MEM_REPORT_CTG_CODE)                    
);  
  -- 스터디 참여 신청
CREATE TABLE TBL_STUDY_APPLY
( APPLY_CODE    VARCHAR2(15)
, STUDY_CODE    VARCHAR2(15)                 NOT NULL
, USER_CODE     VARCHAR2(10)                 NOT NULL
, APPLY_DATE    DATE         DEFAULT SYSDATE NOT NULL
, CONSTRAINT STUDY_APPLY_AC_PK PRIMARY KEY (APPLY_CODE)
, CONSTRAINT STUDY_APPLY_SC_FK FOREIGN KEY (STUDY_CODE)
  REFERENCES TBL_STUDY_OPEN (STUDY_CODE)
, CONSTRAINT STUDY_APPLY_UC_FK FOREIGN KEY (USER_CODE)
  REFERENCES TBL_USER_CODE_CREATE (USER_CODE)
);

  -- it,기술정보 댓글 등록
CREATE TABLE TBL_COMMENT_INFORM
( COMMENT_CODE      VARCHAR2(10)                --PK
, POST_CODE         VARCHAR2(15)    NOT NULL    --FK
, COMMENTS          VARCHAR2(800)   NOT NULL
, USER_CODE         VARCHAR2(10)    NOT NULL    --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT CMT_INFO_CC_PK PRIMARY KEY(COMMENT_CODE)
, CONSTRAINT CMT_INFO_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_INFORM(POST_CODE)
, CONSTRAINT CMT_INFO_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
); 
  -- 면접, 코딩테스트 댓글 등록
CREATE TABLE TBL_COMMENT_INTERVIEW
( COMMENT_CODE      VARCHAR2(10)                --PK
, POST_CODE         VARCHAR2(15)    NOT NULL    --FK
, COMMENTS          VARCHAR2(800)   NOT NULL
, USER_CODE         VARCHAR2(10)    NOT NULL    --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT CMT_INTER_CC_PK PRIMARY KEY(COMMENT_CODE)
, CONSTRAINT CMT_INTER_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_INTERVIEW(POST_CODE)
, CONSTRAINT CMT_INTER_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
);

  -- 세미나, 공모전 댓글 등록
CREATE TABLE TBL_COMMENT_SEMINAR
( COMMENT_CODE      VARCHAR2(10)                --PK
, POST_CODE         VARCHAR2(15)    NOT NULL    --FK
, COMMENTS          VARCHAR2(800)   NOT NULL
, USER_CODE         VARCHAR2(10)    NOT NULL    --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT CMT_SEMI_CC_PK PRIMARY KEY(COMMENT_CODE)
, CONSTRAINT CMT_SEMI_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_SEMINAR(POST_CODE)
, CONSTRAINT CMT_SEMI_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
);  
  -- 자유게시판 댓글 등록
CREATE TABLE TBL_COMMENT_FREE
( COMMENT_CODE      VARCHAR2(10)        --PK
, POST_CODE         VARCHAR2(15)    NOT NULL    --FK
, COMMENTS          VARCHAR2(800)   NOT NULL
, USER_CODE         VARCHAR2(10)    NOT NULL    --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT CMT_FREE_CC_PK PRIMARY KEY(COMMENT_CODE)
, CONSTRAINT CMT_FREE_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_FREE(POST_CODE)
, CONSTRAINT CMT_FREE_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
); 
  -- Q&A 질문 댓글 등록
  CREATE TABLE TBL_COMMENT_QUESTION
( COMMENT_CODE      VARCHAR2(10)        --PK
, POST_CODE         VARCHAR2(15)    NOT NULL    --FK
, COMMENTS          VARCHAR2(800)   NOT NULL
, USER_CODE         VARCHAR2(10)    NOT NULL    --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT CMT_QUE_CC_PK PRIMARY KEY(COMMENT_CODE)
, CONSTRAINT CMT_QUE_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_QUESTION(POST_CODE)
, CONSTRAINT CMT_QUE_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
);
  -- Q&A 답변
CREATE TABLE TBL_BOARD_ANSWER
( POST_CODE         VARCHAR2(15)     --PK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, HITCOUNT          NUMBER          DEFAULT 0 NOT NULL
, TITLE             VARCHAR2(300)   NOT NULL
, CONTENT           VARCHAR2(4000)  NOT NULL
, INTEREST_MC_CODE  VARCHAR2(20)    NOT NULL --FK
, CONSTRAINT BRD_AWR_PC_PK PRIMARY KEY(POST_CODE)
, CONSTRAINT BRD_AWR_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
, CONSTRAINT BRD_AWR_IRMCC_FK FOREIGN KEY(INTEREST_MC_CODE)
             REFERENCES TBL_INTEREST_MC(INTEREST_MC_CODE)
); 
  -- It, 기술정보 추천/비추천 등록
CREATE TABLE TBL_REC_INFORM
( REC_CODE          VARCHAR2(20)    --PK
, POST_CODE         VARCHAR2(15)    NOT NULL --FK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, REC_CHECK         NUMBER          NOT NULL
, REC_DATE          DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT REC_INFO_RC_PK PRIMARY KEY(REC_CODE)
, CONSTRAINT REC_INFO_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_INFORM(POST_CODE)
, CONSTRAINT REC_INFO_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
);  
  -- 면접, 코딩테스트 추천/비추천 등록
CREATE TABLE TBL_REC_INTERVIEW
( REC_CODE          VARCHAR2(20)    --PK
, POST_CODE         VARCHAR2(15)    NOT NULL --FK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, REC_CHECK         NUMBER          NOT NULL
, REC_DATE          DATE            DEFAULT SYSDATE NOT NULL    
, CONSTRAINT REC_INTER_RC_PK PRIMARY KEY(REC_CODE)
, CONSTRAINT REC_INTER_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_INTERVIEW(POST_CODE)
, CONSTRAINT REC_INTER_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
);  
  -- 세미나,공모전 추천/비추천 등록
CREATE TABLE TBL_REC_SEMINAR
( REC_CODE          VARCHAR2(20)    --PK
, POST_CODE         VARCHAR2(15)    NOT NULL --FK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, REC_CHECK         NUMBER          NOT NULL
, REC_DATE          DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT REC_SEMI_RC_PK PRIMARY KEY(REC_CODE)
, CONSTRAINT REC_SEMI_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_SEMINAR(POST_CODE)
, CONSTRAINT REC_SEMI_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
);  
  -- 자유게시판 추천/비추천 등록
CREATE TABLE TBL_REC_FREE
( REC_CODE          VARCHAR2(20)    --PK
, POST_CODE         VARCHAR2(15)    NOT NULL --FK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, REC_CHECK         NUMBER          NOT NULL
, REC_DATE          DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT REC_FREE_RC_PK PRIMARY KEY(REC_CODE)
, CONSTRAINT REC_FREE_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_FREE(POST_CODE)
, CONSTRAINT REC_FREE_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
);  
  -- Q&A 질문 추천/비추천 등록
CREATE TABLE TBL_REC_QUESTION
( REC_CODE          VARCHAR2(20)    --PK
, POST_CODE         VARCHAR2(15)    --FK
, USER_CODE         VARCHAR2(10)    --FK
, REC_CHECK         NUMBER
, REC_DATE          DATE
, CONSTRAINT REC_QUE_RC_PK PRIMARY KEY(REC_CODE)
, CONSTRAINT REC_QUE_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_QUESTION(POST_CODE)
, CONSTRAINT REC_QUE_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
);  
  -- 기술정보공유 신고 등록
CREATE TABLE TBL_REPORT_REG_INFORM
( POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --PK
, POST_CODE             VARCHAR2(15)    NOT NULL --FK
, USER_CODE             VARCHAR2(10)    NOT NULL --FK
, REPORT_DATE           DATE            DEFAULT SYSDATE NOT NULL
, REPORT_REASON         VARCHAR2(400)   NOT NULL
, POST_REPORT_CTG_CODE  VARCHAR2(10)    NOT NULL --FK
, CONSTRAINT RPT_REG_INFO_PRC_PK PRIMARY KEY(POST_REPORT_CODE)
, CONSTRAINT RPT_REG_INFO_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_INFORM(POST_CODE)
, CONSTRAINT RPT_REG_INFO_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
, CONSTRAINT RPT_REG_INFO_PRCC_FK FOREIGN KEY(POST_REPORT_CTG_CODE)
             REFERENCES TBL_POST_REPORT_CTG(POST_REPORT_CTG_CODE)
);  
  -- 면접,코딩테스트 신고 등록
CREATE TABLE TBL_REPORT_REG_INTERVIEW
( POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --PK
, POST_CODE             VARCHAR2(15)    NOT NULL --FK
, USER_CODE             VARCHAR2(10)    NOT NULL --FK
, REPORT_DATE           DATE            DEFAULT SYSDATE NOT NULL
, REPORT_REASON         VARCHAR2(400)   NOT NULL
, POST_REPORT_CTG_CODE  VARCHAR2(10)    NOT NULL --FK
, CONSTRAINT RPT_REG_INTER_PRC_PK PRIMARY KEY(POST_REPORT_CODE)
, CONSTRAINT RPT_REG_INTER_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_INTERVIEW(POST_CODE)
, CONSTRAINT RPT_REG_INTER_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
, CONSTRAINT RPT_REG_INTER_PRCC_FK FOREIGN KEY(POST_REPORT_CTG_CODE)
             REFERENCES TBL_POST_REPORT_CTG(POST_REPORT_CTG_CODE)
);  
  -- 세미나, 공모전 신고 등록
CREATE TABLE TBL_REPORT_REG_SEMINAR
( POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --PK
, POST_CODE             VARCHAR2(15)    NOT NULL --FK
, USER_CODE             VARCHAR2(10)    NOT NULL --FK
, REPORT_DATE           DATE            DEFAULT SYSDATE NOT NULL
, REPORT_REASON         VARCHAR2(400)   NOT NULL
, POST_REPORT_CTG_CODE  VARCHAR2(10)    NOT NULL --FK
, CONSTRAINT RPT_REG_SEMI_PRC_PK PRIMARY KEY(POST_REPORT_CODE)
, CONSTRAINT RPT_REG_SEMI_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_SEMINAR(POST_CODE)
, CONSTRAINT RPT_REG_SEMI_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
, CONSTRAINT RPT_REG_SEMI_PRCC_FK FOREIGN KEY(POST_REPORT_CTG_CODE)
             REFERENCES TBL_POST_REPORT_CTG(POST_REPORT_CTG_CODE)
);  
  -- 자유게시판 신고 등록
CREATE TABLE TBL_REPORT_REG_FREE
( POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --PK
, POST_CODE             VARCHAR2(15)    NOT NULL --FK
, USER_CODE             VARCHAR2(10)    NOT NULL --FK
, REPORT_DATE           DATE            DEFAULT SYSDATE NOT NULL
, REPORT_REASON         VARCHAR2(400)   NOT NULL
, POST_REPORT_CTG_CODE  VARCHAR2(10)    NOT NULL --FK
, CONSTRAINT RPT_REG_FREE_PRC_PK PRIMARY KEY(POST_REPORT_CODE)
, CONSTRAINT RPT_REG_FREE_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_FREE(POST_CODE)
, CONSTRAINT RPT_REG_FREE_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
, CONSTRAINT RPT_REG_FREE_PRCC_FK FOREIGN KEY(POST_REPORT_CTG_CODE)
             REFERENCES TBL_POST_REPORT_CTG(POST_REPORT_CTG_CODE)
);  
  -- Q&A질문 신고 등록
CREATE TABLE TBL_REPORT_REG_QUESTION
( POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --PK
, POST_CODE             VARCHAR2(15)    NOT NULL --FK
, USER_CODE             VARCHAR2(10)    NOT NULL --FK
, REPORT_DATE           DATE            DEFAULT SYSDATE NOT NULL
, REPORT_REASON         VARCHAR2(400)   NOT NULL
, POST_REPORT_CTG_CODE  VARCHAR2(10)    NOT NULL --FK
, CONSTRAINT RPT_REG_QUE_PRC_PK PRIMARY KEY(POST_REPORT_CODE)
, CONSTRAINT RPT_REG_QUE_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_QUESTION(POST_CODE)
, CONSTRAINT RPT_REG_QUE_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
, CONSTRAINT RPT_REG_QUE_PRCC_FK FOREIGN KEY(POST_REPORT_CTG_CODE)
             REFERENCES TBL_POST_REPORT_CTG(POST_REPORT_CTG_CODE)
);  
  -- Q&A답변 신고 등록
CREATE TABLE TBL_REPORT_REG_ANSWER
( POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --PK
, POST_CODE             VARCHAR2(15)    NOT NULL --FK
, USER_CODE             VARCHAR2(10)    NOT NULL --FK
, REPORT_DATE           DATE            DEFAULT SYSDATE NOT NULL
, REPORT_REASON         VARCHAR2(400)   NOT NULL
, POST_REPORT_CTG_CODE  VARCHAR2(10)    NOT NULL --FK
, CONSTRAINT RPT_REG_AWR_PRC_PK PRIMARY KEY(POST_REPORT_CODE)
, CONSTRAINT RPT_REG_AWR_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_ANSWER(POST_CODE)
, CONSTRAINT RPT_REG_AWR_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
, CONSTRAINT RPT_REG_AWR_PRCC_FK FOREIGN KEY(POST_REPORT_CTG_CODE)
             REFERENCES TBL_POST_REPORT_CTG(POST_REPORT_CTG_CODE)
);  


--6. 그 다음 순서
  -- 스터디 신고 처리
CREATE TABLE TBL_STUDY_ACCUSE_HANDLE
( ACCUSE_HANDLE_CODE        VARCHAR(20)     NOT NULL
, ACCUSE_CODE                    VARCHAR(20)     NOT NULL
, HANDLE_RESULT_CODE         VARCHAR(10)
, ACCUSE_HANDLE_DATE         DATE
, CONSTRAINT STUDY_ACCUSE_HANDLE_AHC_PK PRIMARY KEY(ACCUSE_HANDLE_CODE)
, CONSTRAINT STUDY_ACCUSE_HANDLE_AC_FK FOREIGN KEY(ACCUSE_CODE)
                     REFERENCES TBL_STUDY_ACCUSE(ACCUSE_CODE)
, CONSTRAINT STUDY_ACCUSE_HANDLE_HRC_FK FOREIGN KEY(HANDLE_RESULT_CODE)
                     REFERENCES TBL_HANDLE_RESULT(HANDLE_RESULT_CODE)  
);  
  -- 스터디 취소 처리
CREATE TABLE TBL_STUDY_CANCEL
( CANCEL_CODE   VARCHAR2(15)
, APPLY_CODE    VARCHAR2(15)                 NOT NULL
, CANCEL_DATE   DATE         DEFAULT SYSDATE NOT NULL
, CONSTRAINT STUDY_CANCEL_CC_PK PRIMARY KEY (CANCEL_CODE)
, CONSTRAINT STUDY_CANCEL_AC_FK FOREIGN KEY (APPLY_CODE)
  REFERENCES TBL_STUDY_APPLY (APPLY_CODE)
);
  
  -- 스터디 진행
CREATE TABLE TBL_STUDY_PARTICIPANT
( PARTI_CODE    VARCHAR2(15)
, APPLY_CODE    VARCHAR2(15)    NOT NULL
, POSITION_CODE VARCHAR2(5)     NOT NULL
, CONSTRAINT STUDY_PARTI_PC_PK PRIMARY KEY (PARTI_CODE)
, CONSTRAINT STUDY_PARTI_AC_FK FOREIGN KEY (APPLY_CODE)
  REFERENCES TBL_STUDY_APPLY (APPLY_CODE)
, CONSTRAINT STUDY_PARTI_PC_FK FOREIGN KEY (POSITION_CODE)
  REFERENCES TBL_STUDY_POSITION (POSITION_CODE)
);  
  -- Q&A 답변 댓글 등록
CREATE TABLE TBL_COMMENT_ANSWER
( COMMENT_CODE      VARCHAR2(10)        --PK
, POST_CODE         VARCHAR2(15)    NOT NULL    --FK
, COMMENTS          VARCHAR2(800)   NOT NULL
, USER_CODE         VARCHAR2(10)    NOT NULL    --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT CMT_AWR_CC_PK PRIMARY KEY(COMMENT_CODE)
, CONSTRAINT CMT_AWR_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_ANSWER(POST_CODE)
, CONSTRAINT CMT_AWR_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
);  
  -- Q&A 답변 추천/비추천 등록
CREATE TABLE TBL_REC_ANSWER
( REC_CODE          VARCHAR2(20)    NOT NULL --PK
, POST_CODE         VARCHAR2(15)    NOT NULL --FK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, REC_CHECK         NUMBER          NOT NULL
, REC_DATE          DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT REC_AWR_RC_PK PRIMARY KEY(REC_CODE)
, CONSTRAINT REC_AWR_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_ANSWER(POST_CODE)
, CONSTRAINT REC_AWR_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
);  
  -- 기술정보공유 신고 처리
CREATE TABLE TBL_REPORT_HANDLE_INFORM
( REPORT_HANDLE_CODE    VARCHAR2(15)    NOT NULL --PK
, POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --FK
, HANDLE_RESULT_CODE    VARCHAR2(5)              --FK
, HANDLE_DATE           DATE            
, CONSTRAINT RPT_HLE_INFO_RHC_PK PRIMARY KEY(REPORT_HANDLE_CODE)
, CONSTRAINT RPT_HLE_INFO_PRC_FK FOREIGN KEY(POST_REPORT_CODE)
             REFERENCES TBL_REPORT_REG_INFORM(POST_REPORT_CODE)
, CONSTRAINT RPT_HLE_INFO_HR_FK FOREIGN KEY(HANDLE_RESULT_CODE)
             REFERENCES TBL_HANDLE_RESULT(HANDLE_RESULT_CODE)         
);  
  -- 면접,코딩테스트 신고 처리
CREATE TABLE TBL_REPORT_HANDLE_INTERVIEW
( REPORT_HANDLE_CODE    VARCHAR2(15)    NOT NULL --PK
, POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --FK
, HANDLE_RESULT_CODE    VARCHAR2(5)              --FK
, HANDLE_DATE           DATE 
, CONSTRAINT RPT_HLE_INTER_RHC_PK PRIMARY KEY(REPORT_HANDLE_CODE)
, CONSTRAINT RPT_HLE_INTER_PRC_FK FOREIGN KEY(POST_REPORT_CODE)
             REFERENCES TBL_REPORT_REG_INTERVIEW(POST_REPORT_CODE)
, CONSTRAINT RPT_HLE_INTER_HR_FK FOREIGN KEY(HANDLE_RESULT_CODE)
             REFERENCES TBL_HANDLE_RESULT(HANDLE_RESULT_CODE)         
);  
  -- 세미나, 공모전 신고 처리
CREATE TABLE TBL_REPORT_HANDLE_SEMINAR
( REPORT_HANDLE_CODE    VARCHAR2(15)    NOT NULL --PK
, POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --FK
, HANDLE_RESULT_CODE    VARCHAR2(5)              --FK
, HANDLE_DATE           DATE 
, CONSTRAINT RPT_HLE_SEMI_RHC_PK PRIMARY KEY(REPORT_HANDLE_CODE)
, CONSTRAINT RPT_HLE_SEMI_PRC_FK FOREIGN KEY(POST_REPORT_CODE)
             REFERENCES TBL_REPORT_REG_SEMINAR(POST_REPORT_CODE)
, CONSTRAINT RPT_HLE_SEMI_HR_FK FOREIGN KEY(HANDLE_RESULT_CODE)
             REFERENCES TBL_HANDLE_RESULT(HANDLE_RESULT_CODE)         
);  
  -- 자유게시판 신고 처리
CREATE TABLE TBL_REPORT_HANDLE_FREE
( REPORT_HANDLE_CODE    VARCHAR2(15)    NOT NULL --PK
, POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --FK
, HANDLE_RESULT_CODE    VARCHAR2(5)              --FK
, HANDLE_DATE           DATE 
, CONSTRAINT RPT_HLE_FREE_RHC_PK PRIMARY KEY(REPORT_HANDLE_CODE)
, CONSTRAINT RPT_HLE_FREE_PRC_FK FOREIGN KEY(POST_REPORT_CODE)
             REFERENCES TBL_REPORT_REG_FREE(POST_REPORT_CODE)
, CONSTRAINT RPT_HLE_FREE_HR_FK FOREIGN KEY(HANDLE_RESULT_CODE)
             REFERENCES TBL_HANDLE_RESULT(HANDLE_RESULT_CODE)         
);  
  -- Q&A질문 신고 처리
CREATE TABLE TBL_REPORT_HANDLE_QUESTION
( REPORT_HANDLE_CODE    VARCHAR2(15)    NOT NULL --PK
, POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --FK
, HANDLE_RESULT_CODE    VARCHAR2(5)              --FK
, HANDLE_DATE           DATE 
, CONSTRAINT RPT_HLE_QUE_RHC_PK PRIMARY KEY(REPORT_HANDLE_CODE)
, CONSTRAINT RPT_HLE_QUE_PRC_FK FOREIGN KEY(POST_REPORT_CODE)
             REFERENCES TBL_REPORT_REG_QUESTION(POST_REPORT_CODE)
, CONSTRAINT RPT_HLE_QUE_HR_FK FOREIGN KEY(HANDLE_RESULT_CODE)
             REFERENCES TBL_HANDLE_RESULT(HANDLE_RESULT_CODE)         
);  
  -- Q&A답변 신고 처리
CREATE TABLE TBL_REPORT_HANDLE_ANSWER
( REPORT_HANDLE_CODE    VARCHAR2(15)    NOT NULL --PK
, POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --FK
, HANDLE_RESULT_CODE    VARCHAR2(5)              --FK
, HANDLE_DATE           DATE 
, CONSTRAINT RPT_HLE_AWR_RHC_PK PRIMARY KEY(REPORT_HANDLE_CODE)
, CONSTRAINT RPT_HLE_AWR_PRC_FK FOREIGN KEY(POST_REPORT_CODE)
             REFERENCES TBL_REPORT_REG_ANSWER(POST_REPORT_CODE)
, CONSTRAINT RPT_HLE_AWR_HR_FK FOREIGN KEY(HANDLE_RESULT_CODE)
             REFERENCES TBL_HANDLE_RESULT(HANDLE_RESULT_CODE)         
);  


--7. 그 다음 순서
  -- 스터디 컨텐츠 등록
CREATE TABLE TBL_STUDY_CONTENT
( CONTENT_CODE  VARCHAR2(15)
, PARTI_CODE    VARCHAR2(15)                 NOT NULL
, WRITE_DATE    DATE         DEFAULT SYSDATE NOT NULL
, HITCOUNT      NUMBER       DEFAULT 0       NOT NULL
, TITLE         VARCHAR2(100)                NOT NULL
, CONTENT       VARCHAR2(4000)               NOT NULL
, CONSTRAINT STUDY_CONTENT_CC_PK PRIMARY KEY (CONTENT_CODE)
, CONSTRAINT STUDY_CONTENT_PC_FK FOREIGN KEY (PARTI_CODE)
  REFERENCES TBL_STUDY_PARTICIPANT (PARTI_CODE)
);  
  -- 스터디 평가 등록
CREATE TABLE TBL_STUDY_ASSESS
( ASSESS_CODE   VARCHAR2(15)                 NOT NULL
, PARTI_CODE    VARCHAR2(15)                 NOT NULL
, SCORE         NUMBER                       NOT NULL
, ASSESS_DATE   DATE         DEFAULT SYSDATE NOT NULL
, CONSTRAINT STUDY_ASSESS_AC_PK PRIMARY KEY (ASSESS_CODE)
, CONSTRAINT STUDY_ASSESS_PC_FK FOREIGN KEY (PARTI_CODE)
  REFERENCES TBL_STUDY_PARTICIPANT (PARTI_CODE)
);
  -- 출석부
CREATE TABLE TBL_STUDY_ATTEND
( ATTEND_CODE   VARCHAR2(15)
, PARTI_CODE    VARCHAR2(15)                 NOT NULL
, ATTEND_DATE   DATE         DEFAULT SYSDATE NOT NULL
, CLOCK_IN      TIMESTAMP    DEFAULT SYSDATE NOT NULL
, CLOCK_OUT     TIMESTAMP 
, CONSTRAINT STUDY_ATTEND_AC_PK PRIMARY KEY (ATTEND_CODE)
, CONSTRAINT STUDY_ATTEND_PC_FK FOREIGN KEY (PARTI_CODE)
  REFERENCES TBL_STUDY_PARTICIPANT (PARTI_CODE)
);  
  -- 스터디원 평가 등록
CREATE TABLE TBL_STUDY_INTERASSESS
( INTERASSESS_CODE         VARCHAR2(15)                
, PARTI_ASSESS_CODE        VARCHAR2(15)                 NOT NULL
, RESP_CODE                VARCHAR2(5)                  NOT NULL
, ITEM_CODE                VARCHAR2(5)                  NOT NULL
, PARTI_ASSESSED_CODE      VARCHAR2(15)                 NOT NULL
, INTERASSESS_DATE  DATE         DEFAULT SYSDATE NOT NULL
, CONSTRAINT STUDY_ITASS_IC_PK PRIMARY KEY (INTERASSESS_CODE)
, CONSTRAINT STUDY_ITASS_PAC_FK FOREIGN KEY (PARTI_ASSESS_CODE)
  REFERENCES TBL_STUDY_PARTICIPANT (PARTI_CODE)
, CONSTRAINT STUDY_ITASS_RC_FK FOREIGN KEY (RESP_CODE)
  REFERENCES TBL_STUDY_ASSESS_RESP (RESP_CODE)
, CONSTRAINT STUDY_ITASS_IC_FK FOREIGN KEY (ITEM_CODE)
  REFERENCES TBL_STUDY_ASSESS_ITEM (ITEM_CODE)
, CONSTRAINT STUDY_ITASS_PACD_FK FOREIGN KEY (PARTI_ASSESSED_CODE)
  REFERENCES TBL_STUDY_PARTICIPANT (PARTI_CODE)
);
  
  -- 스터디원 신고 등록
CREATE TABLE TBL_MEM_REPORT_REG
( MEM_REPORT_REG_CODE   VARCHAR2(12)
, PARTI_REPORT_CODE     VARCHAR2(12) NOT NULL
, REPORT_REG_DATE       DATE    DEFAULT SYSDATE NOT NULL
, MEM_REPORT_CTG_CODE   VARCHAR2(3) NOT NULL
, REPORT_REG_REASON     VARCHAR2(300)
, PARTI_REPORTED_CODE   VARCHAR2(12)    NOT NULL
, CONSTRAINT MEM_REP_REG_MRRC_PK PRIMARY KEY(MEM_REPORT_REG_CODE)
, CONSTRAINT MEM_REP_REG_PRC_FK FOREIGN KEY(PARTI_REPORT_CODE)
            REFERENCES TBL_STUDY_PARTICIPANT(PARTI_CODE)
, CONSTRAINT MEM_REP_REG_MRCC_FK FOREIGN KEY(MEM_REPORT_CTG_CODE)
            REFERENCES TBL_MEM_REPORT_CTG(MEM_REPORT_CTG_CODE)
, CONSTRAINT MEM_REP_REG_PRDC_FK FOREIGN KEY(PARTI_REPORTED_CODE)
            REFERENCES TBL_STUDY_PARTICIPANT(PARTI_CODE)
);  

  -- 내보내기 등록
CREATE TABLE TBL_MEM_KICK_REG
( MEM_KICK_REG_CODE     VARCHAR2(12)
, PARTI_KICKED_CODE     VARCHAR2(12) NOT NULL
, PARTI_KICK_CODE       VARCHAR2(12) NOT NULL
, MEM_KICK_REG_DATE     DATE DEFAULT SYSDATE NOT NULL
, CONSTRAINT MEM_KICK_REG_MKRC_PK PRIMARY KEY(MEM_KICK_REG_CODE)
, CONSTRAINT MEM_KICK_REG_PKDC_FK FOREIGN KEY(PARTI_KICKED_CODE)
            REFERENCES TBL_STUDY_PARTICIPANT(PARTI_CODE)
, CONSTRAINT MEM_KICK_REG_PKC_FK FOREIGN KEY(PARTI_KICK_CODE)
            REFERENCES TBL_STUDY_PARTICIPANT(PARTI_CODE)
);  


--8. 그 다음 순서
  -- 외출 등록
CREATE TABLE TBL_STUDY_STEPOUT
( ATTEND_CODE   VARCHAR2(15)
, CLOCK_IN      TIMESTAMP   DEFAULT SYSDATE NOT NULL
, CLOCK_OUT     TIMESTAMP 
, CONSTRAINT STUDY_STEPOUT_AC_PK PRIMARY KEY (ATTEND_CODE)
, CONSTRAINT STUDY_STEPOUT_AC_FK FOREIGN KEY (ATTEND_CODE)
  REFERENCES TBL_STUDY_ATTEND (ATTEND_CODE)
);  
  -- 스터디 일정 관리
CREATE TABLE TBL_SCHEDULE
( ATTEND_CODE   VARCHAR2(15)
, SCHEDULE      VARCHAR2(1200)
, CONSTRAINT SCHEDULE_AC_PK PRIMARY KEY (ATTEND_CODE)
, CONSTRAINT SCHEDULE_AC_FK FOREIGN KEY (ATTEND_CODE)
  REFERENCES TBL_STUDY_ATTEND (ATTEND_CODE)
);  
  -- 스터디원 신고 처리
CREATE TABLE TBL_MEM_REPORT_HANDLE
( MEM_REPORT_HANDLE_CODE    VARCHAR2(12)
, MEM_REPORT_REG_CODE       VARCHAR2(12) NOT NULL
, HANDLE_RESULT             VARCHAR2(3) NOT NULL
, HANDEL_DATE               DATE DEFAULT SYSDATE NOT NULL
, CONSTRAINT MEM_REP_HDL_MRHC_PK PRIMARY KEY(MEM_REPORT_HANDLE_CODE)
, CONSTRAINT MEM_REP_HDL_MRRC_FK FOREIGN KEY(MEM_REPORT_REG_CODE)
            REFERENCES TBL_MEM_REPORT_REG(MEM_REPORT_REG_CODE)
, CONSTRAINT MEM_REP_HDL_HR_FK FOREIGN KEY(HANDLE_RESULT)
            REFERENCES TBL_MEM_REPORT_HANDLE_RESULT(MEM_REPORT_HANDLE_RESULT_CODE)
);  
  -- 내보내기 처리
CREATE TABLE TBL_MEM_KICK_HANDLE
( MEM_KICK_HANDLE_CODE VARCHAR2(12)
, MEM_KICK_REG_CODE     VARCHAR2(12) NOT NULL
, MEM_KICK_HANDLE_DATE  DATE DEFAULT SYSDATE NOT NULL
, CONSTRAINT MEM_KICK_HDL_MKHC_PK PRIMARY KEY(MEM_KICK_HANDLE_CODE)
, CONSTRAINT MEM_KICK_HDL_MKRC_FK FOREIGN KEY(MEM_KICK_REG_CODE)
            REFERENCES TBL_MEM_KICK_REG(MEM_KICK_REG_CODE)
);  