--○ 스터디 신고 등록 테이블
INSERT INTO TBL_STUDY_ACCUSE(ACCUSE_CODE, STUDY_CODE, USER_CODE
, ACCUSE_DATE, ACCUSE_REASON, MEM_REPORT_CTG_CODE)
VALUES('AC'||STUDY_ACC_SEQ.NEXTVAL, 'SC1', 'UC1', SYSDATE , '불건전', 'MR1');

--○ 스터디 신고처리
INSERT INTO TBL_STUDY_ACCUSE_HANDLE(ACCUSE_HANDLE_CODE, ACCUSE_CODE
, HANDLE_RESULT_CODE, ACCUSE_HANDLE_DATE)
VALUES('AH'||STUDY_ACC_HAN_SEQ.NEXTVAL, 'SA1', 'HR1', SYSDATE);

--○ 스터디 경고 등록
INSERT INTO TBL_STUDY_WARNING(WARNING_CODE, ACCUSE_HANDLE_CODE
, WARNING_DATE)
VALUES('SW'||STUDY_WAR_SEQ.NEXTVAL, 'AH1', SYSDATE);

--○ 욕설 테이블
INSERT INTO TBL_CURSE(CURSE_CODE, CURSE_KIND)
VALUES('CS'||CURSE_SEQ.NEXTVAL, '개새끼');

--○ 고객센터(1:1문의) 
INSERT INTO TBL_ASK(ASK_CODE, USER_CODE, ASK_TITLE
, ASK_CONTENT, ASK_DATE, ASK_ANSWER, ASK_ANSWER_DATE, ADMIN_CODE)
VALUES('AS'||ASK_SEQ.NEXTVAL, 'UC1', '스터디문의','스터디관려해서...', SYSDATE , '답변드립니다.',SYSDATE, 'AD1');

--○ 고객센터(공지사항)
INSERT INTO TBL_NOTICE(NOTICE_CODE, NOTICE_DATE, NOTICE_TITLE
, NOTICE_CONTENT, ADMIN_CODE, HITCOUNT)
VALUES('NT'||NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항1', '공지내용' , 'AD1', 0);

--○ 관리자
INSERT INTO TBL_ADMIN(ADMIN_CODE, ADMIN_ID,ADMIN_PW)
VALUES('AD'||ADMIN_SEQ.NEXTVAL, '@ADMIN1','java006$');
INSERT INTO TBL_ADMIN(ADMIN_CODE, ADMIN_ID,ADMIN_PW)
VALUES('AD'||ADMIN_SEQ.NEXTVAL, '@ADMIN2','java006$');
--==>> 1 행 이(가) 삽입되었습니다. * 2
