--■ 테이블 INSERT 구문 ■--


DESC TBL_BOARD_INFORM;

--○ IT기술정보공유 테이블
INSERT INTO TBL_BOARD_INFORM(POST_CODE, USER_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT, INTEREST_MC_CODE) 
VALUES ('BI'||BOARD_INFORM_SEQ.NEXTVAL, 'UC1', DEFAULT, DEFAULT, '안녕하세요', '파이널 프로젝트 4조 본문입니다.', 'IM1');  


--○ 면접/코딩테스트 후기 테이블
INSERT INTO TBL_BOARD_INTERVIEW(POST_CODE, USER_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT, INTEREST_MC_CODE) 
VALUES ('BV'||BOARD_INTERVIEW_SEQ.NEXTVAL, 'UC1', DEFAULT, DEFAULT, '안녕하세요', '파이널 프로젝트 4조 본문입니다.', 'IM1');  


--○ 세미나 및 공모전 테이블
INSERT INTO TBL_BOARD_SEMINAR(POST_CODE, USER_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT, SEMINAR_CATEGORY_CODE) 
VALUES ('BS'||BOARD_SEMINAR_SEQ.NEXTVAL, 'UC1', DEFAULT, DEFAULT, '안녕하세요', '파이널 프로젝트 4조 본문입니다.', 'IM1');  


--○ 자유게시판 테이블
INSERT INTO TBL_BOARD_FREE(POST_CODE, USER_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT) 
VALUES ('BF'||BOARD_FREE_SEQ.NEXTVAL, 'UC1', DEFAULT, DEFAULT, '안녕하세요', '파이널 프로젝트 4조 본문입니다.');  


--○ Q&A 질문 테이블
INSERT INTO TBL_BOARD_QUESTION(POST_CODE, USER_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT, INTEREST_MC_CODE) 
VALUES ('BQ'||BOARD_QUESTION_SEQ.NEXTVAL, 'UC1', DEFAULT, DEFAULT, '안녕하세요', '파이널 프로젝트 4조 본문입니다.', 'IM1');  


--○ Q&A 답변 테이블
INSERT INTO TBL_BOARD_ANSWER(POST_CODE, USER_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT, INTEREST_MC_CODE) 
VALUES ('BA'||BOARD_ANSWER_SEQ.NEXTVAL, 'UC1', DEFAULT, DEFAULT, '안녕하세요', '파이널 프로젝트 4조 본문입니다.', 'IM1');  


--○ 스터디 후기 테이블
INSERT INTO TBL_BOARD_STUDYREVIEW(POST_CODE, PARTI_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT, INTEREST_MC_CODE) 
VALUES ('BR'||BOARD_STUDYREVIEW_SEQ.NEXTVAL, 'PT1', DEFAULT, DEFAULT, '안녕하세요', '파이널 프로젝트 4조 본문입니다.', 'IM1');  




--○ IT기술정보공유 댓글 테이블
INSERT INTO TBL_COMMENT_INFORM(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CI'||COMMENT_INFORM_SEQ.NEXTVAL, 'PC1', '좋은 글이네요', 'UC1', DEFAULT);  


--○ 면접 및 코딩테스트 후기 댓글 테이블
INSERT INTO TBL_COMMENT_INTERVIEW(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CC'||COMMENT_INTERVIEW_SEQ.NEXTVAL, 'PC1', '좋은 글이네요', 'UC1', DEFAULT); 

--○ 세미나 및 공모전 댓글 테이블
INSERT INTO TBL_COMMENT_SEMINAR(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CS'||COMMENT_SEMINAR_SEQ.NEXTVAL, 'PC1', '좋은 글이네요', 'UC1', DEFAULT); 


--○ 자유게시판 댓글 테이블
INSERT INTO TBL_COMMENT_FREE(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CF'||COMMENT_FREE_SEQ.NEXTVAL, 'PC1', '좋은 글이네요', 'UC1', DEFAULT); 

--○ Q&A 질문 댓글 테이블
INSERT INTO TBL_COMMENT_QUESTION(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CQ'||COMMENT_QUESTION_SEQ.NEXTVAL, 'PC1', '좋은 글이네요', 'UC1', DEFAULT); 


--○ Q&A 답변 댓글 테이블
INSERT INTO TBL_COMMENT_ANSWER(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CA'||COMMENT_ANSWER_SEQ.NEXTVAL, 'PC1', '좋은 글이네요', 'UC1', DEFAULT); 


--○ 스터디 후기 댓글 테이블
INSERT INTO TBL_COMMENT_STUDYREVIEW(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CR'||COMMENT_STUDYREVIEW_SEQ.NEXTVAL, 'PC1', '좋은 글이네요', 'UC1', DEFAULT); 






--○ IT기술정보공유 추천/비추천 테이블
INSERT INTO TBL_REC_INFORM(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RI'||REC_INFORM_SEQ.NEXTVAL, 'PC1', 'UC1', 1, DEFAULT); 


--○ 세미나 및 공모전 추천/비추천 테이블
INSERT INTO TBL_REC_SEMINAR(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RS'||REC_SEMINAR_SEQ.NEXTVAL, 'PC1', 'UC1', 1, DEFAULT); 


--○ 면접/코딩테스트 후기 추천비추천 테이블
INSERT INTO TBL_REC_INTERVIEW(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RV'||REC_INTERVIEW_SEQ.NEXTVAL, 'PC1', 'UC1', 1, DEFAULT); 


--○ 자유게시판 추천비추천 테이블
INSERT INTO TBL_REC_FREE(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RF'||REC_FREE_SEQ.NEXTVAL, 'PC1', 'UC1', 1, DEFAULT); 


--○ Q&A 질문 추천비추천 테이블
INSERT INTO TBL_REC_QUESTION(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RQ'||REC_QUESTION_SEQ.NEXTVAL, 'PC1', 'UC1', 1, DEFAULT); 



--○ Q&A 답변 추천비추천 테이블
INSERT INTO TBL_REC_ANSWER(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RA'||REC_ANSWER_SEQ.NEXTVAL, 'PC1', 'UC1', 1, DEFAULT); 


--○ 스터디 후기 추천/ 비추천 테이블
INSERT INTO TBL_REC_STUDYREVIEW(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RR'||REC_STUDYREVIEW_SEQ.NEXTVAL, 'PC1', 'UC1', 1, DEFAULT); 






--○ IT기술정보공유 신고등록 테이블
INSERT INTO TBL_REPORT_REG_INFORM(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GI'||RPT_RG_INFORM_SEQ.NEXTVAL, 'PC1', 'UC1', 1, DEFAULT); 


--○ 면접/코딩테스트 후기  신고등록 테이블
INSERT INTO TBL_REPORT_REG_INTERVIEW(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GV'||RPT_RG_INTERVIEW_SEQ.NEXTVAL, 'PC1', 'UC1', 1, DEFAULT); 



--○ 세미나 및 공모전  신고등록 테이블
INSERT INTO TBL_REPORT_REG_SEMINAR(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GS'||RPT_RG_SEMINAR_SEQ.NEXTVAL, 'PC1', 'UC1', 1, DEFAULT); 


--○ 자유게시판 신고등록 테이블
INSERT INTO TBL_REPORT_REG_FREE(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GF'||RPT_RG_FREE_SEQ.NEXTVAL, 'PC1', 'UC1', 1, DEFAULT); 



--○ Q&A 질문 신고등록 테이블
INSERT INTO TBL_REPORT_REG_QUESTION(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GQ'||RPT_RG_QUESTION_SEQ.NEXTVAL, 'PC1', 'UC1', 1, DEFAULT); 


--○ Q&A 답변 신고등록 테이블
INSERT INTO TBL_REPORT_REG_ANSWER(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GA'||RPT_RG_ANSWER_SEQ.NEXTVAL, 'PC1', 'UC1', 1, DEFAULT); 


--○ 스터디 후기 신고 등록
INSERT INTO TBL_REPORT_REG_STUDYREVIEW(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GR'||RPT_RG_ANSWER_SEQ.NEXTVAL, 'PC1', 'UC1', 1, DEFAULT); 





--○ IT기술정보공유 신고처리 테이블
INSERT INTO TBL_REPORT_HANDLE_INFORM(REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
VALUES ('HI'||RPT_HD_INFORM_SEQ.NEXTVAL, 'PC1', 'UC1', NULL, NULL); 


--○ 면접/코딩테스트 후기 신고처리 테이블
INSERT INTO TBL_REPORT_HANDLE_INTERVIEW(REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
VALUES ('HV'||RPT_HD_INTERVIEW_SEQ.NEXTVAL, 'PC1', 'UC1', NULL, NULL); 


--○ 세미나 및 공모전 신고처리 테이블
INSERT INTO TBL_REPORT_HANDLE_SEMINAR(REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
VALUES ('HS'||RPT_HD_SEMINAR_SEQ.NEXTVAL, 'PC1', 'UC1', NULL, NULL); 

--○ 자유게시판 신고처리 테이블
INSERT INTO TBL_REPORT_HANDLE_FREE(REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
VALUES ('HF'||RPT_HD_FREE_SEQ.NEXTVAL, 'PC1', 'UC1', NULL, NULL); 


--○ Q&A 질문 신고처리 테이블
INSERT INTO TBL_REPORT_HANDLE_QUESTION(REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
VALUES ('HQ'||RPT_HD_QUESTION_SEQ.NEXTVAL, 'PC1', 'UC1', NULL, NULL); 


--○ Q&A 답변 신고처리 테이블
INSERT INTO TBL_REPORT_HANDLE_ANSWER(REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
VALUES ('HA'||RPT_HD_ANSWER_SEQ.NEXTVAL, 'PC1', 'UC1', NULL, NULL); 


--○ 스터디 후기 신고 처리  
INSERT INTO TBL_REPORT_HANDLE_STUDYREVIEW(REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
VALUES ('HR'||RPT_HD_STUDYREVIEW_SEQ.NEXTVAL, 'PC1', 'UC1', NULL, NULL); 





--○ 실습 테이블 생성(신고 처리 테이블) 경고1회, 글삭제, 신고취소, 허위신고
INSERT INTO TBL_HANDLE_RESULT(HANDLE_RESULT_CODE, HANDLE_RESULT) VALUES ('DR'||HD_RESULT_SEQ.NEXTVAL, '경고 1회');

--○ 실습 테이블 생성(세미나 카테고리 테이블) 세미나, 공모전
INSERT INTO TBL_SEMINAR_CATEGORY(SEMINAR_CATEGORY_CODE, SEMINAR_CATEGORY) VALUES ('SC'||SEMI_CTG_SEQ.NEXTVAL, '세미나');
INSERT INTO TBL_SEMINAR_CATEGORY(SEMINAR_CATEGORY_CODE, SEMINAR_CATEGORY) VALUES ('SC'||SEMI_CTG_SEQ.NEXTVAL, '공모전');


--○ 실습 테이블 생성(게시글 신고 카테고리 테이블) [광고,스팸], [욕설,비방], [기타]
INSERT INTO TBL_POST_REPORT_CTG(POST_REPORT_CTG_CODE, POST_REPORT_CTG) VALUES ('PR'||POST_RPT_CTG_SEQ.NEXTVAL, '세미나');




DESC TBL_STUDY_APPLY;









