
--○ 스터디 신고 등록 테이블 so3 uc12345
-- → 로 변경 
EXEC PRC_RPT_REG_STDOPEN_INSERT('SO3', 'UC5','광고성신고', 'PR1');
INSERT INTO TBL_STUDY_ACCUSE(ACCUSE_CODE, STUDY_CODE, USER_CODE
, ACCUSE_DATE, ACCUSE_REASON, POST_REPORT_CTG_CODE)
VALUES('AC'||STUDY_ACC_SEQ.NEXTVAL, 'SO3', 'UC1', SYSDATE , '광고성신고', 'PR1');
INSERT INTO TBL_STUDY_ACCUSE(ACCUSE_CODE, STUDY_CODE, USER_CODE
, ACCUSE_DATE, ACCUSE_REASON, POST_REPORT_CTG_CODE)
VALUES('AC'||STUDY_ACC_SEQ.NEXTVAL, 'SO3', 'UC2', SYSDATE , '광고성신고', 'PR1');
INSERT INTO TBL_STUDY_ACCUSE(ACCUSE_CODE, STUDY_CODE, USER_CODE
, ACCUSE_DATE, ACCUSE_REASON, POST_REPORT_CTG_CODE)
VALUES('AC'||STUDY_ACC_SEQ.NEXTVAL, 'SO3', 'UC3', SYSDATE , '광고성신고', 'PR1');
INSERT INTO TBL_STUDY_ACCUSE(ACCUSE_CODE, STUDY_CODE, USER_CODE
, ACCUSE_DATE, ACCUSE_REASON, POST_REPORT_CTG_CODE)
VALUES('AC'||STUDY_ACC_SEQ.NEXTVAL, 'SO3', 'UC4', SYSDATE , '광고성신고', 'PR1');
EXEC PRC_RPT_REG_STDOPEN_INSERT('SO4', 'UC1', '', 'PR1');

INSERT INTO TBL_STUDY_ACCUSE(ACCUSE_CODE, STUDY_CODE, USER_CODE
, ACCUSE_DATE, ACCUSE_REASON, POST_REPORT_CTG_CODE)
VALUES('AC'||STUDY_ACC_SEQ.NEXTVAL, 'SO3', 'UC5', SYSDATE , '광고성신고', 'PR1');
--==>> 1 행 이(가) 삽입되었습니다. * 5


--○ 스터디 신고처리 수정 = 처리결과 코드
UPDATE TBL_STUDY_ACCUSE_HANDLE
SET HANDLE_RESULT_CODE = 'DR1'
WHERE ACCUSE_HANDLE_CODE= 'AH1';
-- ↑    ↓   두개 동시 실행
EXEC PRC_INSERT_WARNING('UC7', '2021-01-16');

DESC TBL_WARNING;
--○ 스터디 경고 등록
EXEC PRC_INSERT_WARNING('UC7', '2021-01-16');
-- ↑ 이거로 바뀐듯??


--○ 욕설 테이블
INSERT INTO TBL_CURSE(CURSE_CODE, CURSE_KIND)
VALUES('CS'||CURSE_SEQ.NEXTVAL, '개새끼');
INSERT INTO TBL_CURSE(CURSE_CODE, CURSE_KIND)
VALUES('CS'||CURSE_SEQ.NEXTVAL, '병신');
INSERT INTO TBL_CURSE(CURSE_CODE, CURSE_KIND)
VALUES('CS'||CURSE_SEQ.NEXTVAL, '씨발');
INSERT INTO TBL_CURSE(CURSE_CODE, CURSE_KIND)
VALUES('CS'||CURSE_SEQ.NEXTVAL, '또라이');
INSERT INTO TBL_CURSE(CURSE_CODE, CURSE_KIND)
VALUES('CS'||CURSE_SEQ.NEXTVAL, '지랄');
INSERT INTO TBL_CURSE(CURSE_CODE, CURSE_KIND)
VALUES('CS'||CURSE_SEQ.NEXTVAL, '좆까');
INSERT INTO TBL_CURSE(CURSE_CODE, CURSE_KIND)
VALUES('CS'||CURSE_SEQ.NEXTVAL, '좇까');
INSERT INTO TBL_CURSE(CURSE_CODE, CURSE_KIND)
VALUES('CS'||CURSE_SEQ.NEXTVAL, '염병');
INSERT INTO TBL_CURSE(CURSE_CODE, CURSE_KIND)
VALUES('CS'||CURSE_SEQ.NEXTVAL, '미친');
INSERT INTO TBL_CURSE(CURSE_CODE, CURSE_KIND)
VALUES('CS'||CURSE_SEQ.NEXTVAL, '닥쳐');
INSERT INTO TBL_CURSE(CURSE_CODE, CURSE_KIND)
VALUES('CS'||CURSE_SEQ.NEXTVAL, '미친년');
INSERT INTO TBL_CURSE(CURSE_CODE, CURSE_KIND)
VALUES('CS'||CURSE_SEQ.NEXTVAL, '쓰레기새끼 ');
INSERT INTO TBL_CURSE(CURSE_CODE, CURSE_KIND)
VALUES('CS'||CURSE_SEQ.NEXTVAL, '좇같은새끼 ');
--==>> 1 행 이(가) 삽입되었습니다. * 12
SELECT * FROM TBL_CURSE;


--○ 고객센터(1:1문의) 
INSERT INTO TBL_ASK(ASK_CODE, USER_CODE, ASK_TITLE
, ASK_CONTENT, ASK_DATE, ASK_ANSWER, ASK_ANSWER_DATE, ADMIN_CODE)
VALUES('AS'||ASK_SEQ.NEXTVAL, 'UC1', '스터디문의','스터디관려해서.', SYSDATE , '답변드립니다.',SYSDATE, 'AD1');

INSERT INTO TBL_ASK(ASK_CODE, USER_CODE, ASK_TITLE, ASK_CONTENT, ASK_DATE)
VALUES('AS'||ASK_SEQ.NEXTVAL, 'UC2', '개설문의','개설하려고하는데', SYSDATE);
INSERT INTO TBL_ASK(ASK_CODE, USER_CODE, ASK_TITLE, ASK_CONTENT, ASK_DATE)
VALUES('AS'||ASK_SEQ.NEXTVAL, 'UC3', '게시판문의','게시판을수정하려는데', SYSDATE);
-- 1 행 이(가) 삽입되었습니다.
SELECT * FROM TBL_ASK;

SELECT *
FROM TBL_ASK
ORDER BY TO_NUMBER(SUBSTR(ASK_CODE, 3));

--○ 고객센터(공지사항)
INSERT INTO TBL_NOTICE(NOTICE_CODE, NOTICE_DATE, NOTICE_TITLE
, NOTICE_CONTENT, ADMIN_CODE, HITCOUNT)
VALUES('NT'||NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항1', '공지내용' , 'AD1', 0);
INSERT INTO TBL_NOTICE(NOTICE_CODE, NOTICE_DATE, NOTICE_TITLE
, NOTICE_CONTENT, ADMIN_CODE, HITCOUNT)
VALUES('NT'||NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항2', '공지내용2' , 'AD1', 0);
--==>> 1 행 이(가) 삽입되었습니다.


--○ 관리자
INSERT INTO TBL_ADMIN(ADMIN_CODE, ADMIN_ID,ADMIN_PW)
VALUES('AD'||ADMIN_SEQ.NEXTVAL, '@ADMIN1','java006$');
INSERT INTO TBL_ADMIN(ADMIN_CODE, ADMIN_ID,ADMIN_PW)
VALUES('AD'||ADMIN_SEQ.NEXTVAL, '@ADMIN2','java006$');
--==>> 1 행 이(가) 삽입되었습니다. * 2

COMMIT;
<<<<<<< HEAD


=======
>>>>>>> ddf82e6bbcfc39fa4b4699875627b683f381623f
