-- 모임 요일 테이블 인서트
INSERT INTO TBL_STUDY_MEETDAY (MEETDAY_CODE, WEEKDAY_CODE, STUDY_CODE, START_TIME, END_TIME)
VALUES ('MD'|| STD_MEETDAY_SEQ.NEXTVAL, 'WD1', 'SO1', 18, 20);

-- 요일 테이블 데이터 입력
INSERT INTO TBL_WEEKDAY(WEEKDAY_CODE, WEEKDAY) VALUES('WD'||WEEKDAY_SEQ.NEXTVAL, '월');
INSERT INTO TBL_WEEKDAY(WEEKDAY_CODE, WEEKDAY) VALUES('WD'||WEEKDAY_SEQ.NEXTVAL, '화');
INSERT INTO TBL_WEEKDAY(WEEKDAY_CODE, WEEKDAY) VALUES('WD'||WEEKDAY_SEQ.NEXTVAL, '수');
INSERT INTO TBL_WEEKDAY(WEEKDAY_CODE, WEEKDAY) VALUES('WD'||WEEKDAY_SEQ.NEXTVAL, '목');
INSERT INTO TBL_WEEKDAY(WEEKDAY_CODE, WEEKDAY) VALUES('WD'||WEEKDAY_SEQ.NEXTVAL, '금');
INSERT INTO TBL_WEEKDAY(WEEKDAY_CODE, WEEKDAY) VALUES('WD'||WEEKDAY_SEQ.NEXTVAL, '토');
INSERT INTO TBL_WEEKDAY(WEEKDAY_CODE, WEEKDAY) VALUES('WD'||WEEKDAY_SEQ.NEXTVAL, '일');


-- 인원수 테이블 데이터 입력
INSERT INTO TBL_MEMNUM(MEMNUM_CODE, MEMNUM) VALUES('MN'||MEMNUM_SEQ.NEXTVAL, 3);
INSERT INTO TBL_MEMNUM(MEMNUM_CODE, MEMNUM) VALUES('MN'||MEMNUM_SEQ.NEXTVAL, 4);
INSERT INTO TBL_MEMNUM(MEMNUM_CODE, MEMNUM) VALUES('MN'||MEMNUM_SEQ.NEXTVAL, 5);
INSERT INTO TBL_MEMNUM(MEMNUM_CODE, MEMNUM) VALUES('MN'||MEMNUM_SEQ.NEXTVAL, 6);
INSERT INTO TBL_MEMNUM(MEMNUM_CODE, MEMNUM) VALUES('MN'||MEMNUM_SEQ.NEXTVAL, 7);
INSERT INTO TBL_MEMNUM(MEMNUM_CODE, MEMNUM) VALUES('MN'||MEMNUM_SEQ.NEXTVAL, 8);


-- 등급 테이블 데이터 입력
INSERT INTO TBL_USER_RANK(RANK_CODE, RANK, MIN_SCORE, MAX_SCORE)
VALUES('UR'||USER_RANK_SEQ.NEXTVAL, 1, 12600, 18600);
INSERT INTO TBL_USER_RANK(RANK_CODE, RANK, MIN_SCORE, MAX_SCORE)
VALUES('UR'||USER_RANK_SEQ.NEXTVAL, 2, 7800, 12599);
INSERT INTO TBL_USER_RANK(RANK_CODE, RANK, MIN_SCORE, MAX_SCORE)
VALUES('UR'||USER_RANK_SEQ.NEXTVAL, 3, 4200, 7799);
INSERT INTO TBL_USER_RANK(RANK_CODE, RANK, MIN_SCORE, MAX_SCORE)
VALUES('UR'||USER_RANK_SEQ.NEXTVAL, 4, 1800, 4199);
INSERT INTO TBL_USER_RANK(RANK_CODE, RANK, MIN_SCORE, MAX_SCORE)
VALUES('UR'||USER_RANK_SEQ.NEXTVAL, 5, 600, 1799);
INSERT INTO TBL_USER_RANK(RANK_CODE, RANK, MIN_SCORE, MAX_SCORE)
VALUES('UR'||USER_RANK_SEQ.NEXTVAL, 6, 0, 599);


-- 스터디 유형 테이블 데이터 입력
INSERT INTO TBL_STUDY_TYPE(STUDY_TYPE_CODE, STUDY_TYPE) 
VALUES('ST'||STD_TYPE_SEQ.NEXTVAL, '면접');
INSERT INTO TBL_STUDY_TYPE(STUDY_TYPE_CODE, STUDY_TYPE) 
VALUES('ST'||STD_TYPE_SEQ.NEXTVAL, '코딩테스트');
INSERT INTO TBL_STUDY_TYPE(STUDY_TYPE_CODE, STUDY_TYPE) 
VALUES('ST'||STD_TYPE_SEQ.NEXTVAL, '프로그래밍언어');


-- 관심분야 대분류 테이블 데이터 입력
INSERT INTO TBL_INTEREST_LC(INTEREST_LC_CODE, INTEREST_LC)
VALUES('IL'||INTER_LC_SEQ.NEXTVAL, '정보기술개발');
INSERT INTO TBL_INTEREST_LC(INTEREST_LC_CODE, INTEREST_LC)
VALUES('IL'||INTER_LC_SEQ.NEXTVAL, '정보기술운영');


-- 관심분야 중분류 테이블 데이터 입력
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE)
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'SW아키텍쳐', 'IL1'); -- 정보기술개발 대분류 참조
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE)
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '응용SW엔지니어링', 'IL1'); -- 정보기술개발 대분류 참조
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE)
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '임베디드SW엔지니어링', 'IL1'); -- 정보기술개발 대분류 참조
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE)
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'DB엔지니어링', 'IL1'); -- 정보기술개발 대분류 참조
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE)
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'IT시스템관리', 'IL2'); -- 정보기술운영 대분류 참조
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE)
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'IT기술교육', 'IL2'); -- 정보기술운영 대분류 참조
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE)
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'IT기술지원', 'IL2'); -- 정보기술운영 대분류 참조
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE)
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '빅데이터운영관리', 'IL2'); -- 정보기술운영 대분류 참조

SELECT *
FROM TBL_INTEREST_MC;

-- 지역 대분류 테이블 데이터 입력
INSERT INTO TBL_LOC_LC(LOC_LC_CODE, LOC_LC)
VALUES('LL'||LOC_LC_SEQ.NEXTVAL, '서울');


-- 지역 중분류 테이블 데이터 입력
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '강남', 'LL1');


-- 스터디 개설 테이블 데이터 입력
INSERT INTO TBL_STUDY_OPEN
( STUDY_CODE, USER_CODE
, STUDY_TYPE_CODE, INTEREST_MC_CODE
, START_DATE, END_DATE
, MIN_MEM_CODE, MAX_MEM_CODE
, STUDY_NAME, MIN_RANK, CLOSE_DATE
, STUDY_DESC, LOC_MC_CODE)
VALUES
( 'SO'||STD_OPEN_SEQ.NEXTVAL, 유저코드 --> 유저코드 수정하고 인서트 해야함!!!
, 'ST1', 'IM1'
, TO_DATE('2021-01-17', 'YYYY-MM-DD'), TO_DATE('2021-03-17', 'YYYY-MM-DD')
, 'MN1', 'MN4'
, '카카오톡 개발자 공채 면접 준비', 4, TO_DATE('2021-02-01', 'YYYY-MM-DD')
, '함께 카카오 면접 준비하실분!!!', 'LM1');


