--■ 테이블 INSERT 구문 ■--


--○ 실습 테이블 생성(신고 처리결과 테이블) 경고1회, 글삭제, 신고취소, 허위신고
INSERT INTO TBL_HANDLE_RESULT(HANDLE_RESULT_CODE, HANDLE_RESULT) VALUES ('DR'||HD_RESULT_SEQ.NEXTVAL, '경고 1회');
INSERT INTO TBL_HANDLE_RESULT(HANDLE_RESULT_CODE, HANDLE_RESULT) VALUES ('DR'||HD_RESULT_SEQ.NEXTVAL, '글삭제');
INSERT INTO TBL_HANDLE_RESULT(HANDLE_RESULT_CODE, HANDLE_RESULT) VALUES ('DR'||HD_RESULT_SEQ.NEXTVAL, '신고취소');
INSERT INTO TBL_HANDLE_RESULT(HANDLE_RESULT_CODE, HANDLE_RESULT) VALUES ('DR'||HD_RESULT_SEQ.NEXTVAL, '허위신고');

--○ 실습 테이블 생성(세미나 카테고리 테이블) 세미나, 공모전
INSERT INTO TBL_SEMINAR_CATEGORY(SEMINAR_CATEGORY_CODE, SEMINAR_CATEGORY) VALUES ('SC'||SEMI_CTG_SEQ.NEXTVAL, '세미나');
INSERT INTO TBL_SEMINAR_CATEGORY(SEMINAR_CATEGORY_CODE, SEMINAR_CATEGORY) VALUES ('SC'||SEMI_CTG_SEQ.NEXTVAL, '공모전');


--○ 실습 테이블 생성(게시글 신고 카테고리 테이블) [광고,스팸], [욕설,비방], [기타]
INSERT INTO TBL_POST_REPORT_CTG(POST_REPORT_CTG_CODE, POST_REPORT_CTG) 
VALUES ('PR'||POST_RPT_CTG_SEQ.NEXTVAL, '광고, 스팸');
INSERT INTO TBL_POST_REPORT_CTG(POST_REPORT_CTG_CODE, POST_REPORT_CTG) 
VALUES ('PR'||POST_RPT_CTG_SEQ.NEXTVAL, '욕설, 비방');
INSERT INTO TBL_POST_REPORT_CTG(POST_REPORT_CTG_CODE, POST_REPORT_CTG) 
VALUES ('PR'||POST_RPT_CTG_SEQ.NEXTVAL, '기타');

-------------------------------------------------------------------------------- 여기까지 인서트 실행

--○ IT기술정보공유 테이블 *관심분야 카테고리는 몰라서 임의로 넣었어요
INSERT INTO TBL_BOARD_INFORM(POST_CODE, USER_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT, INTEREST_MC_CODE) 
VALUES ('BI'||BOARD_INFORM_SEQ.NEXTVAL, 'UC1', DEFAULT, DEFAULT, '오라클 트리거란?', 
        ' 개요 테이블에 대한 이벤트를 자동으로 실행해 주는 것', 'IM1');

INSERT INTO TBL_BOARD_INFORM(POST_CODE, USER_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT, INTEREST_MC_CODE) 
VALUES ('BI'||BOARD_INFORM_SEQ.NEXTVAL, 'UC7', DEFAULT, DEFAULT, '맛있는 고구마 있어요', ' 해남 고구마 팔아요', 'IM2'); 

--○ 면접/코딩테스트 후기 테이블
INSERT INTO TBL_BOARD_INTERVIEW(POST_CODE, USER_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT, INTEREST_MC_CODE) 
VALUES ('BV'||BOARD_INTERVIEW_SEQ.NEXTVAL, 'UC2', DEFAULT, DEFAULT, '카카오 코테 봄', '그렇게 어렵지 않음 합격함', 'IM4'); 

INSERT INTO TBL_BOARD_INTERVIEW(POST_CODE, USER_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT, INTEREST_MC_CODE) 
VALUES ('BV'||BOARD_INTERVIEW_SEQ.NEXTVAL, 'UC7', DEFAULT, DEFAULT, '밑에 새끼 재수없네', 
        '왜 자랑질임 미친놈 개구라일듯', 'IM3');


--○ 세미나 및 공모전 테이블
INSERT INTO TBL_BOARD_SEMINAR(POST_CODE, USER_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT, SEMINAR_CATEGORY_CODE, START_DATE, END_DATE) 
VALUES ('BS'||BOARD_SEMINAR_SEQ.NEXTVAL, 'UC3', DEFAULT, DEFAULT, '2021 IT분야 기술 연구'
, 'IT분야 기술을 주제로 세미나 개최`', 'SC1', TO_DATE('2021-01-10', 'YYYY-MM-DD'), TO_DATE('2021-01-20', 'YYYY-MM-DD')); 

INSERT INTO TBL_BOARD_SEMINAR(POST_CODE, USER_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT, SEMINAR_CATEGORY_CODE, START_DATE, END_DATE) 
VALUES ('BS'||BOARD_SEMINAR_SEQ.NEXTVAL, 'UC4', DEFAULT, DEFAULT, '공공 데이터 활용 앱 개발 공모전'
, '공공 데이터를 활용해 앱 개발', 'SC2', TO_DATE('2021-01-15', 'YYYY-MM-DD'), TO_DATE('2021-01-21', 'YYYY-MM-DD')); 


--○ 자유게시판 테이블
INSERT INTO TBL_BOARD_FREE(POST_CODE, USER_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT) 
VALUES ('BF'||BOARD_FREE_SEQ.NEXTVAL, 'UC4', DEFAULT, DEFAULT, '안녕하세요', '오늘 가입했습니다.'); 

INSERT INTO TBL_BOARD_FREE(POST_CODE, USER_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT) 
VALUES ('BF'||BOARD_FREE_SEQ.NEXTVAL, 'UC5', DEFAULT, DEFAULT, 
        '같이 라인 면접 스터디 하실 분?', '댓글 많이 달리면 제가 개설할게요.'); 


--○ Q&A 질문 테이블
INSERT INTO TBL_BOARD_QUESTION(POST_CODE, USER_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT, INTEREST_MC_CODE) 
VALUES ('BQ'||BOARD_QUESTION_SEQ.NEXTVAL, 'UC1', DEFAULT, DEFAULT, '프로시저 관련 질문 있어요', 
        '프로시저에 서브쿼리 쓸 수 있나요?', 'IM1'); 

INSERT INTO TBL_BOARD_QUESTION(POST_CODE, USER_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT, INTEREST_MC_CODE) 
VALUES ('BQ'||BOARD_QUESTION_SEQ.NEXTVAL, 'UC4', DEFAULT, DEFAULT, '트리거 질문', 
        '트리거에서 :NEW.어쩌구 이게 뭔가요?', 'IM1'); 

--○ 스터디 후기 테이블 * PARTI_CODE, INTEREST_MC_CODE 확인
INSERT INTO TBL_BOARD_STUDYREVIEW(POST_CODE, PARTI_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT, INTEREST_MC_CODE) 
VALUES ('BR'||BOARD_STUDYREVIEW_SEQ.NEXTVAL, 'PT1', DEFAULT, DEFAULT, '카카오 면접 준비 스터디 후기', '열심히 해서 전원 합격', 'IM2');  

INSERT INTO TBL_BOARD_STUDYREVIEW(POST_CODE, PARTI_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT, INTEREST_MC_CODE) 
VALUES ('BR'||BOARD_STUDYREVIEW_SEQ.NEXTVAL, 'PT2', DEFAULT, DEFAULT, '정처기 준비 스터디 완', '필기 합격했어요', 'IM3');  




--○ IT기술정보공유 댓글 테이블
INSERT INTO TBL_COMMENT_INFORM(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CI'||COMMENT_INFORM_SEQ.NEXTVAL, 'BI1', '좋은 정보 감사합니다.', 'UC2', DEFAULT);  

INSERT INTO TBL_COMMENT_INFORM(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CI'||COMMENT_INFORM_SEQ.NEXTVAL, 'BI1', '땡큐땡큐', 'UC7', DEFAULT); 

INSERT INTO TBL_COMMENT_INFORM(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CI'||COMMENT_INFORM_SEQ.NEXTVAL, 'BI2', '신고 완', 'UC3', DEFAULT);  

INSERT INTO TBL_COMMENT_INFORM(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CI'||COMMENT_INFORM_SEQ.NEXTVAL, 'BI2', '광고 ㅗ 신고함', 'UC5', DEFAULT); 

--○ 면접 및 코딩테스트 후기 댓글 테이블
INSERT INTO TBL_COMMENT_INTERVIEW(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CC'||COMMENT_INTERVIEW_SEQ.NEXTVAL, 'BV1', '오 축하드려요', 'UC1', DEFAULT); 

INSERT INTO TBL_COMMENT_INTERVIEW(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CC'||COMMENT_INTERVIEW_SEQ.NEXTVAL, 'BV1', '헐 부럽..', 'UC5', DEFAULT); 

INSERT INTO TBL_COMMENT_INTERVIEW(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CC'||COMMENT_INTERVIEW_SEQ.NEXTVAL, 'BV2', '욕설 금지임 님 신고', 'UC4', DEFAULT); 

INSERT INTO TBL_COMMENT_INTERVIEW(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CC'||COMMENT_INTERVIEW_SEQ.NEXTVAL, 'BV2', '부러우면 공부나 해', 'UC6', DEFAULT); 

--○ 세미나 및 공모전 댓글 테이블
INSERT INTO TBL_COMMENT_SEMINAR(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CS'||COMMENT_SEMINAR_SEQ.NEXTVAL, 'BS1', '오 감사합니다', 'UC4', DEFAULT); 

INSERT INTO TBL_COMMENT_SEMINAR(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CS'||COMMENT_SEMINAR_SEQ.NEXTVAL, 'BS1', '좋은 글이네요', 'UC1', DEFAULT);

INSERT INTO TBL_COMMENT_SEMINAR(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CS'||COMMENT_SEMINAR_SEQ.NEXTVAL, 'BS2', '경쟁률 높을까요..', 'UC3', DEFAULT); 

INSERT INTO TBL_COMMENT_SEMINAR(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CS'||COMMENT_SEMINAR_SEQ.NEXTVAL, 'BS2', '하고 싶은데 시간이 없네', 'UC2', DEFAULT);


--○ 자유게시판 댓글 테이블
INSERT INTO TBL_COMMENT_FREE(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CF'||COMMENT_FREE_SEQ.NEXTVAL, 'BF1', '안녕하세요~', 'UC6', DEFAULT);

INSERT INTO TBL_COMMENT_FREE(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CF'||COMMENT_FREE_SEQ.NEXTVAL, 'BF1', '반갑습니다 ㅎㅎ', 'UC7', DEFAULT); 

INSERT INTO TBL_COMMENT_FREE(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CF'||COMMENT_FREE_SEQ.NEXTVAL, 'BF2', '저요저요', 'UC3', DEFAULT);

INSERT INTO TBL_COMMENT_FREE(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CF'||COMMENT_FREE_SEQ.NEXTVAL, 'BF2', '저도 준비 중인데 껴 주세요!', 'UC1', DEFAULT); 

--○ Q&A 질문 댓글 테이블
INSERT INTO TBL_COMMENT_QUESTION(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CQ'||COMMENT_QUESTION_SEQ.NEXTVAL, 'BQ1', '저도 이거 궁금했는데', 'UC5', DEFAULT); 

INSERT INTO TBL_COMMENT_QUESTION(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CQ'||COMMENT_QUESTION_SEQ.NEXTVAL, 'BQ1', '예제도 같이 보여 주세요 ㅠ', 'UC4', DEFAULT); 

INSERT INTO TBL_COMMENT_QUESTION(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CQ'||COMMENT_QUESTION_SEQ.NEXTVAL, 'BQ2', ':NEW가 새 데이터 값일걸요? ', 'UC6', DEFAULT); 

INSERT INTO TBL_COMMENT_QUESTION(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CQ'||COMMENT_QUESTION_SEQ.NEXTVAL, 'BQ2', '구글에 검색하면 나옴..', 'UC2', DEFAULT); 


--○ 스터디 후기 댓글 테이블
INSERT INTO TBL_COMMENT_STUDYREVIEW(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CR'||COMMENT_STUDYREVIEW_SEQ.NEXTVAL, 'BR1', '와 비법 좀', 'UC3', DEFAULT); 

INSERT INTO TBL_COMMENT_STUDYREVIEW(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CR'||COMMENT_STUDYREVIEW_SEQ.NEXTVAL, 'BR1', '진짜 부럽네요 ㅠㅠ', 'UC1', DEFAULT);

INSERT INTO TBL_COMMENT_STUDYREVIEW(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CR'||COMMENT_STUDYREVIEW_SEQ.NEXTVAL, 'BR2', '아 저도 따야 되는데 귀찮네요 ㅜㅜ', 'UC6', DEFAULT); 

INSERT INTO TBL_COMMENT_STUDYREVIEW(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CR'||COMMENT_STUDYREVIEW_SEQ.NEXTVAL, 'BR2', '축하드려요!!', 'UC4', DEFAULT);


--○ Q&A 답변 테이블
INSERT INTO TBL_BOARD_ANSWER(POST_CODE, USER_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT, INTEREST_MC_CODE) 
VALUES ('BA'||BOARD_ANSWER_SEQ.NEXTVAL, 'UC2', DEFAULT, DEFAULT, '└트리거 질문에 대한 답변', 
        ':NEW가 붙은 건 데이터가 삽입될 때 새로 들어온 값입니다', 'IM1'); 


--○ IT기술정보공유 추천/비추천 테이블
INSERT INTO TBL_REC_INFORM(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RI'||REC_INFORM_SEQ.NEXTVAL, 'BR1', 'UC1', 1, DEFAULT); 

INSERT INTO TBL_REC_INFORM(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RI'||REC_INFORM_SEQ.NEXTVAL, 'BR1', 'UC2', 1, DEFAULT); 

INSERT INTO TBL_REC_INFORM(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RI'||REC_INFORM_SEQ.NEXTVAL, 'BR1', 'UC3', 2, DEFAULT); 

INSERT INTO TBL_REC_INFORM(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RI'||REC_INFORM_SEQ.NEXTVAL, 'BR2', 'UC4', 2, DEFAULT); 

INSERT INTO TBL_REC_INFORM(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RI'||REC_INFORM_SEQ.NEXTVAL, 'BR2', 'UC5', 2, DEFAULT); 

INSERT INTO TBL_REC_INFORM(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RI'||REC_INFORM_SEQ.NEXTVAL, 'BR2', 'UC6', 2, DEFAULT); 


--○ 세미나 및 공모전 추천/비추천 테이블
INSERT INTO TBL_REC_SEMINAR(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RS'||REC_SEMINAR_SEQ.NEXTVAL, 'BS1', 'UC1', 1, DEFAULT); 

INSERT INTO TBL_REC_SEMINAR(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RS'||REC_SEMINAR_SEQ.NEXTVAL, 'BS1', 'UC2', 1, DEFAULT); 

INSERT INTO TBL_REC_SEMINAR(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RS'||REC_SEMINAR_SEQ.NEXTVAL, 'BS1', 'UC3', 1, DEFAULT); 

INSERT INTO TBL_REC_SEMINAR(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RS'||REC_SEMINAR_SEQ.NEXTVAL, 'BS2', 'UC4', 1, DEFAULT); 

INSERT INTO TBL_REC_SEMINAR(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RS'||REC_SEMINAR_SEQ.NEXTVAL, 'BS2', 'UC5', 1, DEFAULT); 

INSERT INTO TBL_REC_SEMINAR(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RS'||REC_SEMINAR_SEQ.NEXTVAL, 'BS2', 'UC6', 1, DEFAULT); 


--○ 면접/코딩테스트 후기 추천비추천 테이블
INSERT INTO TBL_REC_INTERVIEW(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RV'||REC_INTERVIEW_SEQ.NEXTVAL, 'BV1', 'UC1', 1, DEFAULT); 

INSERT INTO TBL_REC_INTERVIEW(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RV'||REC_INTERVIEW_SEQ.NEXTVAL, 'BV1', 'UC2', 1, DEFAULT); 

INSERT INTO TBL_REC_INTERVIEW(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RV'||REC_INTERVIEW_SEQ.NEXTVAL, 'BV1', 'UC3', 1, DEFAULT); 

INSERT INTO TBL_REC_INTERVIEW(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RV'||REC_INTERVIEW_SEQ.NEXTVAL, 'BV2', 'UC4', 2, DEFAULT); 

INSERT INTO TBL_REC_INTERVIEW(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RV'||REC_INTERVIEW_SEQ.NEXTVAL, 'BV2', 'UC5', 2, DEFAULT); 

INSERT INTO TBL_REC_INTERVIEW(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RV'||REC_INTERVIEW_SEQ.NEXTVAL, 'BV2', 'UC6', 1, DEFAULT); 


--○ 자유게시판 추천비추천 테이블
INSERT INTO TBL_REC_FREE(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RF'||REC_FREE_SEQ.NEXTVAL, 'BF1', 'UC1', 1, DEFAULT); 

INSERT INTO TBL_REC_FREE(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RF'||REC_FREE_SEQ.NEXTVAL, 'BF1', 'UC2', 1, DEFAULT); 

INSERT INTO TBL_REC_FREE(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RF'||REC_FREE_SEQ.NEXTVAL, 'BF1', 'UC3', 1, DEFAULT); 

INSERT INTO TBL_REC_FREE(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RF'||REC_FREE_SEQ.NEXTVAL, 'BF2', 'UC4', 2, DEFAULT); 

INSERT INTO TBL_REC_FREE(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RF'||REC_FREE_SEQ.NEXTVAL, 'BF2', 'UC5', 1, DEFAULT); 

INSERT INTO TBL_REC_FREE(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RF'||REC_FREE_SEQ.NEXTVAL, 'BF2', 'UC6', 1, DEFAULT); 


--○ Q&A 질문 추천비추천 테이블
INSERT INTO TBL_REC_QUESTION(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RQ'||REC_QUESTION_SEQ.NEXTVAL, 'BQ1', 'UC1', 1, DEFAULT); 

INSERT INTO TBL_REC_QUESTION(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RQ'||REC_QUESTION_SEQ.NEXTVAL, 'BQ1', 'UC2', 1, DEFAULT); 

INSERT INTO TBL_REC_QUESTION(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RQ'||REC_QUESTION_SEQ.NEXTVAL, 'BQ1', 'UC3', 1, DEFAULT); 

INSERT INTO TBL_REC_QUESTION(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RQ'||REC_QUESTION_SEQ.NEXTVAL, 'BQ2', 'UC4', 1, DEFAULT); 

INSERT INTO TBL_REC_QUESTION(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RQ'||REC_QUESTION_SEQ.NEXTVAL, 'BQ2', 'UC5', 1, DEFAULT); 

INSERT INTO TBL_REC_QUESTION(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RQ'||REC_QUESTION_SEQ.NEXTVAL, 'BQ2', 'UC6', 1, DEFAULT); 

--○ 스터디 후기 추천/ 비추천 테이블
INSERT INTO TBL_REC_STUDYREVIEW(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RR'||REC_STUDYREVIEW_SEQ.NEXTVAL, 'BR1', 'UC1', 1, DEFAULT); 

INSERT INTO TBL_REC_STUDYREVIEW(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RR'||REC_STUDYREVIEW_SEQ.NEXTVAL, 'BR1', 'UC2', 1, DEFAULT); 

INSERT INTO TBL_REC_STUDYREVIEW(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RR'||REC_STUDYREVIEW_SEQ.NEXTVAL, 'BR1', 'UC3', 2, DEFAULT); 

INSERT INTO TBL_REC_STUDYREVIEW(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RR'||REC_STUDYREVIEW_SEQ.NEXTVAL, 'BR2', 'UC4', 1, DEFAULT); 

INSERT INTO TBL_REC_STUDYREVIEW(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RR'||REC_STUDYREVIEW_SEQ.NEXTVAL, 'BR2', 'UC5', 1, DEFAULT); 

INSERT INTO TBL_REC_STUDYREVIEW(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RR'||REC_STUDYREVIEW_SEQ.NEXTVAL, 'BR2', 'UC6', 1, DEFAULT); 



--○ IT기술정보공유 신고등록 테이블
INSERT INTO TBL_REPORT_REG_INFORM(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GI'||RPT_RG_INFORM_SEQ.NEXTVAL, 'BI2', 'UC1', DEFAULT, '광고글이에요', 'PR1'); 

INSERT INTO TBL_REPORT_REG_INFORM(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GI'||RPT_RG_INFORM_SEQ.NEXTVAL, 'BI2', 'UC2', DEFAULT, '광고글', 'PR1'); 

INSERT INTO TBL_REPORT_REG_INFORM(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GI'||RPT_RG_INFORM_SEQ.NEXTVAL, 'BI2', 'UC3', DEFAULT, '고구마 팔아요', 'PR1'); 

INSERT INTO TBL_REPORT_REG_INFORM(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GI'||RPT_RG_INFORM_SEQ.NEXTVAL, 'BI2', 'UC4', DEFAULT, '광고', 'PR1'); 

INSERT INTO TBL_REPORT_REG_INFORM(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GI'||RPT_RG_INFORM_SEQ.NEXTVAL, 'BI2', 'UC5', DEFAULT, '광고글요', 'PR1'); 




--○ 면접/코딩테스트 후기  신고등록 테이블
INSERT INTO TBL_REPORT_REG_INTERVIEW(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GV'||RPT_RG_INTERVIEW_SEQ.NEXTVAL, 'BV2', 'UC1', DEFAULT, '욕설', 'PR2'); 

INSERT INTO TBL_REPORT_REG_INTERVIEW(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GV'||RPT_RG_INTERVIEW_SEQ.NEXTVAL, 'BV2', 'UC2', DEFAULT, '욕함', 'PR2'); 

INSERT INTO TBL_REPORT_REG_INTERVIEW(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GV'||RPT_RG_INTERVIEW_SEQ.NEXTVAL, 'BV2', 'UC3', DEFAULT, '비방글', 'PR2'); 

INSERT INTO TBL_REPORT_REG_INTERVIEW(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GV'||RPT_RG_INTERVIEW_SEQ.NEXTVAL, 'BV2', 'UC4', DEFAULT, '저격글이에요', 'PR2'); 

INSERT INTO TBL_REPORT_REG_INTERVIEW(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GV'||RPT_RG_INTERVIEW_SEQ.NEXTVAL, 'BV2', 'UC5', DEFAULT, '욕설 사용', 'PR2'); 



--○ 세미나 및 공모전  신고등록 테이블
INSERT INTO TBL_REPORT_REG_SEMINAR(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GS'||RPT_RG_SEMINAR_SEQ.NEXTVAL, 'BS2', 'UC5', DEFAULT, '그냥', 'PR3'); 

INSERT INTO TBL_REPORT_REG_SEMINAR(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GS'||RPT_RG_SEMINAR_SEQ.NEXTVAL, 'BS2', 'UC3', DEFAULT, '그냥', 'PR3'); 

INSERT INTO TBL_REPORT_REG_SEMINAR(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GS'||RPT_RG_SEMINAR_SEQ.NEXTVAL, 'BS2', 'UC1', DEFAULT, '그냥', 'PR3'); 

INSERT INTO TBL_REPORT_REG_SEMINAR(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GS'||RPT_RG_SEMINAR_SEQ.NEXTVAL, 'BS2', 'UC6', DEFAULT, '그냥', 'PR3'); 

INSERT INTO TBL_REPORT_REG_SEMINAR(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GS'||RPT_RG_SEMINAR_SEQ.NEXTVAL, 'BS2', 'UC2', DEFAULT, '그냥', 'PR3'); 


--○ 자유게시판 신고등록 테이블
INSERT INTO TBL_REPORT_REG_FREE(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GF'||RPT_RG_FREE_SEQ.NEXTVAL, 'BF2', 'UC4', DEFAULT, '사람 구하는 글 되나요?', 'PR3'); 


INSERT INTO TBL_REPORT_REG_FREE(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GF'||RPT_RG_FREE_SEQ.NEXTVAL, 'BF2', 'UC1', DEFAULT, '사람 구하는 글 되나요?', 'PR3'); 

INSERT INTO TBL_REPORT_REG_FREE(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GF'||RPT_RG_FREE_SEQ.NEXTVAL, 'BF2', 'UC2', DEFAULT, '사람 구하는 글 되나요?', 'PR3'); 

INSERT INTO TBL_REPORT_REG_FREE(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GF'||RPT_RG_FREE_SEQ.NEXTVAL, 'BF2', 'UC3', DEFAULT, '사람 구하는 글 되나요?', 'PR3'); 

INSERT INTO TBL_REPORT_REG_FREE(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GF'||RPT_RG_FREE_SEQ.NEXTVAL, 'BF2', 'UC6', DEFAULT, '사람 구하는 글 되나요?', 'PR3'); 


--○ Q&A 질문 신고등록 테이블
INSERT INTO TBL_REPORT_REG_QUESTION(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GQ'||RPT_RG_QUESTION_SEQ.NEXTVAL, 'BQ2', 'UC2', DEFAULT, '모름', 'PR3'); 

INSERT INTO TBL_REPORT_REG_QUESTION(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GQ'||RPT_RG_QUESTION_SEQ.NEXTVAL, 'BQ2', 'UC1', DEFAULT, '모름', 'PR3'); 

INSERT INTO TBL_REPORT_REG_QUESTION(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GQ'||RPT_RG_QUESTION_SEQ.NEXTVAL, 'BQ2', 'UC3', DEFAULT, '모름', 'PR3'); 

INSERT INTO TBL_REPORT_REG_QUESTION(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GQ'||RPT_RG_QUESTION_SEQ.NEXTVAL, 'BQ2', 'UC5', DEFAULT, '모름', 'PR3'); 

INSERT INTO TBL_REPORT_REG_QUESTION(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GQ'||RPT_RG_QUESTION_SEQ.NEXTVAL, 'BQ2', 'UC6', DEFAULT, '모름', 'PR3'); 


--○ Q&A 답변 신고등록 테이블
INSERT INTO TBL_REPORT_REG_ANSWER(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GA'||RPT_RG_ANSWER_SEQ.NEXTVAL, 'BA2', 'UC1', DEFAULT, '무슨 말인지 모르겠음', 'PR3'); 

INSERT INTO TBL_REPORT_REG_ANSWER(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GA'||RPT_RG_ANSWER_SEQ.NEXTVAL, 'BA2', 'UC3', DEFAULT, '무슨 말인지 모르겠음', 'PR3'); 

INSERT INTO TBL_REPORT_REG_ANSWER(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GA'||RPT_RG_ANSWER_SEQ.NEXTVAL, 'BA2', 'UC4', DEFAULT, '무슨 말인지 모르겠음', 'PR3'); 

INSERT INTO TBL_REPORT_REG_ANSWER(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GA'||RPT_RG_ANSWER_SEQ.NEXTVAL, 'BA2', 'UC5', DEFAULT, '무슨 말인지 모르겠음', 'PR3'); 

INSERT INTO TBL_REPORT_REG_ANSWER(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GA'||RPT_RG_ANSWER_SEQ.NEXTVAL, 'BA2', 'UC6', DEFAULT, '무슨 말인지 모르겠음', 'PR3'); 


--○ 스터디 후기 신고 등록
INSERT INTO TBL_REPORT_REG_STUDYREVIEW(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GR'||RPT_RG_ANSWER_SEQ.NEXTVAL, 'BR1', 'UC1', DEFAULT, '허위 사실 유포', 'PR3'); 

INSERT INTO TBL_REPORT_REG_STUDYREVIEW(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GR'||RPT_RG_ANSWER_SEQ.NEXTVAL, 'BR1', 'UC2', DEFAULT, '허위 사실 유포', 'PR3'); 

INSERT INTO TBL_REPORT_REG_STUDYREVIEW(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GR'||RPT_RG_ANSWER_SEQ.NEXTVAL, 'BR1', 'UC3', DEFAULT, '허위 사실 유포', 'PR3'); 

INSERT INTO TBL_REPORT_REG_STUDYREVIEW(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GR'||RPT_RG_ANSWER_SEQ.NEXTVAL, 'BR1', 'UC4', DEFAULT, '허위 사실 유포', 'PR3'); 

INSERT INTO TBL_REPORT_REG_STUDYREVIEW(POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE) 
VALUES ('GR'||RPT_RG_ANSWER_SEQ.NEXTVAL, 'BR1', 'UC5', DEFAULT, '허위 사실 유포', 'PR3'); 


--○ Q&A 답변 댓글 테이블
INSERT INTO TBL_COMMENT_ANSWER(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CA'||COMMENT_ANSWER_SEQ.NEXTVAL, 'BA1', '감사합니다~', 'UC1', DEFAULT);

INSERT INTO TBL_COMMENT_ANSWER(COMMENT_CODE, POST_CODE, COMMENTS, USER_CODE, WRITE_DATE) 
VALUES ('CA'||COMMENT_ANSWER_SEQ.NEXTVAL, 'BA1', '좋은 정보 ㄳ', 'UC3', DEFAULT);

--○ Q&A 답변 추천비추천 테이블
INSERT INTO TBL_REC_ANSWER(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RA'||REC_ANSWER_SEQ.NEXTVAL, 'BA1', 'UC1', 1, DEFAULT); 

INSERT INTO TBL_REC_ANSWER(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RA'||REC_ANSWER_SEQ.NEXTVAL, 'BA1', 'UC3', 1, DEFAULT); 

INSERT INTO TBL_REC_ANSWER(REC_CODE, POST_CODE, USER_CODE, REC_CHECK, REC_DATE) 
VALUES ('RA'||REC_ANSWER_SEQ.NEXTVAL, 'BA1', 'UC6', 1, DEFAULT); 


--○ IT기술정보공유 신고처리 테이블
INSERT INTO TBL_REPORT_HANDLE_INFORM(REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
VALUES ('HI'||RPT_HD_INFORM_SEQ.NEXTVAL, 'GI5', 'DR1', SYSDATE); 


--○ 면접/코딩테스트 후기 신고처리 테이블
INSERT INTO TBL_REPORT_HANDLE_INTERVIEW(REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
VALUES ('HV'||RPT_HD_INTERVIEW_SEQ.NEXTVAL, 'GV5', 'DR1', SYSDATE); 


--○ 세미나 및 공모전 신고처리 테이블
INSERT INTO TBL_REPORT_HANDLE_SEMINAR(REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
VALUES ('HS'||RPT_HD_SEMINAR_SEQ.NEXTVAL, 'GS5', 'DR4', SYSDATE); 

--○ 자유게시판 신고처리 테이블
INSERT INTO TBL_REPORT_HANDLE_FREE(REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
VALUES ('HF'||RPT_HD_FREE_SEQ.NEXTVAL, 'GF5', 'DR3', SYSDATE); 


--○ Q&A 질문 신고처리 테이블
INSERT INTO TBL_REPORT_HANDLE_QUESTION(REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
VALUES ('HQ'||RPT_HD_QUESTION_SEQ.NEXTVAL, 'GQ5', 'DR4', SYSDATE); 


--○ Q&A 답변 신고처리 테이블
INSERT INTO TBL_REPORT_HANDLE_ANSWER(REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
VALUES ('HA'||RPT_HD_ANSWER_SEQ.NEXTVAL, 'GA5', 'DR3', SYSDATE); 


--○ 스터디 후기 신고 처리  
INSERT INTO TBL_REPORT_HANDLE_STUDYREVIEW(REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
VALUES ('HR'||RPT_HD_STUDYREVIEW_SEQ.NEXTVAL, 'GR5', 'DR4', SYSDATE); 















