-- 스터디 신청
INSERT INTO TBL_STUDY_APPLY(APPLY_CODE, STUDY_CODE, USER_CODE, APPLY_DATE)
    VALUES('SA'|| STUDY_APL_SEQ.NEXTVAL, 스터디코드, 유저코드, SYSDATE);
    
-- 스터디 취소처리
INSERT INTO TBL_STUDY_CANCEL(CANCEL_CODE, APPLY_CODE, CANCEL_DATE)
    VALUES('SC'|| STUDY_CANC_SEQ.NEXTVAL, 신청코드, SYSDATE);
    
-- 스터디 참가
INSERT INTO TBL_STUDY_PARTICIPANT(PARTI_CODE, APPLY_CODE, POSITION_CODE)
    VALUES('PT'|| STUDY_PARTI_SEQ.NEXTVAL, 신청코드, 직책코드);
    
-- 직책
INSERT INTO TBL_STUDY_POSITION(POSITION_CODE, POSITION)
    VALUES('SP'|| STUDY_POS_SEQ.NEXTVAL, 직책);

-- 스터디 컨텐츠
INSERT INTO TBL_STUDY_CONTENT(CONTENT_CODE, PARTI_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT)
    VALUES('CT'|| STUDY_CON_SEQ.NEXTVAL, 'PT1', SYSDATE, 0, '안녕하세요', '오늘공부한내용');
    
-- 스터디 평가
INSERT INTO TBL_STUDY_ASSESS(ASSESS_CODE, PARTI_CODE, SCORE, ASSESS_DATE)
    VALUES('AS'|| STUDY_ASSE_SEQ.NEXTVAL, 'PT1', 5, SYSDATE);
    
-- 출석부
INSERT INTO TBL_STUDY_ATTEND(ATTEND_CODE, PARTI_CODE, ATTEND_DATE, CLOCK_IN, CLOCK_OUT)
    VALUES('AT'|| STUDY_ATT_SEQ.NEXTVAL, 'PT1', 날짜, 출석시작, 종료);
    
-- 일정관리
INSERT INTO TBL_STUDY_SCHEDULE(ATTEND_CODE, SCHEDULE)
    VALUES('SC'|| STUDY_SCHE_SEQ.NEXTVAL, '자바 반복문까지');
    
-- 외출등록
INSERT INTO TBL_STUDY_STEPOUT(ATTEND_CODE, CLOCK_IN, CLOCK_OUT)
    VALUES('SO'|| STUDY_STO_SEQ.NEXTVAL, 외출시작, 종료시간);
    
-- 스터디원평가등록
INSERT INTO TBL_STUDY_INTERASSESS(INTERASSESS_CODE, PARTI_CODE, RESP_CODE, ITEM_CODE, INTERASSESS_DATE)
    VALUES('IA'|| STUDY_IASSE_SEQ.NEXTVAL, 'PT1', 'AR1', 'AI1', 날짜);
    
-- 평가 점수
INSERT INTO TBL_STUDY_ASSESS_RESP(RESP_CODE, RESP, SCORE)
    VALUES('AR'|| STUDY_ASSE_RESP_SEQ.NEXTVAL, '매우 그렇다.', 100);
    
-- 평가 항목
INSERT INTO TBL_STUDY_ASSESS_ITEM(ITEM_CODE, ITEM)
    VALUES('AI'|| STUDY_ASSE_ITM_SEQ.NEXTVAL, '성실하다');
    
-- 점수 기록
INSERT INTO TBL_SCORE(SCORE_CODE, USER_CODE, SCORE, SCORE_DATE)
    VALUES('SR'|| STUDY_SCOR_SEQ.NEXTVAL, 유저코드, 점수, 시간);
    
-- 경고 등록
INSERT INTO TBL_WARNING(WARNING_CODE, WARNING_DATE, USER_CODE)
    VALUES('WR'|| STUDY_WARN_SEQ.NEXTVAL, 경고등록날, 유저코드);
    
-- 스터디 댓글
INSERT INTO TBL_COMMENT_STUDY(COMMENT_CODE, STUDY_CODE, COMMENTS, USER_CODE, WRITE_DATE)
    VALUES('SM'|| COMM_STD_SEQ.NEXTVAL, 스터디코드, '1시간만 당겨주시면 안될까요?', 유저코드, 작성날);