

-- 요일 테이블 데이터 입력
INSERT INTO TBL_WEEKDAY(WEEKDAY_CODE, WEEKDAY) VALUES('WD'||WEEKDAY_SEQ.NEXTVAL, '월');
INSERT INTO TBL_WEEKDAY(WEEKDAY_CODE, WEEKDAY) VALUES('WD'||WEEKDAY_SEQ.NEXTVAL, '화');
INSERT INTO TBL_WEEKDAY(WEEKDAY_CODE, WEEKDAY) VALUES('WD'||WEEKDAY_SEQ.NEXTVAL, '수');
INSERT INTO TBL_WEEKDAY(WEEKDAY_CODE, WEEKDAY) VALUES('WD'||WEEKDAY_SEQ.NEXTVAL, '목');
INSERT INTO TBL_WEEKDAY(WEEKDAY_CODE, WEEKDAY) VALUES('WD'||WEEKDAY_SEQ.NEXTVAL, '금');
INSERT INTO TBL_WEEKDAY(WEEKDAY_CODE, WEEKDAY) VALUES('WD'||WEEKDAY_SEQ.NEXTVAL, '토');
INSERT INTO TBL_WEEKDAY(WEEKDAY_CODE, WEEKDAY) VALUES('WD'||WEEKDAY_SEQ.NEXTVAL, '일');
--==>> 입력 완.

SELECT *
FROM TBL_WEEKDAY
ORDER BY 1;



-- 인원수 테이블 데이터 입력
INSERT INTO TBL_MEMNUM(MEMNUM_CODE, MEMNUM) VALUES('MN'||MEMNUM_SEQ.NEXTVAL, 3);
INSERT INTO TBL_MEMNUM(MEMNUM_CODE, MEMNUM) VALUES('MN'||MEMNUM_SEQ.NEXTVAL, 4);
INSERT INTO TBL_MEMNUM(MEMNUM_CODE, MEMNUM) VALUES('MN'||MEMNUM_SEQ.NEXTVAL, 5);
INSERT INTO TBL_MEMNUM(MEMNUM_CODE, MEMNUM) VALUES('MN'||MEMNUM_SEQ.NEXTVAL, 6);
INSERT INTO TBL_MEMNUM(MEMNUM_CODE, MEMNUM) VALUES('MN'||MEMNUM_SEQ.NEXTVAL, 7);
INSERT INTO TBL_MEMNUM(MEMNUM_CODE, MEMNUM) VALUES('MN'||MEMNUM_SEQ.NEXTVAL, 8);
--==>> 입력 완.

SELECT *
FROM TBL_MEMNUM
ORDER BY 1;



-- 등급 테이블 데이터 입력
INSERT INTO TBL_USER_RANK(RANK_CODE, RANK, MIN_SCORE, MAX_SCORE)
VALUES('UR'||USER_RANK_SEQ.NEXTVAL, 1, 12600, 18600);
INSERT INTO TBL_USER_RANK(RANK_CODE, RANK, MIN_SCORE, MAX_SCORE)
VALUES('UR'||USER_RANK_SEQ.NEXTVAL, 2, 7800, 12599);
INSERT INTO TBL_USER_RANK(RANK_CODE, RANK, MIN_SCORE, MAX_SCORE)
VALUES('UR'||USER_RANK_SEQ.NEXTVAL, 3, 4200, 7799);
INSERT INTO TBL_USER_RANK(RANK_CODE, RANK, MIN_SCORE, MAX_SCORE)
VALUES('UR'||USER_RANK_SEQ.NEXTVAL, 4, 1800, 4199);
INSERT INTO TBL_USER_RANK(RANK_CODE, RANK, MIN_SCORE, MAX_SCORE)
VALUES('UR'||USER_RANK_SEQ.NEXTVAL, 5, 600, 1799);
INSERT INTO TBL_USER_RANK(RANK_CODE, RANK, MIN_SCORE, MAX_SCORE)
VALUES('UR'||USER_RANK_SEQ.NEXTVAL, 6, 0, 599);
-->> 입력 완.
SELECT *
FROM TBL_USER_RANK;

-- 스터디 유형 테이블 데이터 입력
INSERT INTO TBL_STUDY_TYPE(STUDY_TYPE_CODE, STUDY_TYPE) VALUES('ST'||STD_TYPE_SEQ.NEXTVAL, '면접');
INSERT INTO TBL_STUDY_TYPE(STUDY_TYPE_CODE, STUDY_TYPE) VALUES('ST'||STD_TYPE_SEQ.NEXTVAL, '자격증');
INSERT INTO TBL_STUDY_TYPE(STUDY_TYPE_CODE, STUDY_TYPE) VALUES('ST'||STD_TYPE_SEQ.NEXTVAL, '프로그래밍언어');
INSERT INTO TBL_STUDY_TYPE(STUDY_TYPE_CODE, STUDY_TYPE) VALUES('ST'||STD_TYPE_SEQ.NEXTVAL, '알고리즘');
INSERT INTO TBL_STUDY_TYPE(STUDY_TYPE_CODE, STUDY_TYPE) VALUES('ST'||STD_TYPE_SEQ.NEXTVAL, '취업관련');
INSERT INTO TBL_STUDY_TYPE(STUDY_TYPE_CODE, STUDY_TYPE) VALUES('ST'||STD_TYPE_SEQ.NEXTVAL, '기타');
--==>> 입력 완.
SELECT *
FROM TBL_STUDY_TYPE;



-- 관심분야 대분류 테이블 데이터 입력
INSERT INTO TBL_INTEREST_LC(INTEREST_LC_CODE, INTEREST_LC) VALUES('IL'||INTER_LC_SEQ.NEXTVAL, '정보기술전략·계획');
INSERT INTO TBL_INTEREST_LC(INTEREST_LC_CODE, INTEREST_LC) VALUES('IL'||INTER_LC_SEQ.NEXTVAL, '정보기술개발');
INSERT INTO TBL_INTEREST_LC(INTEREST_LC_CODE, INTEREST_LC) VALUES('IL'||INTER_LC_SEQ.NEXTVAL, '정보기술운영');
INSERT INTO TBL_INTEREST_LC(INTEREST_LC_CODE, INTEREST_LC) VALUES('IL'||INTER_LC_SEQ.NEXTVAL, '정보기술관리');
INSERT INTO TBL_INTEREST_LC(INTEREST_LC_CODE, INTEREST_LC) VALUES('IL'||INTER_LC_SEQ.NEXTVAL, '정보기술영업');
INSERT INTO TBL_INTEREST_LC(INTEREST_LC_CODE, INTEREST_LC) VALUES('IL'||INTER_LC_SEQ.NEXTVAL, '정보보호');
INSERT INTO TBL_INTEREST_LC(INTEREST_LC_CODE, INTEREST_LC) VALUES('IL'||INTER_LC_SEQ.NEXTVAL, '인공지능');
INSERT INTO TBL_INTEREST_LC(INTEREST_LC_CODE, INTEREST_LC) VALUES('IL'||INTER_LC_SEQ.NEXTVAL, '블록체인');
--==>> 입력 완.
SELECT *
FROM TBL_INTEREST_LC
ORDER BY INTEREST_LC_CODE;



-- 관심분야 중분류 테이블 데이터 입력
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '정보기술전략', 'IL1');        -- 대분류 정보기술전략·계획 참조
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '정보기술컨설팅', 'IL1');        
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '정보기술기획', 'IL1');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'SW제품기획', 'IL1');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '빅데이터분석', 'IL1');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'IOT융합서비스기획', 'IL1');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '빅데이터기획', 'IL1');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '핀테크기술기획', 'IL1');
--==>> 1 행 이(가) 삽입되었습니다. * 8
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'SW아키텍처', 'IL2');       -- 대분류 정보기술개발 참조
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '응용SW엔지니어링', 'IL2');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '임베디드SW엔지니어링', 'IL2');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'DB엔지니어링', 'IL2');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'NW엔지니어링', 'IL2');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '보안엔지니어링', 'IL2');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'UI/UX엔지니어링', 'IL2');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '시스템SW엔지니어링', 'IL2');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '빅데이터플랫폼구축', 'IL2');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '핀테크엔지니어링', 'IL2');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '데이터아키텍처', 'IL2');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'IoT시스템연동', 'IL2');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '인프라스트럭쳐아키텍처구축', 'IL2');
--==>> 1 행 이(가) 삽입되었습니다. * 13
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'IT시스템관리', 'IL3'); -- 대분류 정보기술운영 참조
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'IT기술교육', 'IL3'); 
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'IT기술지원', 'IL3'); 
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '빅데이터운영관리', 'IL3'); 
--==>> 1 행 이(가) 삽입되었습니다. * 4
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'IT프로젝트관리', 'IL4'); -- 대분류 정보기술관리 참조
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'IT품질보증', 'IL4'); 
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'IT테스트', 'IL4'); 
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'IT감리', 'IL4'); 
--==>> 1 행 이(가) 삽입되었습니다. * 4
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'IT기술영업', 'IL5');    -- 대분류 정보기술영업 참조
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, 'IT마케팅', 'IL5');
--==>> 1 행 이(가) 삽입되었습니다. * 2
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '정보보호관리·운영', 'IL6'); -- 대분류 정보보호 참조
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '정보보호진단분석', 'IL6');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '보안사고분석대응', 'IL6');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '정보보호암호인증', 'IL6');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '지능형영상정보처리', 'IL6');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '생체인식(바이오인식)', 'IL6');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '개인정보보호', 'IL6');
--==>> 1 행 이(가) 삽입되었습니다. * 7
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '인공지능플랫폼구축', 'IL7'); -- 대분류 인공지능 참조
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '인공지능서비스기획', 'IL7');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '인공지능모델링', 'IL7');
--==>> 1 행 이(가) 삽입되었습니다. * 3
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '블록체인분석·설계', 'IL8'); -- 대분류 블록체인 참조
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '블록체인구축운영', 'IL8');
INSERT INTO TBL_INTEREST_MC(INTEREST_MC_CODE, INTEREST_MC, INTEREST_LC_CODE) 
VALUES('IM'||INTER_MC_SEQ.NEXTVAL, '블록체인서비스기획', 'IL8');
--==>> 1 행 이(가) 삽입되었습니다. * 3
SELECT *
FROM TBL_INTEREST_MC
ORDER BY TO_NUMBER(SUBSTR(INTEREST_MC_CODE, 3));



-- 지역 대분류 테이블 데이터 입력
INSERT INTO TBL_LOC_LC(LOC_LC_CODE, LOC_LC) VALUES('LL'||LOC_LC_SEQ.NEXTVAL, '서울');
INSERT INTO TBL_LOC_LC(LOC_LC_CODE, LOC_LC) VALUES('LL'||LOC_LC_SEQ.NEXTVAL, '경기');
INSERT INTO TBL_LOC_LC(LOC_LC_CODE, LOC_LC) VALUES('LL'||LOC_LC_SEQ.NEXTVAL, '광역시·도');
INSERT INTO TBL_LOC_LC(LOC_LC_CODE, LOC_LC) VALUES('LL'||LOC_LC_SEQ.NEXTVAL, '온라인');
--==>> 입력 완.
SELECT *
FROM TBL_LOC_LC
ORDER BY 1;


-- 지역 중분류 테이블 데이터 입력
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '은평구/서대문구/마포구', 'LL1'); -- 대분류 서울 참조
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '종로구/중구/용산구', 'LL1');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '도봉구/강북구/성북구/노원구', 'LL1');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '동대문구/중랑구/성동구/광진구', 'LL1');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '강서구/양천구', 'LL1');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '영등포구/구로구/금천구', 'LL1');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '동작구/관악구', 'LL1');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '서초구/강남구', 'LL1');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '송파구/강동구', 'LL1');
--==>> 1 행 이(가) 삽입되었습니다. * 9
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '수원시', 'LL2');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '고양시', 'LL2');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '용인시', 'LL2');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '성남시', 'LL2');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '부천시', 'LL2');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '화성시', 'LL2');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '남양주시', 'LL2');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '안산시', 'LL2');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '안양시', 'LL2');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '기타', 'LL2');
--==>> 1 행 이(가) 삽입되었습니다.
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '충청도', 'LL3');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '경상도', 'LL3');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '전라도', 'LL3');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '강원도', 'LL3');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '인천', 'LL3');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '대전', 'LL3');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '광주', 'LL3');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '대구', 'LL3');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '울산', 'LL3');
INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '부산', 'LL3');
--==>> 1 행 이(가) 삽입되었습니다.



--○ 스터디1, 종료된 것
-- 진행 요일 : 월 3~5,수 7~9
INSERT INTO TBL_STUDY_OPEN
( STUDY_CODE, USER_CODE
, WRITE_DATE
, STUDY_TYPE_CODE, INTEREST_MC_CODE
, START_DATE
, END_DATE
, MIN_MEM_CODE, MAX_MEM_CODE
, MIN_RANK, CLOSE_DATE
, STUDY_NAME, STUDY_DESC, LOC_MC_CODE)
VALUES
( 'SO'||STD_OPEN_SEQ.NEXTVAL, 'UC1'     --사용자1(박혜인)의 유저코드
, TO_DATE('2020-12-01', 'YYYY-MM-DD')   -- 작성일
, 'ST1', 'IM1'                          -- 스터티타입:면접, 관심분야중분류:IT마케팅
, TO_DATE('2020-12-16', 'YYYY-MM-DD')   -- 시작일
, TO_DATE('2020-12-30', 'YYYY-MM-DD')   -- 종료일
, 'MN1', 'MN2'                          -- 3~4명
, 'UR4', TO_DATE('2020-12-16', 'YYYY-MM-DD')
, '카카오톡 개발자 공채 면접 준비', '함께 면접 준비하실분!!!'
, 'LM1'                                -- 은평구/서대문구/마포구
);   

-- 진행요일
INSERT INTO TBL_STUDY_MEETDAY (MEETDAY_CODE, WEEKDAY_CODE, STUDY_CODE, START_TIME, END_TIME)
VALUES ('MD'|| STD_MEETDAY_SEQ.NEXTVAL,'WD2', 'SO1', '15:00', '17:00');
                                    -- 월   스터디1   오후 3 ~ 5시

INSERT INTO TBL_STUDY_MEETDAY (MEETDAY_CODE, WEEKDAY_CODE, STUDY_CODE, START_TIME, END_TIME) 
VALUES ('MD'|| STD_MEETDAY_SEQ.NEXTVAL,'WD4', 'SO1', '19:00', '21:00');
                                    -- 수   스터디1   오후 7 ~ 9시                                 


--○ 스터디2, 현재 진행 중인 것
-- 진행 요일 : 화 8~9
INSERT INTO TBL_STUDY_OPEN
( STUDY_CODE, USER_CODE
, WRITE_DATE
, STUDY_TYPE_CODE, INTEREST_MC_CODE
, START_DATE
, END_DATE
, MIN_MEM_CODE, MAX_MEM_CODE
, MIN_RANK, CLOSE_DATE
, STUDY_NAME, STUDY_DESC
, LOC_MC_CODE)
VALUES
( 'SO'||STD_OPEN_SEQ.NEXTVAL, 'UC5'     --사용자5(조인경)의 유저코드
, TO_DATE('2020-12-20', 'YYYY-MM-DD')   -- 작성일
, 'ST2', 'IM2'                          -- 스터티타입:자격증, 관심분야중분류:정보기술컨설팅
, TO_DATE('2021-01-04', 'YYYY-MM-DD')   -- 시작일
, TO_DATE('2021-01-18', 'YYYY-MM-DD')   -- 종료일
, 'MN1', 'MN3'                          -- 3~5명
, 'UR4', TO_DATE('2021-01-04', 'YYYY-MM-DD')
, '정보처리기사 자격증 취득 스터디', '스터디로 정처기 박살내실분들!! 성실하신분 환영'
, 'LM2'                                 -- 종로구/중구/용산구
);

-- 진행요일
INSERT INTO TBL_STUDY_MEETDAY (MEETDAY_CODE, WEEKDAY_CODE, STUDY_CODE, START_TIME, END_TIME) 
VALUES ('MD'|| STD_MEETDAY_SEQ.NEXTVAL,'WD3', 'SO2', '20:00', '21:00');
--                                     화   스터디2  오후 8 ~ 9시


--○ 스터디3, 광고 글
-- 진행 요일 : 금 오후 6 ~ 8시
INSERT INTO TBL_STUDY_OPEN
( STUDY_CODE, USER_CODE
, WRITE_DATE
, STUDY_TYPE_CODE, INTEREST_MC_CODE
, START_DATE
, END_DATE
, MIN_MEM_CODE, MAX_MEM_CODE
, MIN_RANK, CLOSE_DATE
, STUDY_NAME, STUDY_DESC
, LOC_MC_CODE)
VALUES
( 'SO'||STD_OPEN_SEQ.NEXTVAL, 'UC7'     --사용자7(김호진)의 유저코드
, TO_DATE('2021-01-08', 'YYYY-MM-DD')   -- 작성일
, 'ST3', 'IM9'                          -- 스터티타입:프로그래밍언어, 관심분야중분류:SW아키텍처
, TO_DATE('2021-01-18', 'YYYY-MM-DD')   -- 시작일
, TO_DATE('2021-02-01', 'YYYY-MM-DD')   -- 종료일
, 'MN1', 'MN6'                          -- 3~8명
, 'UR4', TO_DATE('2021-01-18', 'YYYY-MM-DD')-- 마감일
, '@ㄷh박ㄴr는 ㅋrㅈi노ㅂr다2ya기@', '쪽^박n0!!ㄷh박go_수입@보장!!@'
, 'LM3'                                 -- 도봉구/강북구/성북구/노원구
);
-- 진행요일
INSERT INTO TBL_STUDY_MEETDAY (MEETDAY_CODE, WEEKDAY_CODE, STUDY_CODE, START_TIME, END_TIME) 
VALUES ('MD'|| STD_MEETDAY_SEQ.NEXTVAL,'WD6', 'SO3', '18:00', '20:00');   
--                                    --금   스터디3  오후 6 ~ 8시
















--■ 아직 인서트문 실행 안함 ■--

INSERT INTO TBL_LOC_MC(LOC_MC_CODE, LOC_MC, LOC_LC_CODE)
VALUES('LM'||LOC_MC_SEQ.NEXTVAL, '온라인', 'LL4'); -- 보류











