--○ 회원 코드 생성
INSERT INTO TBL_USER_CODE_CREATE(USER_CODE)
VALUES('UC'||USER_CODE_CRE_SEQ.NEXTVAL);
 
--○ 회원 등록
INSERT INTO TBL_USER_REGISTER(ID,PW,SSN,PW_SRCH_QUE_CODE,PW_SRCH_QUE_ANS,INTEREST_MC_CODE,LOC_MC_CODE,
JOB_MC_CODE,EMAIL,NAME,REGDATE,STUDY_TYPE_CODE)
VALUES('UR'||USER_REG_SEQ.NEXTVAL, khj1234,java006$,'PQ1','비번이거java006$','IM1','LM1'
,'JM1','HJ@naver.com','김호진', SYSDATE,'ST1');

--○ 비밀번호 찾기 질문
INSERT INTO TBL_PW_SEARCH_QUE(PW_SRCH_QUE_CODE, PW_SRCH_QUE)
VALUES('PQ'||PW_SRCH_QUE_SEQ.NEXTVAL,'내가 가장 좋아하는 동물은?');
 
--○ 현재 직업 대분류
INSERT INTO TBL_JOB_LC(JOB_LC_CODE, JOB_LC)
VALUES('JL'||JOB_LC_SEQ.NEXTVAL,'IT-컴퓨터');

--○ 현재 직업 중분류
INSERT INTO TBL_JOB_MC(JOB_MC_CODE, JOB_MC,JOB_LC)
VALUES('JM'||JOB_MC_SEQ.NEXTVAL,'프로그래머');
 
--○ 계정 정지
INSERT INTO TBL_ACCOUNT_SUSPEND(ACCT_SUS_CODE, ACCT_SUS_DATE, WARNING_CODE)
VALUES('AS'||ACCT_SUS_SEQ.NEXTVAL,SYSDATE,'경고코드');
 
--○ 탈퇴 카테고리
INSERT INTO TBL_WITHDRAWAL_CATEGORY(WDL_CTG_CODE, WDL_CTG)
VALUES('WC'||WDL_CTG_SEQ.NEXTVAL,'서비스 불만');

--○ 탈퇴 기록 및 개인정보 보관
INSERT INTO TBL_WITHDRAWAL_INFO(WDL_CODE,WDL_DATE,WDL_CTG_CODE,SSN,USER_CODE,WDL_REASON)
VALUES('WI'||WDL_INFO_SEQ.NEXTVAL,SYSDATE,'WC1','8901021234567','UC1','여러분 안녕히 계세요~ 저는 제 행복을 찾아 떠납니다.');
 
 