--○ 스터디원 신고 카테고리 더미데이터 입력
INSERT INTO TBL_MEM_REPORT_CTG
VALUES('RC'||MEM_RC_SEQ.NEXTVAL, '따돌림');
INSERT INTO TBL_MEM_REPORT_CTG
VALUES('RC'||MEM_RC_SEQ.NEXTVAL, '부정출석');
INSERT INTO TBL_MEM_REPORT_CTG
VALUES('RC'||MEM_RC_SEQ.NEXTVAL, '태도불량');
INSERT INTO TBL_MEM_REPORT_CTG
VALUES('RC'||MEM_RC_SEQ.NEXTVAL, '불쾌감을 주는 언행');
INSERT INTO TBL_MEM_REPORT_CTG
VALUES('RC'||MEM_RC_SEQ.NEXTVAL, '스터디 이외의 목적(다단계,사이비)');
INSERT INTO TBL_MEM_REPORT_CTG
VALUES('RC'||MEM_RC_SEQ.NEXTVAL, '기타');
COMMIT;
SELECT * FROM TBL_MEM_REPORT_CTG;


--○ 스터디원 신고 처리결과 더미데이터 입력
INSERT INTO TBL_MEM_REPORT_HANDLE_RESULT
VALUES('RH'||MEM_RHR_SEQ.NEXTVAL, '경고1회');

INSERT INTO TBL_MEM_REPORT_HANDLE_RESULT
VALUES('RH'||MEM_RHR_SEQ.NEXTVAL, '신고취소');

INSERT INTO TBL_MEM_REPORT_HANDLE_RESULT
VALUES('RH'||MEM_RHR_SEQ.NEXTVAL, '허위신고');

SELECT * FROM TBL_MEM_REPORT_HANDLE_RESULT;

COMMIT;

--○ 스터디원 신고등록 테이블 더미데이터 입력
INSERT INTO TBL_MEM_REPORT_REG(MEM_REPORT_REG_CODE, PARTI_REPORT_CODE
, REPORT_REG_DATE, MEM_REPORT_CTG_CODE, REPORT_REG_REASON, PARTI_REPORTED_CODE) 
VALUES(RR||MEM_RR_SEQ.NEXTVAL, '', SYSDATE, 'RC3', '너무공격적이에요ㅠ', '');

INSERT INTO TBL_MEM_REPORT_REG(MEM_REPORT_REG_CODE, PARTI_REPORT_CODE
, REPORT_REG_DATE, MEM_REPORT_CTG_CODE, REPORT_REG_REASON, PARTI_REPORTED_CODE) 
VALUES(RR||MEM_RR_SEQ.NEXTVAL, '', SYSDATE, 'RC1', '저를 왕따시켜요', '');

INSERT INTO TBL_MEM_REPORT_REG(MEM_REPORT_REG_CODE, PARTI_REPORT_CODE
, REPORT_REG_DATE, MEM_REPORT_CTG_CODE, REPORT_REG_REASON, PARTI_REPORTED_CODE) 
VALUES(RR||MEM_RR_SEQ.NEXTVAL, '', SYSDATE, 'RC5', '몰래 화장실가서 대마초피우는걸 봤어요', '');

INSERT INTO TBL_MEM_REPORT_REG(MEM_REPORT_REG_CODE, PARTI_REPORT_CODE
, REPORT_REG_DATE, MEM_REPORT_CTG_CODE, REPORT_REG_REASON, PARTI_REPORTED_CODE) 
VALUES(RR||MEM_RR_SEQ.NEXTVAL, '', SYSDATE, 'RC4', '입에 걸레를 물었습니다.', '');

SELECT * 
FROM TBL_STUDY_PARTICIPANT;



--○ 스터디원 신고처리 테이블 더미데이터 입력
INSERT INTO TBL_MEM_REPORT_HANDLE(MEM_REPORT_HADLE_CODE, MEM_REPORT_REG_CODE, HANDLE_RESULT)
VALUES('RH'||MEM_RH_SEQ.NEXTVAL, '','RH1');

INSERT INTO TBL_MEM_REPORT_HANDLE(MEM_REPORT_HADLE_CODE, MEM_REPORT_REG_CODE, HANDLE_RESULT)
VALUES('RH'||MEM_RH_SEQ.NEXTVAL, '','RH2');

INSERT INTO TBL_MEM_REPORT_HANDLE(MEM_REPORT_HADLE_CODE, MEM_REPORT_REG_CODE, HANDLE_RESULT)
VALUES('RH'||MEM_RH_SEQ.NEXTVAL, '','RH3');

--○ 내보내기 등록 더미데이터 입력

INSERT INTO TBL_MEM_KICK_REG(MEM_KICK_REG_CODE, PARTI_KICKED_CODE, PARTI_KICK_CODE)
VALUES('KR'||MEM_KR_SEQ.NEXTVAL,'7','6');

INSERT INTO TBL_MEM_KICK_REG(MEM_KICK_REG_CODE, PARTI_KICKED_CODE, PARTI_KICK_CODE)
VALUES('KR'||MEM_KR_SEQ.NEXTVAL,'7','3');

INSERT INTO TBL_MEM_KICK_REG(MEM_KICK_REG_CODE, PARTI_KICKED_CODE, PARTI_KICK_CODE)
VALUES('KR'||MEM_KR_SEQ.NEXTVAL,'7','4');

--○ 내보내기 처리 더미테이터 입력

INSERT INTO TBL_MEM_KICK_HANDLE(MEM_KICK_HANDLE_CODE, MEM_KICK_REG_CODE)
VALUES('KH'||MEM_KH_SEQ.NEXTVAL,'');

INSERT INTO TBL_MEM_KICK_HANDLE(MEM_KICK_HANDLE_CODE, MEM_KICK_REG_CODE)
VALUES('KH'||MEM_KH_SEQ.NEXTVAL,'');

INSERT INTO TBL_MEM_KICK_HANDLE(MEM_KICK_HANDLE_CODE, MEM_KICK_REG_CODE)
VALUES('KH'||MEM_KH_SEQ.NEXTVAL,'');


























