    
-- 직책
INSERT INTO TBL_STUDY_POSITION(POSITION_CODE, POSITION)
    VALUES('SP'|| STUDY_POS_SEQ.NEXTVAL, '리더');
INSERT INTO TBL_STUDY_POSITION(POSITION_CODE, POSITION)
    VALUES('SP'|| STUDY_POS_SEQ.NEXTVAL, '스터디원');
--==>> 1 행 이(가) 삽입되었습니다. 

-- 평가 점수
INSERT INTO TBL_STUDY_ASSESS_RESP(RESP_CODE, RESP, SCORE)
    VALUES('AR'|| STUDY_ASSE_RESP_SEQ.NEXTVAL, '매우 그렇다', 100);
INSERT INTO TBL_STUDY_ASSESS_RESP(RESP_CODE, RESP, SCORE)
    VALUES('AR'|| STUDY_ASSE_RESP_SEQ.NEXTVAL, '그렇다', 80);
INSERT INTO TBL_STUDY_ASSESS_RESP(RESP_CODE, RESP, SCORE)
    VALUES('AR'|| STUDY_ASSE_RESP_SEQ.NEXTVAL, '보통이다', 60);
INSERT INTO TBL_STUDY_ASSESS_RESP(RESP_CODE, RESP, SCORE)
    VALUES('AR'|| STUDY_ASSE_RESP_SEQ.NEXTVAL, '그렇지 않다', 40);
INSERT INTO TBL_STUDY_ASSESS_RESP(RESP_CODE, RESP, SCORE)
    VALUES('AR'|| STUDY_ASSE_RESP_SEQ.NEXTVAL, '매우 그렇지 않다', 20);
--==>> 1 행 이(가) 삽입되었습니다. * 5
ROLLBACK;    
-- 평가 항목
INSERT INTO TBL_STUDY_ASSESS_ITEM(ITEM_CODE, ITEM)
    VALUES('AI'|| STUDY_ASSE_ITM_SEQ.NEXTVAL, '해당 참가자는 과제 등 자신의 할 일을 성실히 수행했나요?');
INSERT INTO TBL_STUDY_ASSESS_ITEM(ITEM_CODE, ITEM)
    VALUES('AI'|| STUDY_ASSE_ITM_SEQ.NEXTVAL, '해당 참가자는 스터디원들을 배려하며 원활한 소통을 위해 노력했나요?');
INSERT INTO TBL_STUDY_ASSESS_ITEM(ITEM_CODE, ITEM)
    VALUES('AI'|| STUDY_ASSE_ITM_SEQ.NEXTVAL, '해당 참가자는 스터디 활동에 능동적으로 참여했나요?');    
--==>> 1 행 이(가) 삽입되었습니다. * 3


-------------------------------------------------------------------------------------------------------------------------


SELECT *
FROM TBL_STUDY_ASSESS_ITEM;
COMMIT;
SELECT *
FROM TBL_STUDY_ASSESS_RESP;
    
-- 스터디 댓글(5)
INSERT INTO TBL_COMMENT_STUDY(COMMENT_CODE, STUDY_CODE, COMMENTS, USER_CODE, WRITE_DATE)
    VALUES('SM'|| COMM_STD_SEQ.NEXTVAL, 'SO4', '1시간만 당겨주시면 안될까요?', 'UC5', TO_DATE('2020-12-17'));
--==>> 1 행 이(가) 삽입되었습니다.

-- 스터디 신청(5)



--EXEC PRC_STD_APPLY_INSERT('SO1', 'UC1', 'SP1');--> 개설하면 자동으로 삽입됨
EXEC PRC_STD_APPLY_INSERT('SO2', 'UC2');
EXEC PRC_STD_APPLY_INSERT('SO2', 'UC3');
EXEC PRC_STD_APPLY_INSERT('SO2', 'UC4');

--EXEC PRC_STD_APPLY_INSERT('SO2', 'UC5', 'SP1');
EXEC PRC_STD_APPLY_INSERT('SO4', 'UC1');
EXEC PRC_STD_APPLY_INSERT('SO4', 'UC3');
EXEC PRC_STD_APPLY_INSERT('SO4', 'UC6');
EXEC PRC_STD_APPLY_INSERT('SO4', 'UC7');

--EXEC PRC_STD_APPLY_INSERT('SO3', 'UC7', 'SP1');
EXEC PRC_STD_APPLY_INSERT('SO3', 'UC6');


INSERT INTO TBL_STUDY_APPLY(APPLY_CODE, STUDY_CODE, USER_CODE, APPLY_DATE, POSITION_CODE)
    VALUES('SA'|| STUDY_APL_SEQ.NEXTVAL, 'SO4', 'UC1', TO_DATE('2020-12-10', 'YYYY-MM-DD'), 'SP2');
INSERT INTO TBL_STUDY_APPLY(APPLY_CODE, STUDY_CODE, USER_CODE, APPLY_DATE, POSITION_CODE)
    VALUES('SA'|| STUDY_APL_SEQ.NEXTVAL, 'SO4', 'UC3', TO_DATE('2020-12-11', 'YYYY-MM-DD'), 'SP2');
INSERT INTO TBL_STUDY_APPLY(APPLY_CODE, STUDY_CODE, USER_CODE, APPLY_DATE, POSITION_CODE)
    VALUES('SA'|| STUDY_APL_SEQ.NEXTVAL, 'SO4', 'UC6', TO_DATE('2020-12-12', 'YYYY-MM-DD'), 'SP2');   
INSERT INTO TBL_STUDY_APPLY(APPLY_CODE, STUDY_CODE, USER_CODE, APPLY_DATE, POSITION_CODE)
    VALUES('SA'|| STUDY_APL_SEQ.NEXTVAL, 'SO4', 'UC7', TO_DATE('2020-12-13', 'YYYY-MM-DD'), 'SP2');    

INSERT INTO TBL_STUDY_APPLY(APPLY_CODE, STUDY_CODE, USER_CODE, APPLY_DATE, POSITION_CODE)
    VALUES('SA'|| STUDY_APL_SEQ.NEXTVAL, 'SO5', 'UC5', TO_DATE('2020-12-20', 'YYYY-MM-DD'), 'SP1');
INSERT INTO TBL_STUDY_APPLY(APPLY_CODE, STUDY_CODE, USER_CODE, APPLY_DATE, POSITION_CODE)
    VALUES('SA'|| STUDY_APL_SEQ.NEXTVAL, 'SO5', 'UC1', TO_DATE('2020-12-21', 'YYYY-MM-DD'), 'SP2');
INSERT INTO TBL_STUDY_APPLY(APPLY_CODE, STUDY_CODE, USER_CODE, APPLY_DATE, POSITION_CODE)
    VALUES('SA'|| STUDY_APL_SEQ.NEXTVAL, 'SO5', 'UC3', TO_DATE('2020-12-22', 'YYYY-MM-DD'), 'SP2');    
INSERT INTO TBL_STUDY_APPLY(APPLY_CODE, STUDY_CODE, USER_CODE, APPLY_DATE, POSITION_CODE)
    VALUES('SA'|| STUDY_APL_SEQ.NEXTVAL, 'SO5', 'UC6', TO_DATE('2020-12-24', 'YYYY-MM-DD'), 'SP2');
INSERT INTO TBL_STUDY_APPLY(APPLY_CODE, STUDY_CODE, USER_CODE, APPLY_DATE, POSITION_CODE)
    VALUES('SA'|| STUDY_APL_SEQ.NEXTVAL, 'SO5', 'UC7', TO_DATE('2020-12-24', 'YYYY-MM-DD'), 'SP2');    
    
INSERT INTO TBL_STUDY_APPLY(APPLY_CODE, STUDY_CODE, USER_CODE, APPLY_DATE, POSITION_CODE)
    VALUES('SA'|| STUDY_APL_SEQ.NEXTVAL, 'SO6', 'UC7', TO_DATE('2021-01-08', 'YYYY-MM-DD'), 'SP1');    
INSERT INTO TBL_STUDY_APPLY(APPLY_CODE, STUDY_CODE, USER_CODE, APPLY_DATE, POSITION_CODE)
    VALUES('SA'|| STUDY_APL_SEQ.NEXTVAL, 'SO6', 'UC6', TO_DATE('2021-01-08', 'YYYY-MM-DD'), 'SP2'); 
--==>> 1 행 이(가) 삽입되었습니다. * 11    



SELECT *
FROM TBL_SCORE;

-- 스터디 취소처리(6) 패널티 확인하기

--스터디2, 사용자4, 마지막2일 : -30
EXEC PRC_INSERT_CANCEL('SA6', TO_DATE('2021-01-26', 'YYYY-MM-DD'), NULL); 

-- 스터디3, 사용자7(개설자) : 개설자, -100 → 6번이 리더로 바뀌는지 확인
EXEC PRC_INSERT_CANCEL('SA2', TO_DATE('2021-01-17', 'YYYY-MM-DD'), NULL); 
-- 스터디3, 사용자6 : 신고로 스터디 삭제됨(자동취소 -0)
EXEC PRC_INSERT_CANCEL('SA2', TO_DATE('2021-01-17', 'YYYY-MM-DD'), 1); 

-- 스터디4, 사용자7
EXEC PRC_INSERT_CANCEL('SA2', TO_DATE('2021-01-17', 'YYYY-MM-DD'), 1); 



/*
INSERT INTO TBL_STUDY_CANCEL(CANCEL_CODE, APPLY_CODE, CANCEL_DATE)
    VALUES('SC'|| STUDY_CANC_SEQ.NEXTVAL, 'SA4', TO_DATE('2020-12-14', 'YYYY-MM-DD'));
    
INSERT INTO TBL_STUDY_CANCEL(CANCEL_CODE, APPLY_CODE, CANCEL_DATE)
    VALUES('SC'|| STUDY_CANC_SEQ.NEXTVAL, 'SA9', TO_DATE('2021-01-01', 'YYYY-MM-DD')); 
INSERT INTO TBL_STUDY_CANCEL(CANCEL_CODE, APPLY_CODE, CANCEL_DATE)
    VALUES('SC'|| STUDY_CANC_SEQ.NEXTVAL, 'SA7', TO_DATE('2021-01-01', 'YYYY-MM-DD'));    
    
INSERT INTO TBL_STUDY_CANCEL(CANCEL_CODE, APPLY_CODE, CANCEL_DATE)
    VALUES('SC'|| STUDY_CANC_SEQ.NEXTVAL, 'SA10', TO_DATE('2021-01-16', 'YYYY-MM-DD'));
INSERT INTO TBL_STUDY_CANCEL(CANCEL_CODE, APPLY_CODE, CANCEL_DATE)
    VALUES('SC'|| STUDY_CANC_SEQ.NEXTVAL, 'SA11', TO_DATE('2021-01-17', 'YYYY-MM-DD'));     
--※ 스터디2의 사용자3과 사용자7은 자동으로 인서트되어야 함.   
--==>> 완료
*/


-- 스터디 진행(6) -- 이거 넣으면 취소처리에 인서트되는지 확인하기
INSERT INTO TBL_STUDY_PARTICIPANT(PARTI_CODE, APPLY_CODE)
    VALUES('PT'|| STUDY_PARTI_SEQ.NEXTVAL, 'SA1');    
INSERT INTO TBL_STUDY_PARTICIPANT(PARTI_CODE, APPLY_CODE)
    VALUES('PT'|| STUDY_PARTI_SEQ.NEXTVAL, 'SA4'); 
INSERT INTO TBL_STUDY_PARTICIPANT(PARTI_CODE, APPLY_CODE)
    VALUES('PT'|| STUDY_PARTI_SEQ.NEXTVAL, 'SA5');     

      --사용자코드5,1,6
INSERT INTO TBL_STUDY_PARTICIPANT(PARTI_CODE, APPLY_CODE)
    VALUES('PT'|| STUDY_PARTI_SEQ.NEXTVAL, 'SA3'); 
INSERT INTO TBL_STUDY_PARTICIPANT(PARTI_CODE, APPLY_CODE)
    VALUES('PT'|| STUDY_PARTI_SEQ.NEXTVAL, 'SA9');    
    INSERT INTO TBL_STUDY_PARTICIPANT(PARTI_CODE, APPLY_CODE)
    VALUES('PT'|| STUDY_PARTI_SEQ.NEXTVAL, 'SA10');    
    
    EXEC PRC_SC_INSERT('SO4');
    COMMIT;
    SELECT *
    FROM TBL_STUDY_PARTICIPANT P JOIN TBL_STUDY_APPLY A
    ON A.APPLY_CODE = P.APPLY_CODE
        LEFT JOIN TBL_STUDY_CANCEL C
        ON C.APPLY_CODE = A.APPLY_CODE;
    
    SELECT *
    FROM TBL_STUDY_CANCEL;
    
    SELECT *
    FROM TBL_WARNING;
    
---------------------------------------
-- 스터디 컨텐츠(7) : 나중에
INSERT INTO TBL_STUDY_CONTENT(CONTENT_CODE, PARTI_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT)
    VALUES('CT'|| STUDY_CON_SEQ.NEXTVAL, 'PT4', TO_DATE('2020-12-15', 'YYYY-MM-DD')-2, 0, '처음 오실 때 준비하실 것', '노트북챙겨오세요. 자기소개도 할거니까 미리 생각해오면 좋겠습니다.');
INSERT INTO TBL_STUDY_CONTENT(CONTENT_CODE, PARTI_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT)
    VALUES('CT'|| STUDY_CON_SEQ.NEXTVAL, 'PT5', TO_DATE('2020-12-17', 'YYYY-MM-DD')+10, 0, '오늘공부한거정리해봤어요.', 'PROGRAMMER_A.TSTORY.COM/오늘공부 ←이 링크로 오시면 됩니다.');
    
INSERT INTO TBL_STUDY_CONTENT(CONTENT_CODE, PARTI_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT)
    VALUES('CT'|| STUDY_CON_SEQ.NEXTVAL, 'PT1', TO_DATE('2021-01-25', 'YYYY-MM-DD')+4, 0, '처음올리네요', '스터디리더인데 이제야 처음 올리네요..ㅠㅠ 다음시간까지 이거랑 저거랑 공부할테니 예습 해옵시다!');    
INSERT INTO TBL_STUDY_CONTENT(CONTENT_CODE, PARTI_CODE, WRITE_DATE, HITCOUNT, TITLE, CONTENT)
    VALUES('CT'|| STUDY_CON_SEQ.NEXTVAL, 'PT3', TO_DATE('2021-01-16', 'YYYY-MM-DD')+7, 0, '안녕하세요', '여기 제가 발견한 사이트인데 너무 좋아요. 한 번 둘러보세요. WWW.STUDY_IT.COM');
    
    -- SO4(12/30) : SA3(1), 9(3), 10(6), 11(7,취소), PT4, 5, 6
-- 스터디 평가(7) : 
INSERT INTO TBL_STUDY_ASSESS(ASSESS_CODE, PARTI_CODE, SCORE, ASSESS_DATE)
    VALUES('AS'|| STUDY_ASSE_SEQ.NEXTVAL, 'PT4', 5, TO_DATE('2020-12-30', 'YYYY-MM-DD')+1);
INSERT INTO TBL_STUDY_ASSESS(ASSESS_CODE, PARTI_CODE, SCORE, ASSESS_DATE)
    VALUES('AS'|| STUDY_ASSE_SEQ.NEXTVAL, 'PT5', 4.5, TO_DATE('2020-12-30', 'YYYY-MM-DD')+1);
INSERT INTO TBL_STUDY_ASSESS(ASSESS_CODE, PARTI_CODE, SCORE, ASSESS_DATE)
    VALUES('AS'|| STUDY_ASSE_SEQ.NEXTVAL, 'PT6', 4, TO_DATE('2020-12-30', 'YYYY-MM-DD')+1);    

SELECT *
FROM TBL_STUDY_ASSESS;


-- 출석부(7) - 스터디1(월/수 총4회) - 3번 지각1,결석1-4회모두완료. 
INSERT INTO TBL_STUDY_ATTEND(ATTEND_CODE, PARTI_CODE, ATTEND_DATE, CLOCK_IN, CLOCK_OUT)
    VALUES('AT'|| STUDY_ATT_SEQ.NEXTVAL, 'PT1', TO_DATE('2020-12-30', 'YYYY-MM-DD'), TO_DATE('2020-12-30 18:20', 'YYYY-MM-DD HH24:MI'), NULL);
    
SELECT *
FROM TBL_STUDY_ATTEND;

EXEC PRC_STD_ATND('SO2','AT3','PT1',TO_DATE('2020-12-30 21:00', 'YYYY-MM-DD HH24:MI'));

INSERT INTO TBL_STUDY_ATTEND(ATTEND_CODE, PARTI_CODE, ATTEND_DATE, CLOCK_IN, CLOCK_OUT)
    VALUES('AT'|| STUDY_ATT_SEQ.NEXTVAL, 'PT4', TO_DATE('2021-02-30', 'YYYY-MM-DD'), TO_DATE('2020-12-30 18:20', 'YYYY-MM-DD HH24:MI'), NULL);
    
    
INSERT INTO TBL_STUDY_ATTEND(ATTEND_CODE, PARTI_CODE, ATTEND_DATE, CLOCK_IN, CLOCK_OUT)
    VALUES('AT'|| STUDY_ATT_SEQ.NEXTVAL, 'PT4', TO_DATE('2020-12-22', 'YYYY-MM-DD'), TO_DATE('15:00', 'HH24:MI'), NULL);
INSERT INTO TBL_STUDY_ATTEND(ATTEND_CODE, PARTI_CODE, ATTEND_DATE, CLOCK_IN, CLOCK_OUT)
    VALUES('AT'|| STUDY_ATT_SEQ.NEXTVAL, 'PT4', TO_DATE('2020-12-29', 'YYYY-MM-DD'), TO_DATE('15:10', 'HH24:MI'), NULL);
EXEC PRC_STD_ATND('SO4','AT18','PT4',TO_DATE('17:10', 'HH24:MI'));
EXEC PRC_STD_ATND('SO4','AT19','PT4',TO_DATE('17:11', 'HH24:MI'));

INSERT INTO TBL_STUDY_ATTEND(ATTEND_CODE, PARTI_CODE, ATTEND_DATE, CLOCK_IN, CLOCK_OUT)
    VALUES('AT'|| STUDY_ATT_SEQ.NEXTVAL, 'PT5', TO_DATE('2020-12-22', 'YYYY-MM-DD'), TO_DATE('15:00', 'HH24:MI'), NULL);
INSERT INTO TBL_STUDY_ATTEND(ATTEND_CODE, PARTI_CODE, ATTEND_DATE, CLOCK_IN, CLOCK_OUT)
    VALUES('AT'|| STUDY_ATT_SEQ.NEXTVAL, 'PT5', TO_DATE('2020-12-29', 'YYYY-MM-DD'), TO_DATE('15:00', 'HH24:MI'), NULL);
EXEC PRC_STD_ATND('SO4','AT20','PT5',TO_DATE('17:00', 'HH24:MI'));
EXEC PRC_STD_ATND('SO4','AT21','PT5',TO_DATE('16:40', 'HH24:MI'));

INSERT INTO TBL_STUDY_ATTEND(ATTEND_CODE, PARTI_CODE, ATTEND_DATE, CLOCK_IN, CLOCK_OUT)
    VALUES('AT'|| STUDY_ATT_SEQ.NEXTVAL, 'PT6', TO_DATE('2020-12-22', 'YYYY-MM-DD'), TO_DATE('15:00', 'HH24:MI'), NULL);
INSERT INTO TBL_STUDY_ATTEND(ATTEND_CODE, PARTI_CODE, ATTEND_DATE, CLOCK_IN, CLOCK_OUT)
    VALUES('AT'|| STUDY_ATT_SEQ.NEXTVAL, 'PT6', TO_DATE('2020-12-29', 'YYYY-MM-DD'), TO_DATE('15:15', 'HH24:MI'), NULL);
EXEC PRC_STD_ATND('SO4','AT22','PT6',TO_DATE('17:01', 'HH24:MI'));   
EXEC PRC_STD_ATND('SO4','AT23','PT6',TO_DATE('16:30', 'HH24:MI'));

SELECT *
FROM TBL_STUDY_ATTEND;
COMMIT;    
SELECT *
FROM TBL_SCORE
ORDER BY 1;

DELETE
FROM TBL_SCORE
WHERE SCORE_CODE < 'SR7';

SELECT *
FROM TBL_STUDY_PARTICIPANT;

DELETE
FROM TBL_STUDY_ATTEND
WHERE ATTEND_CODE < 'AT3';

SELECT *
FROM TBL_STUDY_MEETDAY;

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TBL_STUDY_ATTEND';

DELETE TBL_STUDY_MEETDAY
WHERE MEETDAY_CODE = 'MD5';

COMMIT;

SELECT *
FROM TIME_CHECK_VIEW;

SELECT P.PARTI_CODE, C.USER_CODE
FROM TBL_STUDY_APPLY A JOIN TBL_STUDY_PARTICIPANT P
 ON A.APPLY_CODE = P.APPLY_CODE
 JOIN TBL_USER_CODE_CREATE C
 ON C.USER_CODE =A.USER_CODE;

---------------스터디2(화, 총2회) - 6번이 한 번 조퇴, 1회만진행함.    
INSERT INTO TBL_STUDY_ATTEND(ATTEND_CODE, PARTI_CODE, ATTEND_DATE, CLOCK_IN, CLOCK_OUT)
    VALUES('AT'|| STUDY_ATT_SEQ.NEXTVAL, 'PT4', EXEC PRC_STD_ATND('SO5','AT12','PT12',TO_DATE('21:00','HH24:MI'));, 시작시간, 종료);    
INSERT INTO TBL_STUDY_ATTEND(ATTEND_CODE, PARTI_CODE, ATTEND_DATE, CLOCK_IN, CLOCK_OUT)
    VALUES('AT'|| STUDY_ATT_SEQ.NEXTVAL, 'PT5', 1회, 시작시간, 종료); 
INSERT INTO TBL_STUDY_ATTEND(ATTEND_CODE, PARTI_CODE, ATTEND_DATE, CLOCK_IN, CLOCK_OUT)
    VALUES('AT'|| STUDY_ATT_SEQ.NEXTVAL, 'PT6', 1회, 시작시간, NULL);     

-- 종료시간 업데이트
-----정상종료(점수 안깎여야 함.)
UPDATE TBL_STUDY_ATTEND
SET CLOCK_OUT = 종료시간
WHERE ATTEND_CODE = 'AT1';
-----조퇴(5점 감점 업데이트 되어야 함.)
UPDATE TBL_STUDY_ATTEND
SET CLOCK_OUT = 종료시간
WHERE ATTEND_CODE = 'AT10';
-----지각(5점 감점 업데이트 되어야 함.)
UPDATE TBL_STUDY_ATTEND
SET CLOCK_OUT = 종료시간-30분
WHERE ATTEND_CODE = 'AT14';

SELECT *
FROM TBL_STUDY_PARTICIPANT P JOIN TBL_STUDY_APPLY A
 ON A.APPLY_CODE = P.APPLY_CODE
     LEFT JOIN TBL_STUDY_CANCEL C
     ON C.APPLY_CODE = A.APPLY_CODE;

SELECT *
FROM TBL_ACCOUNT_SUSPEND;

SELECT *
FROM TBL_WARNING;

SELECT *
FROM TBL_SCORE
WHERE USER_CODE = 'UC7'; 

EXEC PRC_INSERT_WARNING('UC7', SYSDATE-370);

INSERT INTO TBL_SCORE (SCORE_CODE, USER_CODE, SCORE, SCORE_DATE) VALUES('SC'||STUDY_SCOR_SEQ.NEXTVAL, 'UC7', 1800, SYSDATE-400);
SELECT *
FROM USER_SEQUENCES;

SELECT *
FROM TBL_STUDY_PARTICIPANT;
    
-- 스터디원평가등록(7) -- 3명 중 1은 다 함. 2는 다 안함. 3은 아예 안했지만 점수가 음수.
-- 이거 넣어보고 1과 3에게만 점수 반영되는지 확인.
--종료된스터디에서 1(두명분)
INSERT INTO TBL_STUDY_INTERASSESS(INTERASSESS_CODE, PARTI_ASSESS_CODE, RESP_CODE, ITEM_CODE, PARTI_ASSESSED_CODE, INTERASSESS_DATE)
    VALUES('IA'|| STUDY_IASSE_SEQ.NEXTVAL, 'PT4', 'AR1', 'AI1', 'PT5', TO_DATE('2020-12-29', 'YYYY-MM-DD')+1);
INSERT INTO TBL_STUDY_INTERASSESS(INTERASSESS_CODE, PARTI_ASSESS_CODE, RESP_CODE, ITEM_CODE, PARTI_ASSESSED_CODE, INTERASSESS_DATE)
    VALUES('IA'|| STUDY_IASSE_SEQ.NEXTVAL, 'PT4', 'AR1', 'AI2', 'PT5', TO_DATE('2020-12-29', 'YYYY-MM-DD')+1);
INSERT INTO TBL_STUDY_INTERASSESS(INTERASSESS_CODE, PARTI_ASSESS_CODE, RESP_CODE, ITEM_CODE, PARTI_ASSESSED_CODE, INTERASSESS_DATE)
    VALUES('IA'|| STUDY_IASSE_SEQ.NEXTVAL, 'PT4', 'AR2', 'AI3', 'PT5', TO_DATE('2020-12-29', 'YYYY-MM-DD')+1);   
    
INSERT INTO TBL_STUDY_INTERASSESS(INTERASSESS_CODE, PARTI_ASSESS_CODE, RESP_CODE, ITEM_CODE, PARTI_ASSESSED_CODE, INTERASSESS_DATE)
    VALUES('IA'|| STUDY_IASSE_SEQ.NEXTVAL, 'PT4', 'AR5', 'AI1', 'PT6', TO_DATE('2020-12-29', 'YYYY-MM-DD')+1);
INSERT INTO TBL_STUDY_INTERASSESS(INTERASSESS_CODE, PARTI_ASSESS_CODE, RESP_CODE, ITEM_CODE, PARTI_ASSESSED_CODE, INTERASSESS_DATE)
    VALUES('IA'|| STUDY_IASSE_SEQ.NEXTVAL, 'PT4', 'AR4', 'AI2', 'PT6', TO_DATE('2020-12-29', 'YYYY-MM-DD')+1);
INSERT INTO TBL_STUDY_INTERASSESS(INTERASSESS_CODE, PARTI_ASSESS_CODE, RESP_CODE, ITEM_CODE, PARTI_ASSESSED_CODE, INTERASSESS_DATE)
    VALUES('IA'|| STUDY_IASSE_SEQ.NEXTVAL, 'PT4', 'AR4', 'AI3', 'PT6', TO_DATE('2020-12-29', 'YYYY-MM-DD')+1);       

-- 한명만 평가 + 양수
INSERT INTO TBL_STUDY_INTERASSESS(INTERASSESS_CODE, PARTI_ASSESS_CODE, RESP_CODE, ITEM_CODE, PARTI_ASSESSED_CODE, INTERASSESS_DATE)
    VALUES('IA'|| STUDY_IASSE_SEQ.NEXTVAL, 'PT5', 'AR1', 'AI1', 'PT4', TO_DATE('2020-12-29', 'YYYY-MM-DD')+1);
INSERT INTO TBL_STUDY_INTERASSESS(INTERASSESS_CODE, PARTI_ASSESS_CODE, RESP_CODE, ITEM_CODE, PARTI_ASSESSED_CODE, INTERASSESS_DATE)
    VALUES('IA'|| STUDY_IASSE_SEQ.NEXTVAL, 'PT5', 'AR1', 'AI2', 'PT4', TO_DATE('2020-12-29', 'YYYY-MM-DD')+1);
INSERT INTO TBL_STUDY_INTERASSESS(INTERASSESS_CODE, PARTI_ASSESS_CODE, RESP_CODE, ITEM_CODE, PARTI_ASSESSED_CODE, INTERASSESS_DATE)
    VALUES('IA'|| STUDY_IASSE_SEQ.NEXTVAL, 'PT5', 'AR3', 'AI3', 'PT4', TO_DATE('2020-12-29', 'YYYY-MM-DD')+1);   

--한 명에 대해서만 평가 + 음수
INSERT INTO TBL_STUDY_INTERASSESS(INTERASSESS_CODE, PARTI_ASSESS_CODE, RESP_CODE, ITEM_CODE, PARTI_ASSESSED_CODE, INTERASSESS_DATE)
    VALUES('IA'|| STUDY_IASSE_SEQ.NEXTVAL, 'PT6', 'AR3', 'AI1', 'PT4', TO_DATE('2020-12-29', 'YYYY-MM-DD')+1);
INSERT INTO TBL_STUDY_INTERASSESS(INTERASSESS_CODE, PARTI_ASSESS_CODE, RESP_CODE, ITEM_CODE, PARTI_ASSESSED_CODE, INTERASSESS_DATE)
    VALUES('IA'|| STUDY_IASSE_SEQ.NEXTVAL, 'PT6', 'AR2', 'AI2', 'PT4', TO_DATE('2020-12-29', 'YYYY-MM-DD')+1);
INSERT INTO TBL_STUDY_INTERASSESS(INTERASSESS_CODE, PARTI_ASSESS_CODE, RESP_CODE, ITEM_CODE, PARTI_ASSESSED_CODE, INTERASSESS_DATE)
    VALUES('IA'|| STUDY_IASSE_SEQ.NEXTVAL, 'PT6', 'AR1', 'AI3', 'PT4', TO_DATE('2020-12-29', 'YYYY-MM-DD')+1);           
SET SERVEROUTPUT ON;

EXEC PRC_2WEEKS_CHK('SO4',TO_DATE('2020-12-29', 'YYYY-MM-DD')+30, 'PT6');

-- 점수 기록(8) --> 글 인서트 될 때 자동 인서트.
INSERT INTO TBL_SCORE(SCORE_CODE, USER_CODE, SCORE, SCORE_DATE)
    VALUES('SR'|| STUDY_SCOR_SEQ.NEXTVAL, 유저코드, 점수, 시간);


-- 경고 등록(4) - 3개-> 계정정지에 INSERT 되는지 확인

EXEC PRC_INSERT_WARNING('UC7', SYSDATE-3);
EXEC PRC_INSERT_WARNING('UC7', SYSDATE-2);
EXEC PRC_INSERT_WARNING('UC7', SYSDATE);

INSERT INTO TBL_WARNING(WARNING_CODE, WARNING_DATE, USER_CODE)
    VALUES('WR'|| STUDY_WARN_SEQ.NEXTVAL, SYSDATE, 'UC7');
INSERT INTO TBL_WARNING(WARNING_CODE, WARNING_DATE, USER_CODE)
    VALUES('WR'|| STUDY_WARN_SEQ.NEXTVAL, SYSDATE, 'UC7');
INSERT INTO TBL_WARNING(WARNING_CODE, WARNING_DATE, USER_CODE)
    VALUES('WR'|| STUDY_WARN_SEQ.NEXTVAL, SYSDATE, 'UC7');   
    

    
-- 외출등록(보류)
INSERT INTO TBL_STUDY_STEPOUT(ATTEND_CODE, CLOCK_IN, CLOCK_OUT)
    VALUES('SO'|| STUDY_STO_SEQ.NEXTVAL, 외출시작, 종료시간);
-- 일정관리(보류)
INSERT INTO TBL_STUDY_SCHEDULE(ATTEND_CODE, SCHEDULE)
    VALUES('SC'|| STUDY_SCHE_SEQ.NEXTVAL, '자바 반복문까지');






------------------------------------------------------------------인경 회원등록
SELECT *
FROM TBL_USER_CODE_CREATE;

SELECT *
FROM TBL_USER_REGISTER
ORDER BY 1;

EXEC PRC_UC_REG_INSERT('phi11','java001$','9301022345678','PQ1','강아지(울집포도)','IM1','LM6','JM1','phi11@gmail.com','박혜인','ST1');
EXEC PRC_UC_REG_INSERT('yhj22','java002$','9401031234567','PQ2','마르게리타피자','IM2','LM6','JM5','yhj22@daum.net','윤홍준','ST2');
EXEC PRC_UC_REG_INSERT('ljj33','java003$','9407082345678','PQ3','아이슬란드','IM3','LM1','JM6','ljj33@gmail.com','이진주','ST3');
EXEC PRC_UC_REG_INSERT('jyw44','java004$','9502031234567','PQ4','반지의 제왕','IM4','LM4','JM8','jyw44@naver.com','조영욱','ST4');
EXEC PRC_UC_REG_INSERT('jik55','java005$','9603142345678','PQ5','해리포터','IM5','LM6','JM5','jik55@nate.com','조인경','ST5');
EXEC PRC_UC_REG_INSERT('hsm66','java006$','9507052345678','PQ6','우리 가족','IM6','LM2','JM6','hsm66@naver.com','허수민','ST6');
EXEC PRC_UC_REG_INSERT('khj77','java007$','8709041234567','PQ7','이순신','IM7','LM6','JM7','khj77@daum.net','김호진','ST1');
EXEC PRC_UC_REG_INSERT('nha88','java008$','8709041234567','PQ7','소크라테스','IM3','LM6','JM7','nha77@daum.net','유연석','ST1');


INSERT INTO TBL_NOTICE(NOTICE_CODE, NOTICE_DATE, NOTICE_TITLE
, NOTICE_CONTENT, ADMIN_CODE, HITCOUNT)
VALUES('NT'||NOTICE_SEQ.NEXTVAL, SYSDATE+5, '스터디 신고 시 유의사항', '스터디원 여러 명이 허위신고를 할 경우 경고 1회의 제재를 받으니 주의하시기 바랍니다.' , 'AD1', 0);
INSERT INTO TBL_NOTICE(NOTICE_CODE, NOTICE_DATE, NOTICE_TITLE
, NOTICE_CONTENT, ADMIN_CODE, HITCOUNT)
VALUES('NT'||NOTICE_SEQ.NEXTVAL, SYSDATE-3, '궁금한 사항은 1:1게시판 이용', '고객센터 1:1질문 게시판을 이용하여 문의해주십시오.' , 'AD2', 0);
COMMIT;
SELECT *
FROM TBL_USER_REGISTER
ORDER BY 1;

SELECT *
FROM TBL_ASK;

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TBL_STUDY_OPEN';

ALTER TABLE TBL_STUDY_OPEN
DROP CONSTRAINT STD_OPEN_SD_CK;

COMMIT;

SELECT *
FROM TBL_NOTICE;