

--■■■ 신고 등록 프로시저 ■■■--
-- 신고 등록 5회 → 마지막 신고 등록 코드로 신고 처리 테이블에 인서트되는 프로시저


--○ 정보공유게시판 신고 등록 테이블에 INSERT 후 -> 5회 쌓였는지 체크 -> 맞으면 신고처리에 인서트

CREATE OR REPLACE PROCEDURE PRC_RPT_REG_INFOM_INSERT
( V_POST_CODE             IN TBL_BOARD_INFORM.POST_CODE%TYPE
, V_USER_CODE             IN TBL_USER_CODE_CREATE.USER_CODE%TYPE
, V_REPORT_REASON         IN TBL_REPORT_REG_INFORM.REPORT_REASON%TYPE
, V_POST_REPORT_CTG_CODE  IN TBL_POST_REPORT_CTG.POST_REPORT_CTG_CODE%TYPE
)
IS
    V_REG_CNT NUMBER;   -- 특정 게시물의 신고를 세는 변수
    V_RPT_RG_INFORM_SEQ TBL_REPORT_REG_INFORM.POST_REPORT_CODE%TYPE;    -- 정보공유 신고등록 SEQ
BEGIN

    V_RPT_RG_INFORM_SEQ := 'GI'||RPT_RG_INFORM_SEQ.NEXTVAL;

    INSERT INTO TBL_REPORT_REG_INFORM
    (POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE)
    VALUES(V_RPT_RG_INFORM_SEQ, V_POST_CODE, V_USER_CODE, SYSDATE, V_REPORT_REASON, V_POST_REPORT_CTG_CODE);

    -- V_REG_CNT 초기화
    SELECT COUNT(*) AS CNT INTO V_REG_CNT
    FROM TBL_REPORT_REG_INFORM
    WHERE POST_CODE = V_POST_CODE;
    
    -- 신고가 5회 쌓였는지 체크후 처리
    IF ( V_REG_CNT = 5) 
        THEN 
        INSERT INTO TBL_REPORT_HANDLE_INFORM (REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
                    VALUES ('HI'||RPT_HD_INFORM_SEQ.NEXTVAL, V_RPT_RG_INFORM_SEQ, NULL, SYSDATE); -- 처리결과코드는 NULL, 처리일자는 디폴트 SYSDATE
    END IF;
    
    -- 커밋
    COMMIT;
    
END;
--==>> Procedure PRC_RPT_REG_INFOM_INSERT이(가) 컴파일되었습니다.





--○ 면접,코딩테스트 게시판 신고 등록 테이블에 INSERT 후 -> 5회 쌓였는지 체크 -> 맞으면 신고처리에 인서트

CREATE OR REPLACE PROCEDURE PRC_RPT_REG_INTERV_INSERT
( V_POST_CODE             IN TBL_BOARD_INTERVIEW.POST_CODE%TYPE
, V_USER_CODE             IN TBL_USER_CODE_CREATE.USER_CODE%TYPE
, V_REPORT_REASON         IN TBL_REPORT_REG_INTERVIEW.REPORT_REASON%TYPE
, V_POST_REPORT_CTG_CODE  IN TBL_POST_REPORT_CTG.POST_REPORT_CTG_CODE%TYPE
)
IS
    V_REG_CNT NUMBER;   -- 특정 게시물의 신고를 세는 변수
    V_RPT_RG_INTERVIEW_SEQ  TBL_REPORT_REG_INFORM.POST_REPORT_CODE%TYPE;    -- 면접후기 신고등록 SEQ
BEGIN

    V_RPT_RG_INTERVIEW_SEQ := 'GV'||RPT_RG_INTERVIEW_SEQ.NEXTVAL;

    INSERT INTO TBL_REPORT_REG_INTERVIEW
    (POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE)
    VALUES(V_RPT_RG_INTERVIEW_SEQ, V_POST_CODE, V_USER_CODE, SYSDATE, V_REPORT_REASON, V_POST_REPORT_CTG_CODE);

    -- V_REG_CNT 초기화
    SELECT COUNT(*) AS CNT INTO V_REG_CNT
    FROM TBL_REPORT_REG_INTERVIEW
    WHERE POST_CODE = V_POST_CODE;
    
    -- 신고가 5회 쌓였는지 체크후 처리
    IF ( V_REG_CNT = 5) 
        THEN 
        INSERT INTO TBL_REPORT_HANDLE_INTERVIEW (REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
                    VALUES ('HV'||RPT_HD_INTERVIEW_SEQ.NEXTVAL, V_RPT_RG_INTERVIEW_SEQ, NULL, SYSDATE); -- 처리결과코드는 NULL, 처리일자는 디폴트 SYSDATE
    END IF;
    
    
    -- 커밋
    COMMIT;
    
END;
--==>> Procedure PRC_RPT_REG_INTERV_INSERT이(가) 컴파일되었습니다.




--○ 공모전/세미나 게시판 신고 등록 테이블에 INSERT 후 -> 5회 쌓였는지 체크 -> 맞으면 신고처리에 인서트

CREATE OR REPLACE PROCEDURE PRC_RPT_REG_SEMINAR_INSERT
( V_POST_CODE             IN TBL_BOARD_SEMINAR.POST_CODE%TYPE
, V_USER_CODE             IN TBL_USER_CODE_CREATE.USER_CODE%TYPE
, V_REPORT_REASON         IN TBL_REPORT_REG_SEMINAR.REPORT_REASON%TYPE
, V_POST_REPORT_CTG_CODE  IN TBL_POST_REPORT_CTG.POST_REPORT_CTG_CODE%TYPE
)
IS
    V_REG_CNT NUMBER;   -- 특정 게시물의 신고를 세는 변수
    V_RPT_RG_SEMINAR_SEQ  TBL_REPORT_REG_INFORM.POST_REPORT_CODE%TYPE; -- 세미나 신고등록 SEQ
BEGIN

    V_RPT_RG_SEMINAR_SEQ := 'GS'||RPT_RG_SEMINAR_SEQ.NEXTVAL;

    INSERT INTO TBL_REPORT_REG_SEMINAR
    (POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE)
    VALUES(V_RPT_RG_SEMINAR_SEQ, V_POST_CODE, V_USER_CODE, SYSDATE, V_REPORT_REASON, V_POST_REPORT_CTG_CODE);

    -- V_REG_CNT 초기화
    SELECT COUNT(*) AS CNT INTO V_REG_CNT
    FROM TBL_REPORT_REG_SEMINAR
    WHERE POST_CODE = V_POST_CODE;
    
    -- 신고가 5회 쌓였는지 체크후 처리
    IF ( V_REG_CNT = 5) 
        THEN 
        INSERT INTO TBL_REPORT_HANDLE_SEMINAR (REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
                    VALUES ('HS'||RPT_HD_SEMINAR_SEQ.NEXTVAL, V_RPT_RG_SEMINAR_SEQ, NULL, SYSDATE); -- 처리결과코드는 NULL, 처리일자는 디폴트 SYSDATE
    END IF;
    
    
    -- 커밋
    COMMIT;
    
END;
--==>> Procedure PRC_RPT_REG_SEMINAR_INSERT이(가) 컴파일되었습니다.




--○ 자유 게시판 신고 등록 테이블에 INSERT 후 -> 5회 쌓였는지 체크 -> 맞으면 신고처리에 인서트

CREATE OR REPLACE PROCEDURE PRC_RPT_REG_FREE_INSERT
( V_POST_CODE             IN TBL_BOARD_FREE.POST_CODE%TYPE
, V_USER_CODE             IN TBL_USER_CODE_CREATE.USER_CODE%TYPE
, V_REPORT_REASON         IN TBL_REPORT_REG_FREE.REPORT_REASON%TYPE
, V_POST_REPORT_CTG_CODE  IN TBL_POST_REPORT_CTG.POST_REPORT_CTG_CODE%TYPE
)
IS
    V_REG_CNT NUMBER;   -- 특정 게시물의 신고를 세는 변수
    V_RPT_RG_FREE_SEQ  TBL_REPORT_REG_FREE.POST_REPORT_CODE%TYPE; -- 자유게시판 신고등록 SEQ
BEGIN

    V_RPT_RG_FREE_SEQ := 'GF'||RPT_RG_FREE_SEQ.NEXTVAL;

    INSERT INTO TBL_REPORT_REG_FREE
    (POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE)
    VALUES(V_RPT_RG_FREE_SEQ, V_POST_CODE, V_USER_CODE, SYSDATE, V_REPORT_REASON, V_POST_REPORT_CTG_CODE);

    -- V_REG_CNT 초기화
    SELECT COUNT(*) AS CNT INTO V_REG_CNT
    FROM TBL_REPORT_REG_FREE
    WHERE POST_CODE = V_POST_CODE;
    
    -- 신고가 5회 쌓였는지 체크후 처리
    IF ( V_REG_CNT = 5) 
        THEN 
        INSERT INTO TBL_REPORT_HANDLE_FREE (REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
                    VALUES ('HF'||RPT_HD_FREE_SEQ.NEXTVAL, V_RPT_RG_FREE_SEQ, NULL, SYSDATE); -- 처리결과코드는 NULL, 처리일자는 디폴트 SYSDATE
    END IF;
    
    
    -- 커밋
    COMMIT;
    
END;
--==>> Procedure PRC_RPT_REG_FREE_INSERT이(가) 컴파일되었습니다.





--○ 질문 게시판 신고 등록 테이블에 INSERT 후 -> 5회 쌓였는지 체크 -> 맞으면 신고처리에 인서트
CREATE OR REPLACE PROCEDURE PRC_RPT_REG_QUE_INSERT
( V_POST_CODE             IN TBL_BOARD_QUESTION.POST_CODE%TYPE
, V_USER_CODE             IN TBL_USER_CODE_CREATE.USER_CODE%TYPE
, V_REPORT_REASON         IN TBL_REPORT_REG_QUESTION.REPORT_REASON%TYPE
, V_POST_REPORT_CTG_CODE  IN TBL_POST_REPORT_CTG.POST_REPORT_CTG_CODE%TYPE
)
IS
    V_REG_CNT NUMBER;   -- 특정 게시물의 신고를 세는 변수
    V_RPT_RG_QUE_SEQ  TBL_REPORT_REG_QUESTION.POST_REPORT_CODE%TYPE; -- 자유게시판 신고등록 SEQ
BEGIN

    V_RPT_RG_QUE_SEQ := 'GQ'||RPT_RG_QUESTION_SEQ.NEXTVAL;

    INSERT INTO TBL_REPORT_REG_QUESTION
    (POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE)
    VALUES(V_RPT_RG_QUE_SEQ, V_POST_CODE, V_USER_CODE, SYSDATE, V_REPORT_REASON, V_POST_REPORT_CTG_CODE);

    -- V_REG_CNT 초기화
    SELECT COUNT(*) AS CNT INTO V_REG_CNT
    FROM TBL_REPORT_REG_QUESTION
    WHERE POST_CODE = V_POST_CODE;
    
    -- 신고가 5회 쌓였는지 체크후 처리
    IF ( V_REG_CNT = 5) 
        THEN 
        INSERT INTO TBL_REPORT_HANDLE_QUESTION (REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
                    VALUES ('HQ'||RPT_HD_QUESTION_SEQ.NEXTVAL, V_RPT_RG_QUE_SEQ, NULL, SYSDATE); -- 처리결과코드는 NULL, 처리일자는 디폴트 SYSDATE
    END IF;
    
    
    -- 커밋
    COMMIT;
    
END;
--==>> Procedure PRC_RPT_REG_QUE_INSERT이(가) 컴파일되었습니다.





--○ 답변 게시판 신고 등록 테이블에 INSERT 후 -> 5회 쌓였는지 체크 -> 맞으면 신고처리에 인서트
CREATE OR REPLACE PROCEDURE PRC_RPT_REG_ANS_INSERT
( V_POST_CODE             IN TBL_BOARD_ANSWER.POST_CODE%TYPE
, V_USER_CODE             IN TBL_USER_CODE_CREATE.USER_CODE%TYPE
, V_REPORT_REASON         IN TBL_REPORT_REG_ANSWER.REPORT_REASON%TYPE
, V_POST_REPORT_CTG_CODE  IN TBL_POST_REPORT_CTG.POST_REPORT_CTG_CODE%TYPE
)
IS
    V_REG_CNT NUMBER;   -- 특정 게시물의 신고를 세는 변수
    V_RPT_RG_ANS_SEQ  TBL_REPORT_REG_ANSWER.POST_REPORT_CODE%TYPE; -- 자유게시판 신고등록 SEQ
BEGIN

    V_RPT_RG_ANS_SEQ := 'GA'||RPT_RG_ANSWER_SEQ.NEXTVAL;

    INSERT INTO TBL_REPORT_REG_ANSWER
    (POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE)
    VALUES(V_RPT_RG_ANS_SEQ, V_POST_CODE, V_USER_CODE, SYSDATE, V_REPORT_REASON, V_POST_REPORT_CTG_CODE);

    -- V_REG_CNT 초기화
    SELECT COUNT(*) AS CNT INTO V_REG_CNT
    FROM TBL_REPORT_REG_ANSWER
    WHERE POST_CODE = V_POST_CODE;
    
    -- 신고가 5회 쌓였는지 체크후 처리
    IF ( V_REG_CNT = 5) 
        THEN 
        INSERT INTO TBL_REPORT_HANDLE_ANSWER (REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
                    VALUES ('HA'||RPT_HD_ANSWER_SEQ.NEXTVAL, V_RPT_RG_ANS_SEQ, NULL, SYSDATE); -- 처리결과코드는 NULL, 처리일자는 디폴트 SYSDATE
    END IF;
    
    
    -- 커밋
    COMMIT;
    
END;
--==>> Procedure PRC_RPT_REG_ANS_INSERT이(가) 컴파일되었습니다.





--○ 스터디 후기 게시판 신고 등록 테이블에 INSERT 후 -> 5회 쌓였는지 체크 -> 맞으면 신고처리에 인서트
CREATE OR REPLACE PROCEDURE PRC_RPT_REG_STDREVIEW_INSERT
( V_POST_CODE             IN TBL_BOARD_STUDYREVIEW.POST_CODE%TYPE
, V_USER_CODE             IN TBL_USER_CODE_CREATE.USER_CODE%TYPE
, V_REPORT_REASON         IN TBL_REPORT_REG_STUDYREVIEW.REPORT_REASON%TYPE
, V_POST_REPORT_CTG_CODE  IN TBL_POST_REPORT_CTG.POST_REPORT_CTG_CODE%TYPE
)
IS
    V_REG_CNT NUMBER;   -- 특정 게시물의 신고를 세는 변수
    V_RPT_RG_STDREVIEW_SEQ  TBL_REPORT_REG_STUDYREVIEW.POST_REPORT_CODE%TYPE; -- 자유게시판 신고등록 SEQ
BEGIN

    V_RPT_RG_STDREVIEW_SEQ := 'GR'||RPT_RG_ANSWER_SEQ.NEXTVAL;

    INSERT INTO TBL_REPORT_REG_STUDYREVIEW
    (POST_REPORT_CODE, POST_CODE, USER_CODE, REPORT_DATE, REPORT_REASON, POST_REPORT_CTG_CODE)
    VALUES(V_RPT_RG_STDREVIEW_SEQ, V_POST_CODE, V_USER_CODE, SYSDATE, V_REPORT_REASON, V_POST_REPORT_CTG_CODE);

    -- V_REG_CNT 초기화
    SELECT COUNT(*) AS CNT INTO V_REG_CNT
    FROM TBL_REPORT_REG_STUDYREVIEW
    WHERE POST_CODE = V_POST_CODE;
    
    -- 신고가 5회 쌓였는지 체크후 처리
    IF ( V_REG_CNT = 5) 
        THEN 
        INSERT INTO TBL_REPORT_HANDLE_STUDYREVIEW (REPORT_HANDLE_CODE, POST_REPORT_CODE, HANDLE_RESULT_CODE, HANDLE_DATE) 
                    VALUES ('HR'||RPT_HD_STUDYREVIEW_SEQ.NEXTVAL, V_RPT_RG_STDREVIEW_SEQ, NULL, SYSDATE); -- 처리결과코드는 NULL, 처리일자는 디폴트 SYSDATE
    END IF;
    
    
    -- 커밋
    COMMIT;
    
END;
--==>> Procedure PRC_RPT_REG_STDREVIEW_INSERT이(가) 컴파일되었습니다.




--○ 스터디 개설 게시판 신고 등록 테이블에 INSERT 후 -> 5회 쌓였는지 체크 -> 맞으면 신고처리에 인서트
CREATE OR REPLACE PROCEDURE PRC_RPT_REG_STDOPEN_INSERT
( V_STUDY_CODE            IN TBL_STUDY_OPEN.STUDY_CODE%TYPE
, V_USER_CODE             IN TBL_USER_CODE_CREATE.USER_CODE%TYPE
, V_REPORT_REASON         IN TBL_STUDY_ACCUSE.ACCUSE_REASON%TYPE
, V_POST_REPORT_CTG_CODE  IN TBL_POST_REPORT_CTG.POST_REPORT_CTG_CODE%TYPE
)
IS
    V_REG_CNT NUMBER;   -- 특정 게시물의 신고를 세는 변수
    V_RPT_RG_STDOPEN_SEQ  TBL_STUDY_ACCUSE.ACCUSE_CODE%TYPE; -- 자유게시판 신고등록 SEQ
BEGIN

    V_RPT_RG_STDOPEN_SEQ := 'AC'||STUDY_ACC_SEQ.NEXTVAL;

    INSERT INTO TBL_STUDY_ACCUSE
    (ACCUSE_CODE, STUDY_CODE, USER_CODE, ACCUSE_DATE, ACCUSE_REASON, POST_REPORT_CTG_CODE)
    VALUES(V_RPT_RG_STDOPEN_SEQ, V_STUDY_CODE, V_USER_CODE, SYSDATE, V_REPORT_REASON, V_POST_REPORT_CTG_CODE);

    -- V_REG_CNT 초기화
    SELECT COUNT(*) AS CNT INTO V_REG_CNT
    FROM TBL_STUDY_ACCUSE
    WHERE STUDY_CODE = V_STUDY_CODE;
    
    -- 신고가 5회 쌓였는지 체크후 처리
    IF ( V_REG_CNT = 5) 
        THEN 
        INSERT INTO TBL_STUDY_ACCUSE_HANDLE (ACCUSE_HANDLE_CODE, ACCUSE_CODE, HANDLE_RESULT_CODE, ACCUSE_HANDLE_DATE) 
                    VALUES ('AH'||STUDY_ACC_HAN_SEQ.NEXTVAL, V_RPT_RG_STDOPEN_SEQ, NULL, SYSDATE); -- 처리결과코드는 NULL, 처리일자는 디폴트 SYSDATE
    END IF;
    
    
    -- 커밋
    COMMIT;
    
END;
--==>> Procedure PRC_RPT_REG_STDOPEN_INSERT이(가) 컴파일되었습니다.




