SELECT USER
FROM DUAL;
--==>> STITKER
commit;

--계정정지 등록 프로시저 : 현재 취소안한, 신청한 스터디 중 종료되지 않은 것.(갖고있는 정보 : SUSPEND테이블의 WARNING_CODE)
CREATE OR REPLACE PROCEDURE PRC_INSERT_SUSPEND
(V_ACCT_SUS_DATE    IN  TBL_ACCOUNT_SUSPEND.ACCT_SUS_DATE%TYPE
, V_WARNING_CODE    IN  TBL_WARNING.WARNING_CODE%TYPE
)
IS
V_USER_CODE       TBL_USER_REGISTER.USER_CODE%TYPE;
APPLY_CNT       NUMBER := 0;
V_APPLY_CODE    TBL_STUDY_APPLY.APPLY_CODE%TYPE;
V_ACCT_SUS_CODE TBL_ACCOUNT_SUSPEND.ACCT_SUS_CODE%TYPE;
BEGIN
    V_ACCT_SUS_CODE := 'AS'||ACCT_SUS_SEQ.NEXTVAL;
    -- insert
    INSERT INTO TBL_ACCOUNT_SUSPEND(ACCT_SUS_CODE, ACCT_SUS_DATE, WARNING_CODE)
    VALUES(V_ACCT_SUS_CODE, V_ACCT_SUS_DATE, V_WARNING_CODE);
    
    SELECT W.USER_CODE INTO V_USER_CODE
    FROM TBL_ACCOUNT_SUSPEND S JOIN TBL_WARNING W
        ON S.WARNING_CODE = W.WARNING_CODE
    WHERE S.ACCT_SUS_CODE = V_ACCT_SUS_CODE;
    
    SELECT COUNT(*) INTO APPLY_CNT
    FROM INSERT_SUSPEND_VIEW
    WHERE USER_CODE = V_USER_CODE AND CANCEL_CODE IS NULL; 
    
    IF(APPLY_CNT > 0)
    THEN
        FOR I IN 1 .. APPLY_CNT
        LOOP
            -- 참가코드 가져오기
            SELECT T.APPLY_CODE INTO V_APPLY_CODE
            FROM 
            ( SELECT ROWNUM RNUM, APPLY_CODE, USER_CODE
              FROM INSERT_SUSPEND_VIEW
              WHERE USER_CODE = V_USER_CODE AND CANCEL_CODE IS NULL
            ) T 
            WHERE T.RNUM = 1; -- 취소시키면 CANCEL_CODE가 NULL이 아니게 되므로 RNUM 1로 맞춰주기  

            -- 해당 스터디 취소시키기
            PRC_INSERT_CANCEL( V_APPLY_CODE, V_ACCT_SUS_DATE, 1);
    
        END LOOP;
    END IF;  
    
    EXCEPTION WHEN OTHERS THEN ROLLBACK;

    COMMIT;
    
END;

