SELECT USER
FROM DUAL;
--==>> STITKER
commit;

--계정정지 등록 프로시저 : 현재 취소안한, 신청한 스터디 중 종료되지 않은 것.(갖고있는 정보 : SUSPEND테이블의 WARNING_CODE)
CREATE OR REPLACE PROCEDURE PRC_INSERT_SUSPEND
(V_ACCT_SUS_DATE    IN  TBL_ACCOUNT_SUSPEND.ACCT_SUS_DATE%TYPE
, V_WARNING_CODE    IN  TBL_WARNING.WARNING_CODE%TYPE
)
IS
V_USER_CODE       TBL_USER_REGISTER.USER_CODE%TYPE;
APPLY_CNT       NUMBER := 0;
V_APPLY_CODE    TBL_STUDY_APPLY.APPLY_CODE%TYPE;
V_ACCT_SUS_CODE TBL_ACCOUNT_SUSPEND.ACCT_SUS_CODE%TYPE;
BEGIN
    V_ACCT_SUS_CODE := 'AS'||ACCT_SUS_SEQ.NEXTVAL;
    -- insert
    INSERT INTO TBL_ACCOUNT_SUSPEND(ACCT_SUS_CODE, ACCT_SUS_DATE, WARNING_CODE)
    VALUES(V_ACCT_SUS_CODE, V_ACCT_SUS_DATE, V_WARNING_CODE);
    
    SELECT W.USER_CODE INTO V_USER_CODE
    FROM TBL_ACCOUNT_SUSPEND S JOIN TBL_WARNING W
        ON S.WARNING_CODE = W.WARNING_CODE
    WHERE S.ACCT_SUS_CODE = V_ACCT_SUS_CODE;
    
    SELECT COUNT(*) INTO APPLY_CNT
    FROM INSERT_SUSPEND_VIEW
    WHERE USER_CODE = V_USER_CODE AND CANCEL_CODE IS NULL; 
    
    IF(APPLY_CNT > 0)
    THEN
        FOR I IN 1 .. APPLY_CNT
        LOOP
            -- 참가코드 가져오기
            SELECT T.APPLY_CODE INTO V_APPLY_CODE
            FROM 
            ( SELECT ROWNUM RNUM, APPLY_CODE, USER_CODE
              FROM INSERT_SUSPEND_VIEW
              WHERE USER_CODE = V_USER_CODE AND CANCEL_CODE IS NULL
            ) T 
            WHERE T.RNUM = 1; -- 취소시키면 CANCEL_CODE가 NULL이 아니게 되므로 RNUM 1로 맞춰주기  

            -- 해당 스터디 취소시키기
            PRC_INSERT_CANCEL( V_APPLY_CODE, V_ACCT_SUS_DATE, 1);
    
        END LOOP;
    END IF;  
    
    EXCEPTION WHEN OTHERS THEN ROLLBACK;

    COMMIT;
    
END;


-- 신고 등록 프로시저
CREATE OR REPLACE PROCEDURE PRC_MEM_RPT_REG_INSERT
( V_REPORT_REG_DATE     TBL_MEM_REPORT_REG.REPORT_REG_DATE%TYPE
, V_REPORT_USER_CODE    TBL_USER_CODE_CREATE.USER_CODE%TYPE
, V_MEM_REPORT_CTG_CODE TBL_MEM_REPORT_CTG.MEM_REPORT_CTG_CODE%TYPE
, V_REPORT_REG_REASON   TBL_MEM_REPORT_REG.REPORT_REG_REASON%TYPE 
, V_REPORTED_USER_CODE  TBL_USER_CODE_CREATE.USER_CODE%TYPE
, V_STUDY_CODE          TBL_STUDY_OPEN.STUDY_CODE%TYPE
)
IS
    V_MEM_REPORT_REG_CODE VARCHAR(15) := 'RR'||MEM_RR_SEQ.NEXTVAL;
    V_APPLY_NUM    NUMBER;               
    V_REPORT_NUM   NUMBER;
    V_PARTI_REPORT_CODE   TBL_STUDY_PARTICIPANT.PARTI_CODE%TYPE;  
    V_PARTI_REPORTED_CODE TBL_STUDY_PARTICIPANT.PARTI_CODE%TYPE;   
BEGIN
    -- ○ 참여 코드 가져오기
    SELECT P.PARTI_CODE INTO V_PARTI_REPORT_CODE
    FROM TBL_STUDY_PARTICIPANT P JOIN TBL_STUDY_APPLY A
      ON P.APPLY_CODE = A.APPLY_CODE
    WHERE A.USER_CODE = V_REPORT_USER_CODE AND A.STUDY_CODE = V_STUDY_CODE;
    SELECT P.PARTI_CODE INTO V_PARTI_REPORTED_CODE
    FROM TBL_STUDY_PARTICIPANT P JOIN TBL_STUDY_APPLY A
      ON P.APPLY_CODE = A.APPLY_CODE
    WHERE A.USER_CODE = V_REPORTED_USER_CODE AND A.STUDY_CODE = V_STUDY_CODE;

    -- ○ 스터디원 신고 등록
    INSERT INTO TBL_MEM_REPORT_REG(MEM_REPORT_REG_CODE, PARTI_REPORT_CODE, REPORT_REG_DATE, MEM_REPORT_CTG_CODE, REPORT_REG_REASON, PARTI_REPORTED_CODE) 
    VALUES(V_MEM_REPORT_REG_CODE, V_PARTI_REPORT_CODE, V_REPORT_REG_DATE, V_MEM_REPORT_CTG_CODE, V_REPORT_REG_REASON, V_PARTI_REPORTED_CODE);

    -- 현재 진행중인 인원
    SELECT COUNT(*) INTO V_APPLY_NUM
    FROM TBL_STUDY_APPLY A LEFT JOIN TBL_STUDY_CANCEL C
      ON A.APPLY_CODE = C.APPLY_CODE
    WHERE A.STUDY_CODE = V_STUDY_CODE AND C.CANCEL_CODE IS NULL;
    
    -- 신고를 누른 사람 수
    SELECT COUNT(*) INTO V_REPORT_NUM
    FROM TBL_MEM_REPORT_REG
    WHERE PARTI_REPORTED_CODE = V_PARTI_REPORTED_CODE;
    IF( V_REPORT_NUM / V_APPLY_NUM >= 0.5 )
     THEN
        -- 스터디원 신고처리에 등록
        INSERT INTO TBL_MEM_REPORT_HANDLE(MEM_REPORT_HANDLE_CODE, MEM_REPORT_REG_CODE, HANDLE_RESULT, HANDLE_DATE)
        VALUES('MR'||MEM_RH_SEQ.NEXTVAL, V_MEM_REPORT_REG_CODE, NULL, V_REPORT_REG_DATE);

    END IF;
    
    EXCEPTION WHEN OTHERS THEN ROLLBACK;
    
    COMMIT;
END;


--==>>
/*
RR1	PT1	2021-01-16	RC3	너무공격적이에요ㅠ	PT2
RR2	PT3	2021-01-16	RC1	저를 왕따시켜요	PT2
*/


EXEC PRC_MEM_RPT_REG_INSERT(SYSDATE-8, 'UC5', 'RC3', '너무 공격적이에요ㅠ', 'UC2', 'SO2');
EXEC PRC_MEM_RPT_REG_INSERT(SYSDATE-2, 'UC3', 'RC1', '저를 왕따시켜요', 'UC2', 'SO2');
