    -- 스터디 후기 테이블
CREATE TABLE TBL_BOARD_STUDYREVIEW
( POST_CODE         VARCHAR2(15)     --PK
, PARTI_CODE        VARCHAR2(15)    NOT NULL --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, HITCOUNT          NUMBER          DEFAULT 0 NOT NULL
, TITLE             VARCHAR2(300)   NOT NULL
, CONTENT           VARCHAR2(4000)  NOT NULL
, INTEREST_MC_CODE  VARCHAR2(20)    NOT NULL --FK
, CONSTRAINT BRD_STRV_PC_PK PRIMARY KEY(POST_CODE)
, CONSTRAINT BRD_STRV_PTC_FK FOREIGN KEY(PARTI_CODE)
             REFERENCES TBL_STUDY_PARTICIPANT(PARTI_CODE)
, CONSTRAINT BRD_STRV_IRMCC_FK FOREIGN KEY(INTEREST_MC_CODE)
             REFERENCES TBL_INTEREST_MC(INTEREST_MC_CODE)
);



  -- 스터디 후기 댓글 등록
CREATE TABLE TBL_COMMENT_STUDYREVIEW
( COMMENT_CODE      VARCHAR2(10)        --PK
, POST_CODE         VARCHAR2(15)    NOT NULL    --FK
, COMMENTS          VARCHAR2(800)   NOT NULL
, USER_CODE         VARCHAR2(10)    NOT NULL    --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT CMT_STRV_CC_PK PRIMARY KEY(COMMENT_CODE)
, CONSTRAINT CMT_STRV_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_STUDYREVIEW(POST_CODE)
, CONSTRAINT CMT_STRV_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
);


    -- 스터디 후기 추천/ 비추천 테이블
CREATE TABLE TBL_REC_STUDYREVIEW
( REC_CODE          VARCHAR2(20)     --PK
, POST_CODE         VARCHAR2(15)    NOT NULL --FK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, REC_CHECK         NUMBER          NOT NULL
, REC_DATE          DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT REC_STRV_RC_PK PRIMARY KEY(REC_CODE)
, CONSTRAINT REC_STRV_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_STUDYREVIEW(POST_CODE)
, CONSTRAINT REC_STRV_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
);
 
    -- 스터디 후기 신고 등록
CREATE TABLE TBL_REPORT_REG_STUDYREVIEW
( POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --PK
, POST_CODE             VARCHAR2(15)    NOT NULL --FK
, USER_CODE             VARCHAR2(10)    NOT NULL --FK
, REPORT_DATE           DATE            DEFAULT SYSDATE NOT NULL
, REPORT_REASON         VARCHAR2(400)   NOT NULL
, POST_REPORT_CTG_CODE  VARCHAR2(10)    NOT NULL --FK
, CONSTRAINT RPT_REG_STRV_PRC_PK PRIMARY KEY(POST_REPORT_CODE)
, CONSTRAINT RPT_REG_STRV_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_STUDYREVIEW(POST_CODE)
, CONSTRAINT RPT_REG_STRV_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CREATE(USER_CODE)
, CONSTRAINT RPT_REG_STRV_PRCC_FK FOREIGN KEY(POST_REPORT_CTG_CODE)
             REFERENCES TBL_POST_REPORT_CTG(POST_REPORT_CTG_CODE)
); 


    -- 스터디 후기 신고 처리  
CREATE TABLE TBL_REPORT_HANDLE_STUDYREVIEW
( REPORT_HANDLE_CODE    VARCHAR2(15)    NOT NULL --PK
, POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --FK
, HANDLE_RESULT_CODE    VARCHAR2(5)              --FK
, HANDLE_DATE           DATE 
, CONSTRAINT RPT_HLE_STRV_RHC_PK PRIMARY KEY(REPORT_HANDLE_CODE)
, CONSTRAINT RPT_HLE_STRV_PRC_FK FOREIGN KEY(POST_REPORT_CODE)
             REFERENCES TBL_REPORT_REG_STUDYREVIEW(POST_REPORT_CODE)
, CONSTRAINT RPT_HLE_STRV_HR_FK FOREIGN KEY(HANDLE_RESULT_CODE)
             REFERENCES TBL_HANDLE_RESULT(HANDLE_RESULT_CODE)         
);  
 