--○ 실습 테이블 생성(IT기술정보공유 테이블)
CREATE TABLE TBL_BOARD_INFORM
( POST_CODE         VARCHAR2(15)     --PK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, HITCOUNT          NUMBER          DEFAULT 0 NOT NULL
, TITLE             VARCHAR2(300)   NOT NULL
, CONTENT           VARCHAR2(4000)  NOT NULL
, INTEREST_MC_CODE  VARCHAR2(20)    NOT NULL --FK
, CONSTRAINT BRD_INFO_PC_PK PRIMARY KEY(POST_CODE)
, CONSTRAINT BRD_INFO_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
, CONSTRAINT BRD_INFO_IRMCC_FK FOREIGN KEY(INTEREST_MC_CODE)
             REFERENCES TBL_INTEREST_MC(INTEREST_MC_CODE)
);

--○ 실습 테이블 생성(면접/코딩테스트 후기 테이블)
CREATE TABLE TBL_BOARD_INTERVIEW
( POST_CODE         VARCHAR2(15)     --PK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, HITCOUNT          NUMBER          DEFAULT 0 NOT NULL
, TITLE             VARCHAR2(300)   NOT NULL
, CONTENT           VARCHAR2(4000)  NOT NULL
, INTEREST_MC_CODE  VARCHAR2(20)    NOT NULL --FK
, CONSTRAINT BRD_INTER_PC_PK PRIMARY KEY(POST_CODE)
, CONSTRAINT BRD_INTER_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
, CONSTRAINT BRD_INTER_IRMCC_FK FOREIGN KEY(INTEREST_MC_CODE)
             REFERENCES TBL_INTEREST_MC(INTEREST_MC_CODE)
);

--○ 실습 테이블 생성(세미나 및 공모전 테이블)
CREATE TABLE TBL_BOARD_SEMINAR
( POST_CODE         VARCHAR2(15)         --PK
, USER_CODE         VARCHAR2(10)        NOT NULL --FK
, WRITE_DATE        DATE                DEFAULT SYSDATE NOT NULL
, HITCOUNT          NUMBER              DEFAULT 0 NOT NULL
, TITLE             VARCHAR2(300)       NOT NULL
, CONTENT           VARCHAR2(4000)      NOT NULL
, SEMINAR_CATEGORY_CODE  VARCHAR2(20)   NOT NULL --FK
, CONSTRAINT BRD_SEMI_PC_PK PRIMARY KEY(POST_CODE)
, CONSTRAINT BRD_SEMI_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
, CONSTRAINT BRD_SEMI_SMCTC_FK FOREIGN KEY(SEMINAR_CATEGORY_CODE)
             REFERENCES TBL_SEMINAR_CATEGORY(SEMINAR_CATEGORY_CODE)
);

--○ 실습 테이블 생성(자유게시판 테이블)
CREATE TABLE TBL_BOARD_FREE
( POST_CODE         VARCHAR2(15)     --PK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, HITCOUNT          NUMBER          DEFAULT 0 NOT NULL
, TITLE             VARCHAR2(300)   NOT NULL
, CONTENT           VARCHAR2(4000)  NOT NULL
, CONSTRAINT BRD_FREE_PC_PK PRIMARY KEY(POST_CODE)
, CONSTRAINT BRD_FREE_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
);

--○ 실습 테이블 생성(Q&A 질문 테이블)
CREATE TABLE TBL_BOARD_QUESTION
( POST_CODE         VARCHAR2(15)     --PK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, HITCOUNT          NUMBER          DEFAULT 0 NOT NULL
, TITLE             VARCHAR2(300)   NOT NULL
, CONTENT           VARCHAR2(4000)  NOT NULL
, INTEREST_MC_CODE  VARCHAR2(20)    NOT NULL --FK
, CONSTRAINT BRD_QUE_PC_PK PRIMARY KEY(POST_CODE)
, CONSTRAINT BRD_QUE_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
, CONSTRAINT BRD_QUE_IRMCC_FK FOREIGN KEY(INTEREST_MC_CODE)
             REFERENCES TBL_INTEREST_MC(INTEREST_MC_CODE)
);

--○ 실습 테이블 생성(Q&A 답변 테이블)
CREATE TABLE TBL_BOARD_ANSWER
( POST_CODE         VARCHAR2(15)     --PK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, HITCOUNT          NUMBER          DEFAULT 0 NOT NULL
, TITLE             VARCHAR2(300)   NOT NULL
, CONTENT           VARCHAR2(4000)  NOT NULL
, INTEREST_MC_CODE  VARCHAR2(20)    NOT NULL --FK
, CONSTRAINT BRD_AWR_PC_PK PRIMARY KEY(POST_CODE)
, CONSTRAINT BRD_AWR_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
, CONSTRAINT BRD_AWR_IRMCC_FK FOREIGN KEY(INTEREST_MC_CODE)
             REFERENCES TBL_INTEREST_MC(INTEREST_MC_CODE)
);

--○ 실습 테이블 생성(IT기술정보공유 댓글 테이블)
CREATE TABLE TBL_COMMENT_INFORM
( COMMENT_CODE      VARCHAR2(10)        --PK
, POST_CODE         VARCHAR2(15)    NOT NULL    --FK
, COMMENT           VARCHAR2(800)   NOT NULL
, USER_CODE         VARCHAR2(10)    NOT NULL    --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT CMT_INFO_CC_PK PRIMARY KEY(COMMENT_CODE)
, CONSTRAINT CMT_INFO_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_INFORM(POST_CODE)
, CONSTRAINT CMT_INFO_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
);

--○ 실습 테이블 생성(면접 및 코딩테스트 후기 댓글 테이블)
CREATE TABLE TBL_COMMENT_INTERVIEW
( COMMENT_CODE      VARCHAR2(10)        --PK
, POST_CODE         VARCHAR2(15)    NOT NULL    --FK
, COMMENT           VARCHAR2(800)   NOT NULL
, USER_CODE         VARCHAR2(10)    NOT NULL    --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT CMT_INTER_CC_PK PRIMARY KEY(COMMENT_CODE)
, CONSTRAINT CMT_INTER_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_INTERVIEW(POST_CODE)
, CONSTRAINT CMT_INTER_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
);

--○ 실습 테이블 생성(세미나 및 공모전 댓글 테이블)
CREATE TABLE TBL_COMMENT_SEMINAR
( COMMENT_CODE      VARCHAR2(10)        --PK
, POST_CODE         VARCHAR2(15)    NOT NULL    --FK
, COMMENT           VARCHAR2(800)   NOT NULL
, USER_CODE         VARCHAR2(10)    NOT NULL    --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT CMT_SEMI_CC_PK PRIMARY KEY(COMMENT_CODE)
, CONSTRAINT CMT_SEMI_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_SEMINAR(POST_CODE)
, CONSTRAINT CMT_SEMI_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
);

--○ 실습 테이블 생성(자유게시판 댓글 테이블)
CREATE TABLE TBL_COMMENT_FREE
( COMMENT_CODE      VARCHAR2(10)        --PK
, POST_CODE         VARCHAR2(15)    NOT NULL    --FK
, COMMENT           VARCHAR2(800)   NOT NULL
, USER_CODE         VARCHAR2(10)    NOT NULL    --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT CMT_FREE_CC_PK PRIMARY KEY(COMMENT_CODE)
, CONSTRAINT CMT_FREE_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_FREE(POST_CODE)
, CONSTRAINT CMT_FREE_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
);

--○ 실습 테이블 생성(Q&A 질문 댓글 테이블)
CREATE TABLE TBL_COMMENT_QUESTION
( COMMENT_CODE      VARCHAR2(10)        --PK
, POST_CODE         VARCHAR2(15)    NOT NULL    --FK
, COMMENT           VARCHAR2(800)   NOT NULL
, USER_CODE         VARCHAR2(10)    NOT NULL    --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT CMT_QUE_CC_PK PRIMARY KEY(COMMENT_CODE)
, CONSTRAINT CMT_QUE_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_QUESTION(POST_CODE)
, CONSTRAINT CMT_QUE_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
);

--○ 실습 테이블 생성(Q&A 답변 댓글 테이블)
CREATE TABLE TBL_COMMENT_ANSWER
( COMMENT_CODE      VARCHAR2(10)        --PK
, POST_CODE         VARCHAR2(15)    NOT NULL    --FK
, COMMENT           VARCHAR2(800)   NOT NULL
, USER_CODE         VARCHAR2(10)    NOT NULL    --FK
, WRITE_DATE        DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT CMT_AWR_CC_PK PRIMARY KEY(COMMENT_CODE)
, CONSTRAINT CMT_AWR_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_ANSWER(POST_CODE)
, CONSTRAINT CMT_AWR_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
);

--○ 실습 테이블 생성(IT기술정보공유 추천비추천 테이블)
CREATE TABLE TBL_REC_INFORM
( REC_CODE          VARCHAR2(20)    --PK
, POST_CODE         VARCHAR2(15)    NOT NULL --FK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, REC_CHECK         NUMBER          NOT NULL
, REC_DATE          DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT REC_INFO_RC_PK PRIMARY KEY(REC_CODE)
, CONSTRAINT REC_INFO_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_INFORM(POST_CODE)
, CONSTRAINT REC_INFO_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
);

--○ 실습 테이블 생성(세미나 및 공모전 추천비추천 테이블)
CREATE TABLE TBL_REC_SEMINAR
( REC_CODE          VARCHAR2(20)    --PK
, POST_CODE         VARCHAR2(15)    NOT NULL --FK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, REC_CHECK         NUMBER          NOT NULL
, REC_DATE          DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT REC_SEMI_RC_PK PRIMARY KEY(REC_CODE)
, CONSTRAINT REC_SEMI_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_SEMINAR(POST_CODE)
, CONSTRAINT REC_SEMI_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
);

--○ 실습 테이블 생성(면접/코딩테스트 후기 추천비추천 테이블)
CREATE TABLE TBL_REC_INTERVIEW
( REC_CODE          VARCHAR2(20)    --PK
, POST_CODE         VARCHAR2(15)    NOT NULL --FK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, REC_CHECK         NUMBER          NOT NULL
, REC_DATE          DATE            DEFAULT SYSDATE NOT NULL       DATE
, CONSTRAINT REC_INTER_RC_PK PRIMARY KEY(REC_CODE)
, CONSTRAINT REC_INTER_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_INTERVIEW(POST_CODE)
, CONSTRAINT REC_INTER_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
);


--○ 실습 테이블 생성(자유게시판 추천비추천 테이블)
CREATE TABLE TBL_REC_FREE
( REC_CODE          VARCHAR2(20)    --PK
, POST_CODE         VARCHAR2(15)    NOT NULL --FK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, REC_CHECK         NUMBER          NOT NULL
, REC_DATE          DATE            DEFAULT SYSDATE NOT NULL       DATE
, CONSTRAINT REC_FREE_RC_PK PRIMARY KEY(REC_CODE)
, CONSTRAINT REC_FREE_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_FREE(POST_CODE)
, CONSTRAINT REC_FREE_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
);

--○ 실습 테이블 생성(Q&A 질문 추천비추천 테이블)
CREATE TABLE TBL_REC_QUESTION
( REC_CODE          VARCHAR2(20)    --PK
, POST_CODE         VARCHAR2(15)    --FK
, USER_CODE         VARCHAR2(10)    --FK
, REC_CHECK         NUMBER
, REC_DATE          DATE
, CONSTRAINT REC_QUE_RC_PK PRIMARY KEY(REC_CODE)
, CONSTRAINT REC_QUE_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_QUESTION(POST_CODE)
, CONSTRAINT REC_QUE_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
);


--○ 실습 테이블 생성(Q&A 답변 추천비추천 테이블)
CREATE TABLE TBL_REC_ANSWER
( REC_CODE          VARCHAR2(20)    NOT NULL --PK
, POST_CODE         VARCHAR2(15)    NOT NULL --FK
, USER_CODE         VARCHAR2(10)    NOT NULL --FK
, REC_CHECK         NUMBER          NOT NULL
, REC_DATE          DATE            DEFAULT SYSDATE NOT NULL
, CONSTRAINT REC_AWR_RC_PK PRIMARY KEY(REC_CODE)
, CONSTRAINT REC_AWR_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_BOARD_ANSWER(POST_CODE)
, CONSTRAINT REC_AWR_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
);

--○ 실습 테이블 생성(IT기술정보공유 신고등록 테이블)
CREATE TABLE TBL_REPORT_REG_INFORM
( POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --PK
, POST_CODE             VARCHAR2(15)    NOT NULL --FK
, USER_CODE             VARCHAR2(10)    NOT NULL --FK
, REPORT_DATE           DATE            DEFAULT SYSDATE NOT NULL
, REPORT_REASON         VARCHAR2(400)   NOT NULL
, POST_REPORT_CTG_CODE  VARCHAR2(10)    NOT NULL --FK
, CONSTRAINT RPT_REG_INFO_PRC_PK PRIMARY KEY(POST_REPORT_CODE)
, CONSTRAINT RPT_REG_INFO_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_REPORT_REG_INFORM(POST_CODE)
, CONSTRAINT RPT_REG_INFO_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
, CONSTRAINT RPT_REG_INFO_PRCC_FK FOREIGN KEY(POST_REPORT_CTG_CODE)
             REFERENCES TBL_POST_REPORT_CTG(POST_REPORT_CTG_CODE)
);

--○ 실습 테이블 생성(면접/코딩테스트 후기  신고등록 테이블)
CREATE TABLE TBL_REPORT_REG_INTERVIEW
( POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --PK
, POST_CODE             VARCHAR2(15)    NOT NULL --FK
, USER_CODE             VARCHAR2(10)    NOT NULL --FK
, REPORT_DATE           DATE            DEFAULT SYSDATE NOT NULL
, REPORT_REASON         VARCHAR2(400)   NOT NULL
, POST_REPORT_CTG_CODE  VARCHAR2(10)    NOT NULL --FK
, CONSTRAINT RPT_REG_INTER_PRC_PK PRIMARY KEY(POST_REPORT_CODE)
, CONSTRAINT RPT_REG_INTER_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_REPORT_REG_INTERVIEW(POST_CODE)
, CONSTRAINT RPT_REG_INTER_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
, CONSTRAINT RPT_REG_INTER_PRCC_FK FOREIGN KEY(POST_REPORT_CTG_CODE)
             REFERENCES TBL_POST_REPORT_CTG(POST_REPORT_CTG_CODE)
);

--○ 실습 테이블 생성(세미나 및 공모전  신고등록 테이블)
CREATE TABLE TBL_REPORT_REG_SEMINAR
( POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --PK
, POST_CODE             VARCHAR2(15)    NOT NULL --FK
, USER_CODE             VARCHAR2(10)    NOT NULL --FK
, REPORT_DATE           DATE            DEFAULT SYSDATE NOT NULL
, REPORT_REASON         VARCHAR2(400)   NOT NULL
, POST_REPORT_CTG_CODE  VARCHAR2(10)    NOT NULL --FK
, CONSTRAINT RPT_REG_SEMI_PRC_PK PRIMARY KEY(POST_REPORT_CODE)
, CONSTRAINT RPT_REG_SEMI_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_REPORT_REG_SEMINAR(POST_CODE)
, CONSTRAINT RPT_REG_SEMI_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
, CONSTRAINT RPT_REG_SEMI_PRCC_FK FOREIGN KEY(POST_REPORT_CTG_CODE)
             REFERENCES TBL_POST_REPORT_CTG(POST_REPORT_CTG_CODE)
);

--○ 실습 테이블 생성(자유게시판 신고등록 테이블)
CREATE TABLE TBL_REPORT_REG_FREE
( POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --PK
, POST_CODE             VARCHAR2(15)    NOT NULL --FK
, USER_CODE             VARCHAR2(10)    NOT NULL --FK
, REPORT_DATE           DATE            DEFAULT SYSDATE NOT NULL
, REPORT_REASON         VARCHAR2(400)   NOT NULL
, POST_REPORT_CTG_CODE  VARCHAR2(10)    NOT NULL --FK
, CONSTRAINT RPT_REG_FREE_PRC_PK PRIMARY KEY(POST_REPORT_CODE)
, CONSTRAINT RPT_REG_FREE_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_REPORT_REG_FREE(POST_CODE)
, CONSTRAINT RPT_REG_FREE_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
, CONSTRAINT RPT_REG_FREE_PRCC_FK FOREIGN KEY(POST_REPORT_CTG_CODE)
             REFERENCES TBL_POST_REPORT_CTG(POST_REPORT_CTG_CODE)
);


--○ 실습 테이블 생성(Q&A 질문 신고등록 테이블)
CREATE TABLE TBL_REPORT_REG_QUESTION
( POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --PK
, POST_CODE             VARCHAR2(15)    NOT NULL --FK
, USER_CODE             VARCHAR2(10)    NOT NULL --FK
, REPORT_DATE           DATE            DEFAULT SYSDATE NOT NULL
, REPORT_REASON         VARCHAR2(400)   NOT NULL
, POST_REPORT_CTG_CODE  VARCHAR2(10)    NOT NULL --FK
, CONSTRAINT RPT_REG_QUE_PRC_PK PRIMARY KEY(POST_REPORT_CODE)
, CONSTRAINT RPT_REG_QUE_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_REPORT_REG_QUESTION(POST_CODE)
, CONSTRAINT RPT_REG_QUE_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
, CONSTRAINT RPT_REG_QUE_PRCC_FK FOREIGN KEY(POST_REPORT_CTG_CODE)
             REFERENCES TBL_POST_REPORT_CTG(POST_REPORT_CTG_CODE)
);

--○ 실습 테이블 생성(Q&A 답변 신고등록 테이블)
CREATE TABLE TBL_REPORT_REG_ANSWER
( POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --PK
, POST_CODE             VARCHAR2(15)    NOT NULL --FK
, USER_CODE             VARCHAR2(10)    NOT NULL --FK
, REPORT_DATE           DATE            DEFAULT SYSDATE NOT NULL
, REPORT_REASON         VARCHAR2(400)   NOT NULL
, POST_REPORT_CTG_CODE  VARCHAR2(10)    NOT NULL --FK
, CONSTRAINT RPT_REG_AWR_PRC_PK PRIMARY KEY(POST_REPORT_CODE)
, CONSTRAINT RPT_REG_AWR_PC_FK FOREIGN KEY(POST_CODE)
             REFERENCES TBL_REPORT_REG_ANSWER(POST_CODE)
, CONSTRAINT RPT_REG_AWR_UC_FK FOREIGN KEY(USER_CODE)
             REFERENCES TBL_USER_CODE_CRATE(USER_CODE)
, CONSTRAINT RPT_REG_AWR_PRCC_FK FOREIGN KEY(POST_REPORT_CTG_CODE)
             REFERENCES TBL_POST_REPORT_CTG(POST_REPORT_CTG_CODE)
);

--○ 실습 테이블 생성(IT기술정보공유 신고처리 테이블)
CREATE TABLE TBL_REPORT_HANDLE_INFORM
( REPORT_HANDLE_CODE    VARCHAR2(15)    NOT NULL --PK
, POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --FK
, HANDLE_RESULT         VARCHAR2(5)              --FK
, HANDLE_DATE           DATE            
, CONSTRAINT RPT_HLE_INFO_RHC_PK PRIMARY KEY(REPORT_HANDLE_CODE)
, CONSTRAINT RPT_HLE_INFO_PRC_FK FOREIGN KEY(POST_REPORT_CODE)
             REFERENCES TBL_REPORT_REG_INFORM(POST_REPORT_CODE)
, CONSTRAINT RPT_HLE_INFO_HR_FK FOREIGN KEY(HANDLE_RESULT)
             REFERENCES TBL_HANDLE_RESULT(HANDLE_RESULT)         
);

--○ 실습 테이블 생성(면접/코딩테스트 후기 신고처리 테이블)
CREATE TABLE TBL_REPORT_HANDLE_INTERVIEW
( REPORT_HANDLE_CODE    VARCHAR2(15)    NOT NULL --PK
, POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --FK
, HANDLE_RESULT         VARCHAR2(5)              --FK
, HANDLE_DATE           DATE 
, CONSTRAINT RPT_HLE_INTER_RHC_PK PRIMARY KEY(REPORT_HANDLE_CODE)
, CONSTRAINT RPT_HLE_INTER_PRC_FK FOREIGN KEY(POST_REPORT_CODE)
             REFERENCES TBL_REPORT_REG_INTERVIEW(POST_REPORT_CODE)
, CONSTRAINT RPT_HLE_INTER_HR_FK FOREIGN KEY(HANDLE_RESULT)
             REFERENCES TBL_HANDLE_RESULT(HANDLE_RESULT)         
);

--○ 실습 테이블 생성(세미나 및 공모전 신고처리 테이블)
CREATE TABLE TBL_REPORT_HANDLE_SEMINAR
( REPORT_HANDLE_CODE    VARCHAR2(15)    NOT NULL --PK
, POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --FK
, HANDLE_RESULT         VARCHAR2(5)              --FK
, HANDLE_DATE           DATE 
, CONSTRAINT RPT_HLE_SEMI_RHC_PK PRIMARY KEY(REPORT_HANDLE_CODE)
, CONSTRAINT RPT_HLE_SEMI_PRC_FK FOREIGN KEY(POST_REPORT_CODE)
             REFERENCES TBL_REPORT_REG_SEMINAR(POST_REPORT_CODE)
, CONSTRAINT RPT_HLE_SEMI_HR_FK FOREIGN KEY(HANDLE_RESULT)
             REFERENCES TBL_HANDLE_RESULT(HANDLE_RESULT)         
);

--○ 실습 테이블 생성(자유게시판 신고처리 테이블)
CREATE TABLE TBL_REPORT_HANDLE_FREE
( REPORT_HANDLE_CODE    VARCHAR2(15)    NOT NULL --PK
, POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --FK
, HANDLE_RESULT         VARCHAR2(5)              --FK
, HANDLE_DATE           DATE 
, CONSTRAINT RPT_HLE_FREE_RHC_PK PRIMARY KEY(REPORT_HANDLE_CODE)
, CONSTRAINT RPT_HLE_FREE_PRC_FK FOREIGN KEY(POST_REPORT_CODE)
             REFERENCES TBL_REPORT_REG_FREE(POST_REPORT_CODE)
, CONSTRAINT RPT_HLE_FREE_HR_FK FOREIGN KEY(HANDLE_RESULT)
             REFERENCES TBL_HANDLE_RESULT(HANDLE_RESULT)         
);

--○ 실습 테이블 생성(Q&A 질문 신고처리 테이블)
CREATE TABLE TBL_REPORT_HANDLE_QUESTION
( REPORT_HANDLE_CODE    VARCHAR2(15)    NOT NULL --PK
, POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --FK
, HANDLE_RESULT         VARCHAR2(5)              --FK
, HANDLE_DATE           DATE 
, CONSTRAINT RPT_HLE_QUE_RHC_PK PRIMARY KEY(REPORT_HANDLE_CODE)
, CONSTRAINT RPT_HLE_QUE_PRC_FK FOREIGN KEY(POST_REPORT_CODE)
             REFERENCES TBL_REPORT_REG_QUESTION(POST_REPORT_CODE)
, CONSTRAINT RPT_HLE_QUE_HR_FK FOREIGN KEY(HANDLE_RESULT)
             REFERENCES TBL_HANDLE_RESULT(HANDLE_RESULT)         
);

--○ 실습 테이블 생성(Q&A 답변 신고처리 테이블)
CREATE TABLE TBL_REPORT_HANDLE_ANSWER
( REPORT_HANDLE_CODE    VARCHAR2(15)    NOT NULL --PK
, POST_REPORT_CODE      VARCHAR2(15)    NOT NULL --FK
, HANDLE_RESULT         VARCHAR2(5)              --FK
, HANDLE_DATE           DATE 
, CONSTRAINT RPT_HLE_AWR_RHC_PK PRIMARY KEY(REPORT_HANDLE_CODE)
, CONSTRAINT RPT_HLE_AWR_PRC_FK FOREIGN KEY(POST_REPORT_CODE)
             REFERENCES TBL_REPORT_REG_ANSWER(POST_REPORT_CODE)
, CONSTRAINT RPT_HLE_AWR_HR_FK FOREIGN KEY(HANDLE_RESULT)
             REFERENCES TBL_HANDLE_RESULT(HANDLE_RESULT)         
);

--○ 실습 테이블 생성(신고 처리 테이블)
CREATE TABLE TBL_HANDLE_RESULT
( HANDLE_RESULT_CODE    VARCHAR2(5)    NOT NULL --PK
, HANDLE_RESULT         VARCHAR2(20)   NOT NULL 
, CONSTRAINT HLE_RES_HRC_PK PRIMARY KEY(HANDLE_RESULT_CODE)        
);

--○ 실습 테이블 생성(세미나 카테고리 테이블)
CREATE TABLE TBL_SEMINAR_CATEGORY
( SEMINAR_CATEGORY_CODE    VARCHAR2(20)    NOT NULL --PK
, SEMINAR_CATEGORY         VARCHAR2(300)   NOT NULL 
, CONSTRAINT SEMI_CTG_PK PRIMARY KEY(SEMINAR_CATEGORY_CODE)        
);

--○ 실습 테이블 생성(게시글 신고 카테고리 테이블)
CREATE TABLE TBL_POST_REPORT_CTG
( POST_REPORT_CTG_CODE     VARCHAR2(10)    NOT NULL --PK
, POST_REPORT_CTG          VARCHAR2(100)   NOT NULL 
, CONSTRAINT POST_RPT_CTG_PRCC_PK PRIMARY KEY(POST_REPORT_CTG_CODE)       
);




















